### ISSUE TITLE
关于一个项目中有多个CYLTabBarController的问题

### ISSUE THREAD

**Issue by zengfxios** [ChenYilong/CYLTabBarController#100]
我现在的项目中包含两个：CYLTabBarController，其中一个不显示plusbutton,另一个显示plusbutton。这样的场景，该如何设置plusbutton?

**Comment by ChenYilong** [comment]
暂时还不支持

**Comment by xiaoer** [comment]
可以问一下这个问题最后解决了嘛？ 我好像也有这个问题。目前还是无法设置嘛？

**Comment by include11** [comment]
同样存在这样的需求

**Comment by xiaoer** [comment]
我目前是把原有的demo自己重新按照他的流程，换个名字再次封装一下，但要注意里面的全局变量的重命名！

**Comment by ChenYilong** [comment]
发个你的做法的demo到我邮箱吧，我支持下该功能 luohanchenyilong@163.com

**Comment by ChenYilong** [comment]
@xiaoer 发个demo给我吧

**Comment by xiaoer** [comment]
这两天，我整理一下，发个demo给你。目前在公司的项目里写的，我摘一下

**Comment by ChenYilong** [comment]
多谢

**Comment by ChenYilong** [comment]
大家的业务场景是不是都是这样的：例如说 原来的 airbnb 。买家端和买家端是在一个APP里面。在买家主页里面一个按钮切换成 卖家，买家没有上传功能，但卖家有上传功能。所以需要多个TabBar

**Comment by ChenYilong** [comment]
我的思路是给每个TabBar加个context属性，上下文，plusButton也加个，只有匹配上时才展示plusButton。如果tabbar和plusButton都不设置context，就走现在的逻辑。这样多个tabbar就可以控制plusButton的是否展示问题。 你们看这样可以吗？@zengfxios @xiaoer @include11 @pengqun @qoakzmxncb

**Comment by xiaoer** [comment]
应该是可以的。折腾下试试。周末了我也折腾下！

**Comment by ChenYilong** [comment]
@xiaoer @zengfxios @include11 @pengqun @qoakzmxncb v1.17.3版本已经支持多tabbar嵌套，详情请看文档：

https://github.com/ChenYilong/CYLTabBarController#%E5%A4%9Atabbar%E5%B5%8C%E5%A5%97%E5%B9%B6%E6%8C%87%E5%AE%9Aplusbutton%E4%BD%8D%E7%BD%AE

**Comment by include11** [comment]
不知道怎么用

**Comment by ChenYilong** [comment]
@include11 上面有文档，就是TabBarController与plusButton的context一致的时候才会展示。

**Comment by ChenYilong** [comment]
这里给出了方案： https://github.com/ChenYilong/CYLTabBarController/issues/247

**Comment by ChenYilong** [comment]
多个tabbar，如果不指定context会出现如下问题：
![](http://ww2.sinaimg.cn/large/006tNc79ly1g5z25q5qgwg30960fz7wj.gif)
