### ISSUE TITLE
请支持 iOS 10

### ISSUE THREAD

**Issue by AnythingLucky** [ChenYilong/CYLTabBarController#101]
自定义的形状不规则加号按钮无法使用，程序崩溃

**Comment by ChenYilong** [comment]
Crash的问题，不需要更新版本，这里有一个更简单的方法来解决这个问题： 

见文档：

<https://github.com/ChenYilong/CYLTabBarController#第四步可选创建自定义的形状不规则加号按钮>


在注册加号按钮时，需要在 `-application:didFinishLaunchingWithOptions:` 方法里面调用 [YourClass registerPlusButton]

这里注意，不能在子类的 `+load` 方法中调用，比如像下面这样做，在 iOS10 系统上有 Crash 的风险：

 +(void)load {
    [super registerPlusButton];
}


同时 v1.6.1 为 iOS 10 适配版本：https://github.com/ChenYilong/CYLTabBarController/commit/e86302b80e76bc3102f813f0d3adfe0464f92ac0

**Comment by ChenYilong** [comment]
如果想使用 `+load` 方法来注册加号按钮，则需要更多的步骤，详情见这里的讨论 https://github.com/ChenYilong/CYLTabBarController/issues/83

**Comment by koalahl** [comment]
cocoaPods上没有1.6.5版本。

**Comment by ChenYilong** [comment]
## 查询 CocoaPods 源中的本库正确方法

  在终端中运行以下命令：

  ```shell
     pod search CYLTabBarController
  ```
 
   这里注意，这个命令搜索的是本机上的最新版本，并没有联网查询。如果运行以上命令，没有搜到或者搜不到最新版本，您可以运行以下命令，更新一下您本地的 CocoaPods 源列表。

  ```shell
     pod repo update
  ```
 
 详见文档：
https://github.com/ChenYilong/CYLTabBarController/commit/8fa419db42411dfc84027627c34a6e81e82ebe9e

**Comment by benzhemin** [comment]
旧版本对应[CYLPlusButtonSubclass registerSubclass]; 亲测已解决

**Comment by ChenYilong** [comment]
版本号给下，我记得旧版本有这个问题，新版本已经修复了
