### ISSUE TITLE
AppDelegate.m 改名为 AppDelegate.mm 文件后的问题

### ISSUE THREAD

**Issue by IAMJ** [ChenYilong/CYLTabBarController#103]
项目导入引用百度地图 SDK 后 ，将 AppDelegate.m 改名为 AppDelegate.mm ，这时 h 文件里的 `@import` 语句会报错

![001](https://cloud.githubusercontent.com/assets/2928760/19717251/3d9a4d88-9b92-11e6-99d1-808694f17d6a.png)

**Comment by ydhuang28** [comment]
问题好像是因为Objective-C++会自动禁用modules，导致`@import`语句不可以使用。我也用的百度地图API，希望作者如果可以把开头的`@import`改成`#import`，毕竟Xcode 5之后如果在可用modules的情况下`#import`会自动在编译器内转换为`@import`。

**Comment by ydhuang28** [comment]
虽然百度地图API有说明它使用了ObjC++进行静态库链接，但是好像不是必要的。我刚刚试了一下，起码加载最基本的地图是不需要把文件改成`.mm`（ObjC++）的。

**Comment by ChenYilong** [comment]
可以，稍等，我支持下。

**Comment by ChenYilong** [comment]
v1.6.2 版本已经兼容，请升级重试。

**Comment by IAMJ** [comment]
CYLTabBarController/CYLTabBarController/CYLTabBar.h

这个文件还是用 `@import`

**Comment by ChenYilong** [comment]
v1.6.4 版本已经兼容，请升级重试。
