### ISSUE TITLE
请问能不能拿到TabBarButton？

### ISSUE THREAD

**Issue by rakuyoMo** [ChenYilong/CYLTabBarController#104]
想拿到button做长按时事件，不知道作者大大的这个框架能不能直接拿到Button？

**Comment by ChenYilong** [comment]
除了PlusButton，其他的button长按事件暂时无法获取，这种需求，还不支持。如果有这种需求请告知，我提供的接口，我可以实现下。

**Comment by rakuyoMo** [comment]
有这种需求，目前的方案是长按button，然后做一些其他的事情，未来打算使用UIPreviewInteractionDelegate，所以需求恐怕还是要拿到button。不知作者大大能不能抽空实现一下，提供接口能拿到button。

**Comment by rakuyoMo** [comment]
您好我还想请问下，我该如何获取PlusButton的长按点击事件？

**Comment by rakuyoMo** [comment]
看到了您的更新，我想问下CYLPlusButton是如何实现长按事件的？我想可以效仿到其他的button上。

**Comment by rakuyoMo** [comment]
您好，我今天翻看了下您的代码，发现您也是用KVO修改的权限，之前调不到是因为您反KVO了。我让自己的TabBar类继承自您的CYLTabBar，重新KVO之后，修改tabBar为自己的tabbar，成功获取了button，实现了功能。

**Comment by ChenYilong** [comment]
能否发我一份代码，我看下你的实现，我看下能不能直接添加进这个项目，对外提供API。luohanchenyilong@163.com

**Comment by rakuyoMo** [comment]
已经发到您的邮箱，顺带还有一个图标居中显示的问题。

**Comment by treylin** [comment]
@ChenYilong 作者你好，请问获取 tabBar 上 button 的接口提供了吗？

**Comment by ChenYilong** [comment]
@treylin   v1.11.0已经添加点击事件的API，长按事件还未添加，详见[《文档》]( https://github.com/ChenYilong/CYLTabBarController#捕获-tabbar-点击事件 ) 。

**Comment by ChenYilong** [comment]
@treylin 另外请更新至v1.12.0，v1.11.0之前的版本可能包含私有API，审核时可能有被拒的风险。

**Comment by geekbandcainiao** [comment]
@ChenYilong 能否拿到双击事件

**Comment by ChenYilong** [comment]
可以，demo里演示了双击刷新。

**Comment by jianqingyu** [comment]
你好，你这个不是双击刷新，只是在本页面点击刷新 我需要双击返回，在本页单击刷新咋做呢
