### ISSUE TITLE
为什么push过去后只能按返回按钮才能到上一级界面,咋么设置向右滑动回到上一级界面

### ISSUE THREAD

**Issue by JKbai** [ChenYilong/CYLTabBarController#105]

**Comment by ChenYilong** [comment]
Demo中没有这个问题，你可以试一下。右滑是可以返回上界面的。

**Comment by ChenYilong** [comment]
我试了试Demo没发现这个问题，先关闭了，你如果还有疑问，可以再打开

**Comment by JKbai** [comment]
解决了，谢谢，是我自定义的导航控制器没有指定滑动的代理对象！


在2016年10月31日 16:15，微博@iOS程序犭袁 写道:

Demo中没有这个问题，你可以试一下。右滑是可以返回上界面的。
