### ISSUE TITLE
咨询下如何动态的去替换其中一个控制器

### ISSUE THREAD

**Issue by 931743010** [ChenYilong/CYLTabBarController#107]
如题： 求大神帮忙看看

**Comment by 931743010** [comment]
有人吗？ 求帮忙哈

**Comment by ChenYilong** [comment]
再详细描述下需求

**Comment by 931743010** [comment]
实现了；    UITabBarController *tabBarController = [self cyl_tabBarController] ?: [[UITabBarController alloc] init];
    CYLBaseNavigationController *nav=[tabBarController.viewControllers objectAtIndex:2];
        [nav setViewControllers:@[anno] animated:NO];
