### ISSUE TITLE
当ViewController设置的self.title和tabBarItemsAttributes中对应的title不一致的时排序不对

### ISSUE THREAD

**Issue by ChenYilong** [ChenYilong/CYLTabBarController#11]
有 [童鞋](http://weibo.com/tekuba?from=feed&loc=nickname) 发现了一个 bug：

 > 发现了一个bug，当ViewController设置的self.title和tabBarItemsAttributes中对应的title不一致的时候，会出现如图的错误，排序不对了。Debug的时候发现会多执行了自定义TabBar的layoutSubviews方法，UIView *childView in self.subviews这句话获得的内存都不一样了。

![Uploading 71e73aefjw1exht9ai8tzj20ho07saav.jpg…](http://ww3.sinaimg.cn/large/71e73aefjw1exht9ai8tzj20ho07saav.jpg)

我会相应地跟进。

**Comment by kingloveyy** [comment]
我也遇到这个问题了呢

**Comment by ChenYilong** [comment]
@kingloveyy  暂时的解决方案是，只设置一处，比如如果想在 VC 里设置，就没必要在 appdelegate 里设置了。

**Comment by UniverseKing** [comment]
这个问题有解决吗，两处title不一样就有问题哦

**Comment by kapop** [comment]
如题+1

**Comment by ChenYilong** [comment]
好的，我会看下该问题。也欢迎大家提pr

**Comment by maqihan** [comment]
楼主分享的这个自定义tabbar我一研究，在使用中我也发现了这个顺序错乱的问题，通过实验已经知道这个问题问题出在哪里并修复了这个问题，只在楼主自定义的tabbar的类中加入一个方法就可以了，想要的朋友加我1250307429，我也是第一次用这个东西，不清楚这样修改系统的tabbar对于审核有没有问题，应用正在审核中。希望没啥问题。。。

**Comment by ChenYilong** [comment]
@maqihan @kapop @UniverseKing @kingloveyy  

请遵循如下规则：

 ```Objective-C
 self.navigationItem.title = @"同城";    //✅sets navigation bar title.The right way to set the title of the navigation
    self.tabBarItem.title = @"同城23333";   //❌sets tab bar title. Even the `tabBarItem.title` changed, this will be ignored in  tabbar.
    //self.title = @"同城1";                //❌sets both of these. Do not do this‼️‼️ This may cause tabBar to be in disorder.
 ```
