### ISSUE TITLE
支持Gif图片显示么

### ISSUE THREAD

**Issue by jeffy7** [ChenYilong/CYLTabBarController#111]
## Base Info for this issue 

要是不支持Gif ，有什么思路？

**Comment by jeffy7** [comment]
我已经知道怎样做了

**Comment by ChenYilong** [comment]
能不能分享下你的做法？我看下能不能在这库的基础上直接提供API出去。能否发个你的做法的Demo给我？luohanchenyilong@163.com

**Comment by RocPengPeng** [comment]
有方案吗？
