### ISSUE TITLE
请问如果一打开APP如何实现例如我的tabbaritem显示红色小数字，而不是点击我的才显示小数字？

### ISSUE THREAD

**Issue by notePads** [ChenYilong/CYLTabBarController#113]
## Base Info for this issue 

 1. Version：v1.6.5
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
我有个思路：

 库中的 TabBar 实际是自定义的 CYLTabBar，可以在不触发 TabBarItem 的情况下直接修改 CYLTabBar 的badge。

**Comment by ChenYilong** [comment]
改天实现下，有两个项目可以借鉴下：

 1. https://github.com/DeveloperLx/LxTabBadgePoint
 2. https://github.com/Zzzard/HXRedDotTabBarItem

**Comment by ChenYilong** [comment]
@notePads v1.13.0已经可自定义View来展示 TabBarItem 角标，默认支持未读小红点。详情参考文档。一打开APP就显示红点，已经在Demo中演示。
