### ISSUE TITLE
点击PlusButton，不跳出新的界面，在原有界面的基础上添加一个高斯模糊背景；这个界面跳不出来ing

### ISSUE THREAD

**Issue by LittleLydia** [ChenYilong/CYLTabBarController#114]
## Base Info for this issue 

 1. Version：v1.7.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

给PlusButton添加点击事件，在现有界面个的view上添加一层模版，结果获取不到self.view；转而转向 CYLTabBarController *tabBarController = [self cyl_tabBarController];
viewController = tabBarController.selectedViewController;
这个方法，在viewController.view 上添加这个模版也没有效果

## 2. Please help me in this way.

请问一下是因为plusButton是一个单独的UIButton，而不是一个tabbarITem所以不能实现我所说的这样的效果吗？
我想实现的是点击plusButton然后实现类似微博发布的效果；比如这个案例http://www.2cto.com/kf/201509/440810.html

**Comment by ChenYilong** [comment]
这个可以实现。点击plusButton，点击事件你设置成添加高斯模糊的view到rootViewController就行了。

**Comment by LittleLydia** [comment]
添加高丝模糊的view可以通过这个方法获得吗？
CYLTabBarController *tabBarController = [self cyl_tabBarController];
viewController = tabBarController.selectedViewController;

**Comment by ChenYilong** [comment]
一般是通过uiwindow加，我这里有个类似的，你可以看看https://github.com/ChenYilong/CollectionViewClassifyMenu
