### ISSUE TITLE
在其他位置重新初始化 CYLTabbarController 会导致原控制器的 PlusButton 消失

### ISSUE THREAD

**Issue by chen570075003** [ChenYilong/CYLTabBarController#115]
你好，如题。再返回原有的 TabbarController 时怎么才能使 PlusButton 恢复

**Comment by ChenYilong** [comment]
有Demo吗？有Demo的话发我一份，luohanchenyilong@163.com。我看下基于现有接口能否完成该需求，不能完成的话，我可以支持下。

**Comment by ChenYilong** [comment]
我想问，为什么要在push到另外的控制器，后重新初始化一遍？但就你发我的Demo而言，毫无必要。不再次初始化就不会有问题。还是说，你仅仅是为了演示再次初始化的情景？能告知下重新初始化的需求场景吗？

**Comment by chen570075003** [comment]
这个需求之前是要再多级界面，截取到第一级的截图，并且是带 TabbarViewController 情况下，尝试初始化一个截取并没问题，不过返回原来的就使 PlusButton 消失

**Comment by ChenYilong** [comment]
截取截图，为什么要重新初始化。

**Comment by chen570075003** [comment]
当前NavigationViewController处于第三级，截取第一级的页面并显示出来

**Comment by gdfyj90** [comment]
这个可以事先截图吧，除非你首页的数据一直在变

**Comment by ChenYilong** [comment]
参考：https://github.com/ChenYilong/CYLTabBarController/issues/100

已经修复
