### ISSUE TITLE
iOS10之上的系统xcode空白打印

### ISSUE THREAD

**Issue by iOSCountry** [ChenYilong/CYLTabBarController#116]
1. Version：v1.7.0
 2. Language：Objective-C
 4. iOS System Version：iOS10.2
 5. Prototype（是否是真机）：YES

你好,宜龙哥.今天发现集成了CYLTabBarController之后,在iOS10之上的系统,在每次切换底部控制器的时候xcode会有一些空白的打印,在iOS10之下的系统,就没有这个问题.想请教下,这是什么原因

**Comment by ChenYilong** [comment]
没注意，可以把打印的内容贴下。我看下是不是我的库造成的。

**Comment by iOSCountry** [comment]
![image](https://cloud.githubusercontent.com/assets/17453419/21488489/61b5e420-cc1b-11e6-8960-e8faa11b72be.png)
就是这样的空白打印,每次切换item的时候就有这样的打印,但是在iOS9和iOS8上面就没有.

**Comment by iOSCountry** [comment]
@ChenYilong

**Comment by ChenYilong** [comment]
我测试了下，没发现什么打印。你看下你是不是在下面的代理方法中进行了什么操作导致的：

> - (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController {
