### ISSUE TITLE
怎么在push到二级视图时显示CYTabBar，现在只能从第三级视图POP到二级视图时才显示.

### ISSUE THREAD

**Issue by indenpendman** [ChenYilong/CYLTabBarController#117]
## Base Info for this issue 

 1. Version：v1.7.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
再详细描述下，没听懂。

**Comment by indenpendman** [comment]
用你的框架只有根视图才能显示底下tabBar,push 视图控制器后tabBar会消失. 我现在的需求是任意层级都可以显示或隐藏底下tabBar,请问大神怎么实现？

**Comment by ChenYilong** [comment]
默认是会显示的，Demo里的隐藏tabbar效果是手动设置的。

**Comment by indenpendman** [comment]
好的，已经看到实现了，谢谢大神。

**Comment by iOSCountry** [comment]
@ChenYilong 我问那个iOS10 控制台有空白打印的问题,你没有回答啊

**Comment by ChenYilong** [comment]
@iOSCountry 因为不知道为什么。
