### ISSUE TITLE
希望能支持新需求：左右滑动可以切换tabbarItem、可以填一个 tabbar上显示不带数字的小红点功能

### ISSUE THREAD

**Issue by gdfyj90** [ChenYilong/CYLTabBarController#118]
## Base Info for this issue 

 6. Issue Type：Enhancement（希望能支持一个新需求）

## 2. Please help me in this way.
能否支持滚动样式，左右滑动可以切换tabbarItem,类似于安卓版的微信那样。

**Comment by ChenYilong** [comment]
这个暂时还不支持，我调研下，看这个需求广泛不，要是应用的比较多的话，可以考虑实现下。

**Comment by gdfyj90** [comment]
之前有别的第三方实现过，但是当子页面也有scroll的话手势会被拦截，无法从该子控制器的页面滑动到其他子控制器。

**Comment by jcayumengxiang** [comment]
可以填一个 tabbar上显示不带数字的小红点功能吗  这个用的还是比较多的

**Comment by ChenYilong** [comment]
左右滑动可以切换tabbarItem 有两个开源库，你可以参考下：  
 1. https://github.com/DeveloperLx/LxTabBarController
 2. https://github.com/leichunfeng/WXTabBarController


 tabbar上显示不带数字的小红点功能：
 1. https://github.com/DeveloperLx/LxTabBadgePoint


参考：https://github.com/ChenYilong/CYLTabBarController/issues/54

**Comment by ChenYilong** [comment]
v1.13.0已经可自定义View来展示 TabBarItem 角标，默认支持未读小红点。详情参考文档。一打开APP就显示红点，已经在Demo中演示。

**Comment by ChenYilong** [comment]
左右滑动不打算支持。
