### ISSUE TITLE
希望能支持一个新需求

### ISSUE THREAD

**Issue by pc1849** [ChenYilong/CYLTabBarController#119]
希望作者大大能支持一下tabBarItem能直接传image，而不只是name。想要动态配置一下item的image，我目前是在设置过image之后直接用childViewController来改的。

**Comment by ChenYilong** [comment]
这个需求是刚需，下个版本实现下。

**Comment by ChenYilong** [comment]
v1.10.0新版已经发布，API没有变动，同时支持传入 `NSString` 和 `UIImage` 两种格式。

相关改动见：

https://github.com/ChenYilong/CYLTabBarController/commit/7b465cbd5891ad6c10fcf4de108d52c41d4e8c57
