### ISSUE TITLE
我们需求图片要网络获取，然后发现item的图片变的好大

### ISSUE THREAD

**Issue by Qinzhao** [ChenYilong/CYLTabBarController#120]
我们需求图片要网络获取，然后发现item的图片变的好大，是根据图片的尺寸来显示的，如果图片在images.xcassets文件夹中，item的图片会自动适应。你可以把你的图片放在文件目录里，会发现图片都变的好大  这个我改怎么做呢 请教

**Comment by ChenYilong** [comment]
给个Demo并把你的图片给我，我调适下luohanchenyilong@163.com

**Comment by ChenYilong** [comment]
目前对大尺寸的icon没有做特别处理，仅仅支持尺寸合适的icon。这个可以支持下，我试试看，找个合适的方案，支持下。

**Comment by Qinzhao** [comment]
我解决了  如果图片放在文件本地路径中，图片名称必须要带一个@2x。否则，会按照非retina屏显示，导致模糊变的很大。我打算把图片缓存下来，然后拼接一 个@2x 试试。谢谢!大神在百忙中回复。谢谢!!!

**Comment by ChenYilong** [comment]
ok

**Comment by ChenYilong** [comment]
这里有一个思路不错：http://www.jianshu.com/p/fb15ceca2126
