### ISSUE TITLE
在CYLTabBarItemTitle不设置的情况presentViewController会导致显示bug

### ISSUE THREAD

**Issue by bloodspasm** [ChenYilong/CYLTabBarController#122]
## Base Info for this issue 

 1. Version：v1.10.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 1. How to repeat the problem.

带CYLTabBarItemTitle正常显示
<img width="312" alt="2017-02-06 3 18 28" src="https://cloud.githubusercontent.com/assets/10420472/22637889/a0b09b32-ec7f-11e6-8ec8-f4e256244cb6.png">

去CYLTabBarItemTitle

 ```Objective-C

- (NSArray *)tabBarItemsAttributesForController {
    NSDictionary *firstTabBarItemsAttributes = @{
                                                 CYLTabBarItemImage : @"home_gray",
                                                 CYLTabBarItemSelectedImage : @"home",
                                                 };
    NSDictionary *secondTabBarItemsAttributes = @{
                                                  CYLTabBarItemImage : @"me_gray",
                                                  CYLTabBarItemSelectedImage : @"me",
                                                  };
   
    NSArray *tabBarItemsAttributes = @[
                                       firstTabBarItemsAttributes,
                                       secondTabBarItemsAttributes
                                       ];
    return tabBarItemsAttributes;
}

 ```

后显示

<img width="313" alt="2017-02-06 3 21 55" src="https://cloud.githubusercontent.com/assets/10420472/22637955/0e7eeefc-ec80-11e6-9036-e91e3d4ae64d.png">
但是presentViewController后回来显示(两边的icon向里缩进)
<img width="318" alt="2017-02-06 3 22 04" src="https://cloud.githubusercontent.com/assets/10420472/22637969/2bda234a-ec80-11e6-8e09-580d23c5ea64.png">

**Comment by ChenYilong** [comment]
收到，我看下。

**Comment by ChenYilong** [comment]
能不能发给Demo给我，luohanchenyilong@163.com

**Comment by bloodspasm** [comment]
@ChenYilong 我尝试的在Demo上复现但是没成功,我怀疑和App上使用的其他方法有冲突.我觉得我需要监听一下Frame
