### ISSUE TITLE
设置tabbar背景图片后    有问题

### ISSUE THREAD

**Issue by zb1006801184** [ChenYilong/CYLTabBarController#124]
![633f8931-0b68-4d31-9519-3eac91ee1a2f](https://cloud.githubusercontent.com/assets/22284069/23008632/dcdf8afe-f44b-11e6-9639-7a2c7d81ade4.png)
![31011e33-829f-4de3-810f-c4afdfa26536](https://cloud.githubusercontent.com/assets/22284069/23008633/dd5cdc02-f44b-11e6-9bcf-49bb4d2cfb44.png)
只有6 和6s  是正常的。其他机型都不能正常显示。

**Comment by ChenYilong** [comment]
确认下图片有没有问题。可以发个demo给我 luohanchenyilong@163.com

**Comment by ChenYilong** [comment]
收到你的demo了，背景图片，你需要自行拉伸，默认的图片填充方式，不能自动将凸起部分居中的。
