### ISSUE TITLE
使用cocoapods安装CYLTabBarController1.10.0出错

### ISSUE THREAD

**Issue by flypigrmvb** [ChenYilong/CYLTabBarController#125]
Installing CYLTabBarController 1.10.0 (was 1.8.0)

[!] Error installing CYLTabBarController
[!] /usr/bin/git clone https://github.com/ChenYilong/CYLTabBarController.git /var/folders/nk/bzrl93f52fg9znq4117fqb9c0000gn/T/d20170222-26540-no34nc --template= --single-branch --depth 1 --branch 1.10.0

Cloning into '/var/folders/nk/bzrl93f52fg9znq4117fqb9c0000gn/T/d20170222-26540-no34nc'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by ChenYilong** [comment]
推测是你本地错误，建议删除原有的库，重试。
