### ISSUE TITLE
非数字角标小红点能支持吗

### ISSUE THREAD

**Issue by DogTwoChen** [ChenYilong/CYLTabBarController#127]
## Base Info for this issue 

 1. Version：v1.10.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
可以，你可以参考下 https://github.com/ChenYilong/CYLTabBarController/issues/118

**Comment by ChenYilong** [comment]
v1.13.0已经可自定义View来展示 TabBarItem 角标，默认支持未读小红点。详情参考文档。一打开APP就显示红点，已经在Demo中演示。
