### ISSUE TITLE
点击tabBarItem如何让图片放大动画

### ISSUE THREAD

**Issue by fuchenxi** [ChenYilong/CYLTabBarController#128]
## Base Info for this issue 
我想点击tabBarItem的是让image 执行放大缩小动画, 该如何做?

**Comment by ChenYilong** [comment]
这个跟淘宝App最新版6.5.0上面一个效果？请详细描述下你的需求。

**Comment by ChenYilong** [comment]
Reference：https://github.com/ChenYilong/CYLTabBarController/issues/62

**Comment by fuchenxi** [comment]
对的, 就是这个效果, 不过是让image放大, title不变化, 有考虑加入这个功能吗?

**Comment by ChenYilong** [comment]
我在想是支持这一个动画，还是说增加一些通用动画，添加一些参数，可配置。

**Comment by fuchenxi** [comment]
我感觉增加一些通用动画应该就可以了

**Comment by fuchenxi** [comment]
- (void)layoutSubviews {
    [super layoutSubviews];

    for (UIControl *tabBarButton in self.subviews) {
          if ([tabBarButton isKindOfClass:NSClassFromString(@"UITabBarButton")]) {
               [tabBarButton addTarget:self action:@selector(tabBarButtonClick:)  forControlEvents:UIControlEventTouchUpInside];
        }
    }
}

- (void)tabBarButtonClick:(UIControl *)tabBarButton
{
    for (UIView *imageView in tabBarButton.subviews) {
        if ([imageView isKindOfClass:NSClassFromString(@"UITabBarSwappableImageView")]) {
            //需要实现的帧动画,这里根据需求自定义
            CAKeyframeAnimation *animation = [CAKeyframeAnimation animation];
            animation.keyPath = @"transform.scale";
            animation.values = @[@1.0,@1.3,@0.9,@1.15,@0.95,@1.02,@1.0];
            animation.duration = 1;
            animation.calculationMode = kCAAnimationCubic;
            //把动画添加上去就OK了
            [imageView.layer addAnimation:animation forKey:nil];
        }
    }
}


在CYLTabBar.m中实现上面的方法就行了

**Comment by hllGitHub** [comment]
http://www.jianshu.com/p/13fe42796153 参考这个看一下，加了动画的。

**Comment by ChenYilong** [comment]
@hllGitHub  @fuchenxi v1.11.0版本已经添加新的API来完成自定义动画，详情见文档： [《点击 TabBarButton 时添加动画》]( https://github.com/ChenYilong/CYLTabBarController#点击-tabbarbutton-时添加动画 ) .
