### ISSUE TITLE
Item的点击事件

### ISSUE THREAD

**Issue by wyt358489351** [ChenYilong/CYLTabBarController#131]
## Base Info for this issue 

不能获取到tabbarController的点击事件

 1. Version：v1.10.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

设置UISearchBarController的delegate后，不会实现didSelected方法，不能获取到item的点击事件
## 2. Please help me in this way.

开放一个方法可以获取点击事件

**Comment by ChenYilong** [comment]
> 设置UISearchBarController的delegate后？

写错了？

**Comment by ChenYilong** [comment]
先 `[self cyl_tabBarController].delegate = self;`

然后在代理方法里做判断：

``` Objective-C
#pragma mark - delegate

- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController*)viewController {
    NSUInteger selectedIndex = tabBarController.selectedIndex;

    return YES;
}
```

**Comment by wyt358489351** [comment]
协议是 UITabBarControllerDelegate 么？为什么我设置了之后，代理方法还是不执行呢 
 
------------------ Original ------------------
From: "微博@iOS程序犭袁"; 
Date: 2017年3月17日(星期五) 下午5:08
To: "ChenYilong/CYLTabBarController"; 
Cc: "wyt358489351"; "Author"; 
Subject: Re: [ChenYilong/CYLTabBarController] Item的点击事件 (#131)

 

先 [self cyl_tabBarController].delegate = self;
 
然后在代理方法里做判断：
 #pragma mark - delegate - (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController*)viewController {     NSUInteger selectedIndex = tabBarController.selectedIndex;     return YES; }

**Comment by ChenYilong** [comment]
对。请在本仓库的原生Demo里试试。另外排查下，你是不是重复设置了delegate。

**Comment by ChenYilong** [comment]
v1.11.0新添加了API来完成这个，详情可以看 [文档](https://github.com/ChenYilong/CYLTabBarController#捕获-tabbar-点击事件)
