### ISSUE TITLE
TabBar添加自己定义的视图，响应手势的问题

### ISSUE THREAD

**Issue by zhangrenfeng** [ChenYilong/CYLTabBarController#132]
我需要给TabBar添加自己的视图(不能通过您提供的plusButton方式), 同时该添加的子视图需要能响应自己的手势, 该子视图的frame可能会在TabBar的frame之外, 由于您重写了TabBar的hitTest:withEvent:方法, 在该方法中您只遍历了所有的UITabBarButton, 所以我自己添加的子视图不能响应手势, 不知道您是否考虑到用户可能还存在想自定义子视图的需求.

**Comment by ChenYilong** [comment]
v1.11.0 已经修复该问题，请更新重试。

**Comment by ChenYilong** [comment]
另外请更新至v1.12.0，v1.11.0之前的版本可能包含私有API，审核时可能有被拒的风险。
