### ISSUE TITLE
如何push一个UITabBarController?

### ISSUE THREAD

**Issue by fuchenxi** [ChenYilong/CYLTabBarController#135]
现在有个需求是跳转一个普通通德UITabBarController, 隐藏cyl_tabBar, 会出现问题, 而且系统的tabBarItem的image被绘制重叠的两份

**Comment by ChenYilong** [comment]
luohanchenyilong@163.com 发个Demo给我

**Comment by fuchenxi** [comment]
image被绘制两次这个问题现在没有复现, 跳转没有隐藏是我好像写错了
- (void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated {
 
    [super pushViewController:viewController animated:animated];
    if (self.viewControllers.count > 1) {
        
        self.hidesBottomBarWhenPushed = YES;
    }
}


====================================== 改为

- (void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated {
    
    if (self.viewControllers.count > 0) {
        
        viewController.hidesBottomBarWhenPushed = YES;
    }
    [super pushViewController:viewController animated:animated];
}
======================================

**Comment by ChenYilong** [comment]
如果没有问题，可以关闭issue
