### ISSUE TITLE
能默认选择Plus按钮吗？切换tabBarController.selectIndex plus按钮不是被选中状态

### ISSUE THREAD

**Issue by glary** [ChenYilong/CYLTabBarController#137]
如题

**Comment by ChenYilong** [comment]
贴下你怎么尝试更改plusButton状态的代码。

**Comment by glary** [comment]
CYLTabBarControllerConfig *tabBarControllerConfig = [[CYLTabBarControllerConfig alloc] init];
   tabBarControllerConfig.tabBarController.selectedIndex = 2;
    [self.window setRootViewController:tabBarControllerConfig.tabBarController];



//按钮的index
+ (NSUInteger)indexOfPlusButtonInTabBar {
    return 2;
}

**Comment by glary** [comment]
@ChenYilong  我上面那种方式是不是得手动改变button的状态。

**Comment by fanyuexiang** [comment]
我也遇到这个问题,怎么解决? 直接更改tabBarController.selectedIndex 为plusButton所在的index,控制器可以切换为plusChildViewController,但是plus按钮不会切换为选中状态,只有手动点击一次才可以
