### ISSUE TITLE
能否调整plusbutton两侧tabbarItem的位置？

### ISSUE THREAD

**Issue by haofanning** [ChenYilong/CYLTabBarController#138]
如题，如果能调整的话，求告知调整方法，谢谢！

**Comment by ChenYilong** [comment]
请仔细描述一下需求，我的理解是不是你想实现下面的需求：

你不想让PlusButton居中显示，想实现让plusButton处于比如最后一个的位置。

如果是该需求的话，你可以采用下面这个方法：




 ```Objective-C
+ (NSUInteger)indexOfPlusButtonInTabBar;
 ```

用来自定义加号按钮的位置， 文档请戳[这里](https://github.com/ChenYilong/CYLTabBarController#第四步可选创建自定义的形状不规则加号按钮) 。

**Comment by haofanning** [comment]
@ChenYilong 不是的，我想让plusButton居中显示，然后两边的tabbarItem靠两侧屏幕边缘移动一部分距离，这个可以做到吗？

**Comment by ChenYilong** [comment]
参考：https://github.com/ChenYilong/CYLTabBarController/issues/24
