### ISSUE TITLE
setUpTabBarCustomizeAttributes method for selectedTitleColor didn't work

### ISSUE THREAD

**Issue by litt1e-p** [ChenYilong/CYLTabBarController#14]
I did implemented setUpTabBarCustomizeAttributes method for custom NSForegroundColorAttributeName which whiteColor was set before the childViewControllers implementation. but it became the gray color eventually.that is weird.....?

**Comment by ChenYilong** [comment]
now i've fix this bug,please update CYLTabBarController with cocoaPods

**Comment by litt1e-p** [comment]
it work! that's great! thx quite a lot!
