### ISSUE TITLE
从深度>=3的页面cyl_popSelectTabBarChildViewControllerAtIndex: completion:时tabbar显示异常

### ISSUE THREAD

**Issue by anotherNight** [ChenYilong/CYLTabBarController#141]
## Base Info for this issue 

 1. Version：v1.10.0
 2. Language：Objective-C
 4. iOS System Version：iOS8\9
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 1. How to repeat the problem.

使用CYLTabBarController，当从深度>=3的页面cyl_popSelectTabBarChildViewControllerAtIndex: completion:到另一个tabbarController上的ViewControllerA1并调用pushVC到ViewControllerA2，返回ViewControllerA1时tabbar hidden，在ViewControllerA1上做一次pushVC再pop回时，tabbar show；

## 2. Please help me in this way.

fix bug
## 3. Here is a Demo. 
demo 发送到你的邮箱

![bug重现](http://7xt737.com1.z0.glb.clouddn.com/tabbarBug.gif)

**Comment by anotherNight** [comment]
检查后发现是tabbar的x坐标为-screenWidth，应该是动画机制有问题，跳转后没有把tabbar位置回复，话说tabbar是从左到右显示的，动画样式可以修改吗？动态hidden或从下到上是否更好呢？

**Comment by ChenYilong** [comment]
暂时没好的方法改过来，可以将最低端的window，改为白色，这样动画的黑边效果不会太明显。

**Comment by anotherNight** [comment]
不是黑边问题，是底部导航栏没有显示

**Comment by ChenYilong** [comment]
再次验证你的demo，发现问题无法复现，怀疑是iOS系统某一个版本的问题，Apple已经修复。

**Comment by ChenYilong** [comment]
v1.19.1版本修复了该函数引发的各种问题，欢迎更新重试。
