### ISSUE TITLE
tabBar 上面那条分割线怎么隐藏掉。

### ISSUE THREAD

**Issue by indenpendman** [ChenYilong/CYLTabBarController#144]
大神，你好，
1.CYLTabBar 顶部那条灰黑色的线如何隐藏。

2.    [[UITabBar appearance] setAlpha:0.9];
   用你的DEMO测试过，  透明度设置后 ，如果进入详情页后返回 就不起作用了。

**Comment by ChenYilong** [comment]
Demo里有演示，文档里也有说明。

**Comment by ChenYilong** [comment]
//去除 TabBar 自带的顶部阴影
    需要使用 -[CYLTabBarController hideTabBarShadowImageView] 

见README

并参考：https://github.com/ChenYilong/CYLTabBarController/issues/386
