### ISSUE TITLE
tabBarItems 加载网络图片问题

### ISSUE THREAD

**Issue by geng199200** [ChenYilong/CYLTabBarController#145]
请问一下加载网络图片，有没有一个设置图片大小的属性，比如说图片是48 * 48像素，在我们程序中size 应该是 24 * 24，但是不做任何处理的话，图片的宽高就直接按照像素来显示了。

**Comment by ChenYilong** [comment]
目前v1.13.0做不到，后续版本打算支持下。

**Comment by ZYCFan** [comment]
@ChenYilong 这个问题解决了吗？

**Comment by geng199200** [comment]
UIImage *image                      = [UIImage imageWithData:[NSData
dataWithContentsOfURL:[NSURL URLWithString:pathForEnvironment(item.imageUrl)]]
scale:2];我们现在是先下载到本地在给赋上去的。

2017-08-03 13:41 GMT+08:00 ZYCFan <notifications@github.com>:

**Comment by ZYCFan** [comment]
@geng199200 我也想过这么用，觉得有点麻烦。还是直接用UIButton+SDWebImage了。
