### ISSUE TITLE
私有API被拒

### ISSUE THREAD

**Issue by PrinceChen** [ChenYilong/CYLTabBarController#147]
如下，之前都没有问题的，今天被拒了。看看有什么方法可以解决。
Your app also uses or references the following non-public APIs:
UITabBarSwappableImageView, UITabBarButtonLabel, UITabBarButton
The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

**Comment by ChenYilong** [comment]
请更新至v1.11.0，已经解决该问题，详细的更新项目可以参看： https://github.com/ChenYilong/CYLTabBarController/commit/bcd63047e3838e2c4d190c2aed14993b2461b902 。

**Comment by ChenYilong** [comment]
@PrinceChen 请问更新后是否审核通过了？

**Comment by PrinceChen** [comment]
@ChenYilong 还在审，有结果了再来反馈！

**Comment by ChenYilong** [comment]
@PrinceChen 审核结果出来没，加我微信chenyilong1010 ，保持关注.

**Comment by niunaruto** [comment]
怎样了？今天要发包😓

**Comment by niunaruto** [comment]
@PrinceChen

**Comment by PrinceChen** [comment]
@ChenYilong @niunaruto 还没结果。上次被发了3.2(f)警告，不知道会被推出多久审核。

**Comment by ChenYilong** [comment]
@PrinceChen 这个警告是指的上面你贴的那段吗？

> Your app also uses or references the following non-public APIs:
UITabBarSwappableImageView, UITabBarButtonLabel, UITabBarButton
The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change

**Comment by PrinceChen** [comment]
@ChenYilong  不是，3.2(f)是其他附加的, 跟这边的API没关系

**Comment by PrinceChen** [comment]
@ChenYilong @niunaruto 审核结果出来了。还是被拒。
Guideline 2.5.1 - Performance - Software Requirements
  Your app uses or references the following non-public APIs:
  UITabBarButton, UITabBarButtonLabel, UITabBarSwappableImageView
  The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

**Comment by ChenYilong** [comment]
了解了，我今天就处理下

**Comment by ChenYilong** [comment]
你先在项目中全局搜索下，看能不能找到这些API

**Comment by PrinceChen** [comment]
@ChenYilong 提交前就收了，全局搜不到的

**Comment by ChenYilong** [comment]
因为Apple会使用程序静态分析代码中是否使用了私有API，V1.11.0版本使用字符串拆解、混淆技术来绕过苹果的静态分析工具。这种方法不总是有效，如果苹果公司采用了动态分析工具，那么这方法就不灵了。现在应该是遇到了这种情况。

**Comment by ChenYilong** [comment]
CYLTabBarController v1.12.0已经发布，解决私有API的问题，请更新。v1.11.0经验证并没有解决私有API被拒的问题。

@PrinceChen  @niunaruto

**Comment by ChenYilong** [comment]
如果有哪位朋友使用 CYLTabBarController v1.12.0审核通过了，也请在此留言，以证实该版本是可用的。

**Comment by niunaruto** [comment]
我用的v1.11.0早上了审核通过了，没有说私有API问题

**Comment by ChenYilong** [comment]
1.11.0解决的是Apple静态检查，1.12.1同时解决静态检查和动态检查的问题。

**Comment by PrinceChen** [comment]
虽然APP审核还是没过，但用v1.12.1该私有API问题审核结果未再提及。

**Comment by ChenYilong** [comment]
好的，祝你早日通过审核，通过审核的话，帮忙留言下哈！

**Comment by ws1227** [comment]
今天1.11.0被拒  我看不是说‘1.12.1同时解决静态检查和动态检查的问题’  但是貌似最高版本就是 1.11.0啊 @ChenYilong 
看图 http://art5.photozou.jp/pub/534/3167534/photo/249413094_624.v1500431179.png

**Comment by ChenYilong** [comment]
reference： [《iOS 私有 API 调用检测机制探讨
》]( http://davidlau.me/2017/08/23/ios-private-api-detection/?utm_medium=email&utm_source=gank.io ) .
