### ISSUE TITLE
TabBarItem只显示图标，图标未居中

### ISSUE THREAD

**Issue by XIAODINGPA** [ChenYilong/CYLTabBarController#148]
## Base Info for this issue 

 

 1. Version：v1.10.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
![tabbar](https://user-images.githubusercontent.com/28077025/26871183-e730f064-4ba4-11e7-8ec1-65b5274f6f83.png)

 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

  这样设置也无效
   tabBarController.imageInsets = UIEdgeInsetsMake(4.5, 0, -4.5, 0);
    tabBarCtroller.titlePositionAdjustment = UIOffsetMake(0, MAXFLOAT);
  真机和模拟器，图标都无法居中

## 4. Here is my Debug log

![image](https://user-images.githubusercontent.com/28077025/26871296-4d607e9a-4ba5-11e7-81ac-cc894716ccec.png)

**Comment by ChenYilong** [comment]
请更新到v1.11.0，我更新了API。

**Comment by ChenYilong** [comment]
@XIAODINGPA 后来更新没？解决问题没有？

**Comment by XIAODINGPA** [comment]
UI给的@2x图片是64x64的，我用你demo例子里面48x48的图是居中的，应该是图片图片尺寸的问题,换成48x48解决了。

**Comment by XIAODINGPA** [comment]
不好意思呀,UI给的2倍图是64x64的，我用你demo里面的48x48的图居中是没问题的,更换图片尺寸就解决了
