### ISSUE TITLE
横屏问题

### ISSUE THREAD

**Issue by lhwsygdtc900723** [ChenYilong/CYLTabBarController#149]
## Base Info for this issue 
在ipad air下  从竖屏切换到横屏 tabbar点击会失效 只有plusbutton点击还有效。在我的项目上横屏之后pushviewcontroller之后tabbar会消失，再切换到竖屏也不会出现。还有在pad上tabbar有时候会错位到屏幕中间

 1. Version：v1.25.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 1. How to repeat the problem.
横竖屏切换并pushVC

## 3. Here is a Demo. 
使用的是1.25版本的demo

**Comment by ChenYilong** [comment]
目前没有提供1.25.0版本，请使用最新版1.11.0版本重试。

https://github.com/ChenYilong/CYLTabBarController/releases

**Comment by lhwsygdtc900723** [comment]
谢谢
