### ISSUE TITLE
CYLTabBarController *cyl_tabBar_VC = [self cyl_tabBarController]; 返回的cyl_tabBar_VC为空

### ISSUE THREAD

**Issue by wherewemet** [ChenYilong/CYLTabBarController#150]
最近在用CYLTabBarViewController，遇到一个问题，当从一个viewController presnt进入tabBarViewController,发现CYLTabBarController *cyl_tabBar_VC = [self cyl_tabBarController]; 返回的cyl_tabBar_VC为空，求解决。。。

**Comment by ChenYilong** [comment]
请更新至v1.11.0，使用`[id cyl_setTabBarController:]`接口设置，之后` [self cyl_tabBarController]` 就会有值了。

**Comment by ChenYilong** [comment]
另外请更新至v1.12.0，v1.11.0之前的版本可能包含私有API，审核时可能有被拒的风险。

**Comment by ChenYilong** [comment]
@wherewemet 请问可以解决你的问题吗？

**Comment by wherewemet** [comment]
还是为空，，我想从登录页面present进入tabBar页面，，，然后点击plusButton获取CYLTabBarController *cyl_tabBar_VC = [self cyl_tabBarController];的cyl_tabBar_VC为空。。。是我[id cyl_setTabBarController:]用的不对吗？？？ @ChenYilong

**Comment by ChenYilong** [comment]
发个Demo给我，luohanchenyilong@163.com

**Comment by CancerJing** [comment]
你好，请问这个问题解决了吗？？

**Comment by CancerJing** [comment]
![2017-10-27 10 18 31](https://user-images.githubusercontent.com/19985793/32085196-454a5ae8-ba93-11e7-95d6-ceef2a38dd4f.png)
[(UIViewController *)self parentViewController]  会 等于 nil  然后 tabBarController  就又变成nil了

**Comment by ChenYilong** [comment]
参考：https://github.com/ChenYilong/CYLTabBarController/issues/218
