### ISSUE TITLE
能否动态改变所有tabbar,触发一定操作,从四个变成五个等数量的变化.控制器的内容也发生变化

### ISSUE THREAD

**Issue by Williamyzd** [ChenYilong/CYLTabBarController#151]
## Base Info for this issue 

 1. Version：v1.10.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

某个操作触发
## 2. Please help me in this way.

tabbarviewcontroller重置

**Comment by ChenYilong** [comment]
你说的是这种样式吧：

点击首页里的子品牌 | 跳转到另一个页面也是TabBar样式
-------------|-------------
 ![](https://ws4.sinaimg.cn/large/006tNbRwly1fgin0lx2qaj30jz0zkwio.jpg) | ![](https://ws3.sinaimg.cn/large/006tNbRwly1fgin11xpq1j30jz0zkdiz.jpg)

目前系统的控件是无法做到从TabBar样式跳转到TabBar样式的，我这个框架暂时也做不到。推荐你的思路是：A TabBar push 到 B  TabBar，B TabBar 应当完全自定义，不能使用系统 UITabBarController 来做。

**Comment by Williamyzd** [comment]
是的

**Comment by ChenYilong** [comment]
这里给出了方案https://github.com/ChenYilong/CYLTabBarController/issues/247
