### ISSUE TITLE
在ipad上能改变tabbar上图片与文字的布局么，改为一前一后，而不是上下布局

### ISSUE THREAD

**Issue by EasonTangCX** [ChenYilong/CYLTabBarController#153]
## Base Info for this issue 

 1. Version：v1.10.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
已经修复，参考这里的说明：https://github.com/ChenYilong/CYLTabBarController/issues/236
