### ISSUE TITLE
这个能在Storyboard中使用吗？如果能用，怎么用？

### ISSUE THREAD

**Issue by luomuwen** [ChenYilong/CYLTabBarController#16]
比我在Storyboard中定义了一个TabBarController，并且指定为程序的入口？那么怎么才能用上这个CYLTabBarController呢？

**Comment by DeveloperPans** [comment]
同一楼的问题。今天折腾了一整天。请问，当Storyboard作为主入口时，如何才能使用？

**Comment by ChenYilong** [comment]
暂时还不支持。有计划支持下，也欢迎提pr

**Comment by luomuwen** [comment]
@ChenYilong  作者加油。

**Comment by ChenYilong** [comment]
reference： [《从头开始swift2.1 仿搜材通项目（三） 主流框架Tabbed的搭建》]( http://www.jianshu.com/p/c5bc2eae0f55?nomobile=yes )

**Comment by ChenYilong** [comment]
可以使用， [这里](https://github.com/ChenYilong/CYLDeallocBlockExecutor)
