### ISSUE TITLE
二次初始化CYLTabBarController，不走代理方法。

### ISSUE THREAD

**Issue by DogTwoChen** [ChenYilong/CYLTabBarController#161]
## Base Info for this issue 
1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 1. How to repeat the problem.
登陆后退出，再次登录需要初始化 tabbarcontroller ，第二次初始化tabbarcontroller时，设置了delegate，但不走代理方法（动画）。

**Comment by polichan** [comment]
请问如何解决，同样的问题？

**Comment by ChenYilong** [comment]
还没看，有人分析出原因了吗？
delegate重新设置了吗？

**Comment by ChenYilong** [comment]
二次初始化，delegate需要重新设置。

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/362

**Comment by ChenYilong** [comment]
更新 demo 修复二次初始化，不走代理方法不走代理方法的问题，

详情见： 
 - https://github.com/ChenYilong/CYLTabBarController/commit/91f6de1af523f096d6ccc2b8a5accbc04b31f850

 - https://github.com/ChenYilong/CYLTabBarController/issues/161

**Comment by ChenYilong** [comment]
部分子类化的情况, 比如以下情况, 需要改成 super.delegate = self; 

![image](https://user-images.githubusercontent.com/2911921/134796434-a1778cd3-f135-4936-932a-7e5753f7efd8.png)
