### ISSUE TITLE
用Pod导入1.13.1，运行示例Swift代码，中间Plus按钮只有第一次生效，后续点击无效。

### ISSUE THREAD

**Issue by yanlusu** [ChenYilong/CYLTabBarController#162]
## Base Info for this issue 

用Pod导入1.13.1，运行示例Swift代码，中间Plus按钮只有第一次生效，后续点击无效。

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：NO
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Bug

## 1. How to repeat the problem.

将示例代码的Swift版本中的Podfile修改成如下：
pod "CYLTabBarController", "~>1.13.1"
再运行Pod update
打开xcworkspace文件
运行，目标设备选择Plus7
点击中间加号，可以打开红色背景ViewController
点击其他BarItem，OK
再点击中间加号，无法打开红色背景ViewController
以后均失效。
## 2. Please help me in this way.
代码bug
我用了不同的版本做了对比，发现1.10.0版本是没有问题的，在1.11.0版本引入了该问题。
文件CYLTabBarController.m的viewDidLoad方法中，1.11.0去掉了下面一行：
```objc
    self.delegate = self;
```
在1.11.0和最新版本1.13.1中，增加这一句代码后，问题解决。
## 3. Here is a Demo. 

自带示例

## 4. Here is my Debug log

无。

**Comment by xinluqi001** [comment]
我也遇到了同样的问题, 我的是OC, 使用的是模拟器 iOS 11 Xcode9  iPhone 8
plus按钮只响应第一次点击, 之后的点击都不响应
