### ISSUE TITLE
运行时增加或者减少tab数量

### ISSUE THREAD

**Issue by sunever999** [ChenYilong/CYLTabBarController#164]
你好，我的app要根据用户是否有权限，来动态显示4个，或者5个tab，应用内用户登出，再重新登录的时候要动态修改tab数量（从4到5，或者从5到4），系统原生的TabBar是支持这个功能的，请问目前CYLTabBarController是否支持这个功能？

**Comment by zhaoxiaoga** [comment]
需要同时设置  setTabBarItemsAttributes  和 setViewControllers: animated: 方法
`            [tabbarViewControllers removeObjectAtIndex:1];
             [tabBarItemsAttributes removeObjectAtIndex:1];
             [self.customTabBarController setTabBarItemsAttributes:tabBarItemsAttributes];
            [self.customTabBarController setViewControllers:tabbarViewControllers animated:YES];`
这样不会崩溃

**Comment by wocalage** [comment]
> 需要同时设置 setTabBarItemsAttributes 和 setViewControllers: animated: 方法
> ` [tabbarViewControllers removeObjectAtIndex:1]; [tabBarItemsAttributes removeObjectAtIndex:1]; [self.customTabBarController setTabBarItemsAttributes:tabBarItemsAttributes]; [self.customTabBarController setViewControllers:tabbarViewControllers animated:YES];`
> 这样不会崩溃

这边试了一下通过下面这种方式是可以增加，但是发现tab没有图片跟文字
[self.customTabBarController setViewControllers:tabbarViewControllers animated:YES]

下面这种方式会添加失败，这是什么原因？
[self.customTabBarController setViewControllers:tabbarViewControllers]

**Comment by wocalage** [comment]
> 你好，我的app要根据用户是否有权限，来动态显示4个，或者5个tab，应用内用户登出，再重新登录的时候要动态修改tab数量（从4到5，或者从5到4），系统原生的TabBar是支持这个功能的，请问目前CYLTabBarController是否支持这个功能？

请问下，你这个实现了吗？有没有遇到tab不显示图片跟文字的情况？

**Comment by ChenYilong** [comment]
这里给出了方案：https://github.com/ChenYilong/CYLTabBarController/issues/247
