### ISSUE TITLE
关于plusButton跳转问题。

### ISSUE THREAD

**Issue by Ryan-Wong-iOS** [ChenYilong/CYLTabBarController#165]
## Base Info for this issue 

我没有重写CYLTabBarController，直接使用它，然后自定义一个plusButton，按钮出来了。我在button里面实现了indexOfPlusButtonInTabBar 和 plusChildViewController 的代理。可是点击没有效果。实际上我是不是漏了什么步骤？

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：NO
 6. Issue Type：Q-A

**Comment by chiyaoyao** [comment]
下载测试demo https://github.com/ChenYilong/CYLTabBarController/blob/master/Example/Classes/View/CYLPlusButtonSubclass.m#L87  只将这里修改成
    [button addTarget:button action:@selector(plusChildViewController) forControlEvents:UIControlEventTouchUpInside];
https://github.com/ChenYilong/CYLTabBarController/blob/master/Example/Classes/Module/Home/CYLHomeViewController.m#L56
注释    [self cyl_popSelectTabBarChildViewControllerAtIndex:4];
会跳转至发现界面，但是发现按钮不会改变状态，其他几个按钮可以

**Comment by ChenYilong** [comment]
贴一下plusButton的代码，初始化tabbar的代码

**Comment by ChenYilong** [comment]
另外也参考下：https://github.com/ChenYilong/CYLTabBarController/issues/228
