### ISSUE TITLE
self.tabBarController.hidesBottomBarWhenPushed = YES失效

### ISSUE THREAD

**Issue by XCmaxwell** [ChenYilong/CYLTabBarController#166]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.
直接在您的demo中实验的，默认进入CYLHomeViewController 点击跳转--->NewUIViewController，设置self.tabBarController.hidesBottomBarWhenPushed = YES 无效

**Comment by ChenYilong** [comment]
demo里就有CYLHomeViewController 点击跳转--->NewUIViewControlle的逻辑，可以隐藏。
