### ISSUE TITLE
tabbar 图片问题

### ISSUE THREAD

**Issue by shangqianForFun** [ChenYilong/CYLTabBarController#167]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 4. Here is my Debug log

![image](https://user-images.githubusercontent.com/18900603/29395039-cd32a986-8340-11e7-83ce-cf6731283d68.png)

为什么图片总是会顶着上边而不是居中

**Comment by bacy** [comment]
居中的api好像不能用了

**Comment by ChenYilong** [comment]
不显示title的情况下，我才会强制要求居中，非则就是系统逻辑。
