### ISSUE TITLE
多个tabbarviewcontroller 问题

### ISSUE THREAD

**Issue by Engandend** [ChenYilong/CYLTabBarController#168]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：NO
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.
打开APP的时候 显示有凸起来的按钮样式的tabbar（自定义按钮在中间，共5个item）
用户有2中角色，在登录的时候去判断如果是普通用户，继续显示有凸起来的样式，
如果不是普通用户，这个时候需要显示的是 系统样式（共3个item）

在进行不是普通用户登录的时候，重新创建了一个CYLtabbarviewcontroller，用window.rootviewcontroller去切换，这个时候，crash在这个位置：
```
if (CYLTabbarItemsCount % 2 != 0) {
            [NSException raise:@"CYLTabBarController" format:@"If the count of CYLTabbarControllers is odd,you must realizse `+indexOfPlusButtonInTabBar` in your custom plusButton class.【Chinese】如果CYLTabbarControllers的个数是奇数，你必须在你自定义的plusButton中实现`+indexOfPlusButtonInTabBar`，来指定plusButton的位置"];
        }
```

**Comment by ChenYilong** [comment]
请更新到1.17.4版本，已经修复。
