### ISSUE TITLE
tabbar获取上一个选中item

### ISSUE THREAD

**Issue by SimleCp** [ChenYilong/CYLTabBarController#169]
项目需求是点击某个item的时候, 如果没有权限访问, 就返回到上一个选中的item, 但是不知道怎么获取上一个选中的item.

 1. Version：v1.10.0
 2. Language：Objective-C
 4. iOS System Version：iOS9.3.5
 5. Prototype（是否是真机）：YES

**Comment by ChenYilong** [comment]
两个需求，

第一个：

判断是否有权限，这个判断在哪里做都行 viewDidLoad 也行，或者下面这个代理方法也行


 ```Objective-C
//UITabBarController Delegate Mothed
- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController;

 ```


第二个：
跳转可以用下面的方法：

 ```Objective-C
//#import "UIViewController+CYLTabBarControllerExtention.h"
- (UIViewController *)cyl_popSelectTabBarChildViewControllerAtIndex:(NSUInteger)index;
 ```

**Comment by SimleCp** [comment]
因为当时很多权限控制的逻辑代码都写在了目标控制器的view的生命周期函数里面了. 所以必须得跳到目标控制器去, 第一个函数只能满足是否跳转 ,这样就需要获取到上一个角标.   现在的做法是用第一个函数获取上一个角标, 存在runtime写的分类里, 动态添加属性保存起来.  然后需要是用的时候直接设置selectedIndex就好了.  UITabBarController Delegate用的比较少, 所以没注意这些好用的函数. ^-^, 不知道我现在的方式是否是最优的?

**Comment by ChenYilong** [comment]
这个方法可以。

**Comment by SimleCp** [comment]
好的.  谢谢.   ^-^
