### ISSUE TITLE
storyboard的Demo里面，在didFinishlaunchOption方法里面RegisterPlusbutton添加不上中间按钮。

### ISSUE THREAD

**Issue by lifengios** [ChenYilong/CYLTabBarController#170]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
这个时候注册太晚了，注册早点，在appdelegate里注册。

**Comment by kcchen2012** [comment]
didFinishlaunchOption已经就是在appdelegate里呢

**Comment by ChenYilong** [comment]
如何在storyboard中使用，讨论见： https://github.com/ChenYilong/CYLTabBarController/issues/226
