### ISSUE TITLE
怎么能隐藏底部的tabBar，比如我添加了plusButton，点击进入扫描页，此时希望tabBar是隐藏的。左上角返回，希望返回进入扫描前的tabBar.selectedIndex

### ISSUE THREAD

**Issue by owenWang123** [ChenYilong/CYLTabBarController#171]

**Comment by ChenYilong** [comment]
de mo里的做法就可以，直接push进去，仿照demo里的做法隐藏tabbar。

**Comment by owenWang123** [comment]
谢谢，明白了。我之前把它们当成平级的了。现在这样做OK了。

- (void)clickPublish {
 
    CYLTabBarController *tabBarController = [self cyl_tabBarController];
 
    UIViewController *viewController = tabBarController.selectedViewController;
 
    
 
    ScanViewController *plusChildViewController = [[ScanViewController alloc] init];
 
    [viewController cyl_pushViewController:plusChildViewController animated:YES];
 
}





------------------ 原始邮件 ------------------
发件人: "微博@iOS程序犭袁";<notifications@github.com>;
发送时间: 2017年8月29日(星期二) 中午1:57
收件人: "ChenYilong/CYLTabBarController"<CYLTabBarController@noreply.github.com>; 
抄送: "昊天"<839695819@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [ChenYilong/CYLTabBarController] 怎么能隐藏底部的tabBar，比如我添加了plusButton，点击进入扫描页，此时希望tabBar是隐藏的。左上角返回，希望返回进入扫描前的tabBar.selectedIndex (#171)




de mo里的做法就可以，直接push进去，仿照demo里的做法隐藏tabbar。
