### ISSUE TITLE
这种效果CYLTabBarController能实现？

### ISSUE THREAD

**Issue by KangYJie** [ChenYilong/CYLTabBarController#172]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

<img width="334" alt="2017-08-30 3 06 31" src="https://user-images.githubusercontent.com/19221483/29866188-3e766038-8daa-11e7-81be-886e9336dc34.png">

<img width="379" alt="2017-08-30 5 39 13" src="https://user-images.githubusercontent.com/19221483/29866217-54427f14-8daa-11e7-86ca-e921a1bfdb64.png">

**Comment by ChenYilong** [comment]
可以的。文档里有介绍。
