### ISSUE TITLE
iPhoneX适配问题

### ISSUE THREAD

**Issue by emilyZhouwm** [ChenYilong/CYLTabBarController#175]
## iPhoneX变长了,模拟器中测试,不设置tabBarHeight会一直漂在底部,pop时落下去了,切换tab时又漂上来了.

正常的是这样的：
![Uploading F3D3124E-A156-487F-BD35-807AAC222F10.png…]()

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
说明：https://github.com/ChenYilong/CYLTabBarController/issues/173

**Comment by ChenYilong** [comment]
```Swift
if (@available(iOS 11.0, *)) {
   _tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
}
 ```

**Comment by KBvsMJ** [comment]
@ChenYilong @emilyZhouwm   我是这样修复的:
在CYLTabBar.m文件中重写setframe方法:具体如下
```
- (void)setFrame:(CGRect)frame{
    if (self.superview &&CGRectGetMaxY(self.superview.bounds) !=CGRectGetMaxY(frame)) {
        frame.origin.y =CGRectGetHeight(self.superview.bounds) -CGRectGetHeight(frame);
    }
    [super setFrame:frame];
    
}
```

**Comment by ChenYilong** [comment]
v1.16.1版本已经修复
