### ISSUE TITLE
怎么单独设置TabBar上面的小红点和数字

### ISSUE THREAD

**Issue by ghost** [ChenYilong/CYLTabBarController#177]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
最新版有设置的接口，无法满足需求吗

**Comment by ChenYilong** [comment]
可以升级到v1.16.1版本查看API

**Comment by ChenYilong** [comment]
参照： https://github.com/ChenYilong/CYLTabBarController/issues/206

**Comment by ChenYilong** [comment]
v1.19.1 版本对小红点内部实现做了较大改动，可传入自定义字符串和小红点。
