### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by wunshine** [ChenYilong/CYLTabBarController#179]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：No
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

自己实现button继承CYLPlusButton,实现addTarget方法,点击按钮崩溃

## 4. Here is my Debug log

2017-09-17 15:51:08.523402+0800 xy-out[46964:3170559] +[XYButton displayAlarmController:]: unrecognized selector sent to class 0x10d32ccb0
2017-09-17 15:51:08.533330+0800 xy-out[46964:3170559] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[XYButton displayAlarmController:]: unrecognized selector sent to class 0x10d32ccb0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010dfe326b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001124e8f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e063864 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010df66218 ___forwarding___ + 1432
	4   CoreFoundation                      0x000000010df65bf8 _CF_forwarding_prep_0 + 120
	5   UIKit                               0x000000010ffc6631 -[UIApplication sendAction:to:from:forEvent:] + 83
	6   UIKit                               0x000000011013b000 -[UIControl sendAction:to:forEvent:] + 67
	7   UIKit                               0x000000011013b31d -[UIControl _sendActionsForEvents:withEvent:] + 450
	8   UIKit                               0x000000011013a24a -[UIControl touchesEnded:withEvent:] + 618
	9   UIKit                               0x0000000110039bf1 -[UIWindow _sendTouchesForEvent:] + 2807
	10  UIKit                               0x000000011003b314 -[UIWindow sendEvent:] + 4124
	11  UIKit                               0x000000010ffe12da -[UIApplication sendEvent:] + 352
	12  UIKit                               0x00000001108eff18 __dispatchPreprocessedEventFromEventQueue + 2809
	13  UIKit                               0x00000001108f2a7f __handleEventQueueInternal + 5957
	14  CoreFoundation                      0x000000010df86351 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	15  CoreFoundation                      0x000000010e025d71 __CFRunLoopDoSource0 + 81
	16  CoreFoundation                      0x000000010df6acb9 __CFRunLoopDoSources0 + 185
	17  CoreFoundation                      0x000000010df6a29f __CFRunLoopRun + 1279
	18  CoreFoundation                      0x000000010df69b29 CFRunLoopRunSpecific + 409
	19  GraphicsServices                    0x0000000115bd09c6 GSEventRunModal + 62
	20  UIKit                               0x000000010ffc49a4 UIApplicationMain + 159
	21  xy-out                              0x000000010d10f5bf main + 111
	22  libdyld.dylib                       0x000000011361f621 start + 1
)

**Comment by ChenYilong** [comment]
非本库问题
