### ISSUE TITLE
动态修改tabaritem 的图片吗，替换为用户头像

### ISSUE THREAD

**Issue by EasonGaoDevelop** [ChenYilong/CYLTabBarController#18]
用户登录之后，可以动态修改tabaritem 的图片吗，替换为用户头像

**Comment by ChenYilong** [comment]
请问修改的是哪一个tabaritem？是加号按钮？还是？

**Comment by BuildFaild** [comment]
我这边项目需求要实现加号按钮和其余的tabbarItem图片都可以动态化切换 ，请问我怎么获取到加号的的按钮进行处理？

**Comment by ChenYilong** [comment]
@BuildFaild 可以，参考下这里：https://github.com/ChenYilong/CYLTabBarController/issues/73

**Comment by yangzheng006** [comment]
其余的事怎么切换的？

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/303

**Comment by ChenYilong** [comment]
这里有方案说明：https://github.com/ChenYilong/CYLTabBarController/issues/247
