### ISSUE TITLE
tabBar不显示了

### ISSUE THREAD

**Issue by Brain920227** [ChenYilong/CYLTabBarController#180]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
1.14.1已经修复，https://github.com/ChenYilong/CYLTabBarController/issues/181
