### ISSUE TITLE
更新到1.14.0之后不显示tabbar了

### ISSUE THREAD

**Issue by jokerping** [ChenYilong/CYLTabBarController#181]
## Base Info for this issue 

更新到1.14.0之后不显示tabbar了

 1. Version：1.14.0
 2. Language：Objective-C
 4. iOS System Version：iOS9.1
 5. Prototype（是否是真机）：NO
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
的确如此，1.14.1已经修复。

**Comment by luo71418578** [comment]
iphoneX demo中
 
    if (self.viewControllers.count > 0) {
        if (!IS_IPHONE_X) {
            viewController.hidesBottomBarWhenPushed = YES;
        }
    }

若是把if (!IS_IPHONE_X)条件去掉，tabbar隐藏时候会向上跳一下，不知道为何

**Comment by ChenYilong** [comment]
目前看，怀疑是系统bug，不过也不确定，目前还没有好的方法，先避免用红点 showPoint 相关的api吧。
