### ISSUE TITLE
有选中背景，但中间的圆形Tab不需要选中背景,怎么做到?

### ISSUE THREAD

**Issue by PrinceChen** [ChenYilong/CYLTabBarController#182]
如题。如有需要，我贴UI设计的图来阐述。

**Comment by ChenYilong** [comment]
可以做到，tabbar与plusbutton设置是分离的，文档里有介绍

**Comment by PrinceChen** [comment]
下面链接是UI设计的效果，和目前做到的效果。帮忙看下
链接: https://pan.baidu.com/s/1dFMrv6D 密码: aaex
中间的Tabbar功能跟其他的Tabbar一样只是切换显示，不需要弹窗。它的选中效果由按钮自身实现。
现在关键就是去掉中间plusbutton，由tabbar整体设置的选中效果。
设置选中效果调用的是CYLTabBarControllerConfig中customizeTabBarSelectionIndicatorImage函数。

**Comment by ChenYilong** [comment]
selectedImage设置成和normalimage一样的就行了。
