### ISSUE TITLE
iphoneX隐藏tabbar时候会向上跳动

### ISSUE THREAD

**Issue by luo71418578** [ChenYilong/CYLTabBarController#183]
if (self.viewControllers.count > 0) {
        if (!IS_IPHONE_X) {
            viewController.hidesBottomBarWhenPushed = YES;
        }
    }

若是把   if (!IS_IPHONE_X) 条件去掉，iphoneX中tabbar会向上跳动，返回时也有问题，不知道怎么回事

**Comment by ChenYilong** [comment]
先避免在iPhone X上用showPoint相关的API吧。稍后会修复下。

**Comment by ChenYilong** [comment]
也就是红点相关的API

**Comment by luo71418578** [comment]
好的，先试试，不过我试了单单系统的tabbar，隐藏也是有这个情况

**Comment by ChenYilong** [comment]
嗯疑似系统bug了，再等等下个版本

**Comment by ChenYilong** [comment]
请更新至v1.16.1
