### ISSUE TITLE
Tabbar 按钮 点击切换后 TabBar诡异的消失了

### ISSUE THREAD

**Issue by ijeffery3** [ChenYilong/CYLTabBarController#184]
## Base Info for this issue 

下载的是v1.14.1 但是每个类的第五行显示的是v1.14.0

APP启动TabBar是出现的，但是点击切换的时候 TabBar就消失了。请提供个思考方向，哪里出现了问题

 1. Version：v1.14.0
 2. Language：Objective-C
 4. iOS System Version：iOS 10
 5. Prototype（是否是真机）：NO
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/241
