### ISSUE TITLE
问一下怎么调整图片与title的距离

### ISSUE THREAD

**Issue by sjxt** [ChenYilong/CYLTabBarController#186]

**Comment by ChenYilong** [comment]
文档已经给出方法

**Comment by sjxt** [comment]
tabBarController.imageInsets = UIEdgeInsetsMake(5, 5, 5, 5);
 tabBarController.titlePositionAdjustment = UIOffsetMake(-5, MAXFLOAT);

这个吗

**Comment by ChenYilong** [comment]
嗯

**Comment by sjxt** [comment]
但是设置了没有效果呀

**Comment by ChenYilong** [comment]
init方法的初始化方法里传入才会生效，demo里已经给出了调整间距的演示。

**Comment by sjxt** [comment]
好的 ，谢谢了
