### ISSUE TITLE
iPhone X iOS11 push过程中tabbar隐藏会上移

### ISSUE THREAD

**Issue by notePads** [ChenYilong/CYLTabBarController#187]
使用iPhone X iOS11 模拟器 测试发现push到B界面的时候，
    if (self.viewControllers.count > 0) {
        viewController.hidesBottomBarWhenPushed = YES;
    }
这时tabBar会隐藏，但是push过程中注意看到TabBar会上移一段距离。
版本：1.14.1

**Comment by loveuqian** [comment]
是的。同发现

**Comment by ChaoGuoGuo** [comment]
需要在viewDidLayoutSubviews方法中重写tabbar的frame，
 self.tabBar.frame = ({
        CGRect frame = self.tabBar.frame;
        CGFloat tabBarHeight = self.tabBarHeight > 0 ? self.tabBarHeight : (CYL_IS_IPHONE_X ? 83 : 49);
        frame.size.height = tabBarHeight;
        frame.origin.y = [UIScreen mainScreen].bounds.size.height - tabBarHeight;
        frame;
    });

**Comment by ChenYilong** [comment]
v1.16.1已经修复

**Comment by WCMYCML** [comment]
🇨🇳 开发者们好啊
