### ISSUE TITLE
ios 11 真机中  item 切换  变成四个,请求支援~~~

### ISSUE THREAD

**Issue by Rookie-liu** [ChenYilong/CYLTabBarController#188]
## Base Info for this issue 

![wechatimg3250](https://user-images.githubusercontent.com/12107673/31214617-8f663bda-a9de-11e7-824d-fc551d0c6099.jpg)

> 如上图所示 , 在第一个和第二个点击切换后 , 在点中间自定义的, 然后退出 .就变成如图所示 . 经过测试在ios11 真机上回出现此问题 , 在ios10.3--6s 上不会复现此问题  ios9.3 -- 5s上也不会复现此问题. 不明白问题在哪里, 请求支援~~~~  急急急.

- 引入库方式 - pod
- CYLPlusButtonSubclass  以及CYLTabBarControllerConfig  复制Demo 修改的.
- ios11 - 7P 中毕现
- 自定义按钮弹出方式 Model

## 操作步骤
- 运行程序 第一二个item 进行切换
- 点击中间自定义按钮退出
- 效果如上图

## 关键代码截图

> appdelegate中的
![wx20171005-151133](https://user-images.githubusercontent.com/12107673/31214805-7eda2e6a-a9df-11e7-8d8f-adae0a7a54ff.png)

> 两个数组

![image11](http://oqcnceap1.bkt.clouddn.com/WX20171005-115057.png)

![image22](http://oqcnceap1.bkt.clouddn.com/WX20171005-115042.png)

> 自定义按钮弹出方式
![image333](http://oqcnceap1.bkt.clouddn.com/WX20171005-115111.png)

## 版本信息
 1. Version：v1.14.0
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
请跟新到1.17.4以上版本，已经适配iPhone X重试下。
