### ISSUE TITLE
怎样禁止横屏存在，明明APP是禁止横屏的，结果进去的时候tabbar 图标不适配，感觉是tabbar图标横屏存在，最后两个图标看不见，而且前面空格很长。

### ISSUE THREAD

**Issue by Zhangyunjiang123** [ChenYilong/CYLTabBarController#190]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
禁止横屏操作很多，现在demo也演示了如何禁止横屏，可以看下appdelegate里的演示。
