### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by pickView** [ChenYilong/CYLTabBarController#192]
## Base Info for this issue 

[[CYLTabBarController alloc] init]

 1. Version：v1.14.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.
appdelegate 加 [[CYLTabBarController alloc] init] crash

## 4. Here is my Debug log
数组越界
断点定位在 CYLTabBar.m  86行

**Comment by ChenYilong** [comment]
crash
log打下。

**Comment by ChenYilong** [comment]
推测是初始化方法不正确，请参照文档与demo的做法。
