### ISSUE TITLE
小红点设置函数存在错误

### ISSUE THREAD

**Issue by 823906214** [ChenYilong/CYLTabBarController#194]
1.14.0

类 UIControl+CYLTabBarControllerExtention.m
`- (void)cyl_setTabBadgePointView:(UIView *)tabBadgePointView {
    
    /*UIView *tempView = objc_getAssociatedObject(self, @selector(cyl_tabBadgePointView));
    if (tempView) {
        [tempView removeFromSuperview];
    }*/

    if (tabBadgePointView.superview) {
        [tabBadgePointView removeFromSuperview];
    }
    
    tabBadgePointView.hidden = YES;
    objc_setAssociatedObject(self, @selector(cyl_tabBadgePointView), tabBadgePointView, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}`

注释部分为个人修改部分。
这边逻辑上存在问题，如果需要传过来的tabBadgePointView不是同一个视图，那这里会导致重复添加小红点。

**Comment by ChenYilong** [comment]
我优化下。
