### ISSUE TITLE
提点小建议：易用性的问题

### ISSUE THREAD

**Issue by goodcyg** [ChenYilong/CYLTabBarController#195]
在配置CYLTabBarControllerConfig的里写带复杂了。例如你demo 默认创建一个加号和4个按钮，我想把去掉+号，保留任意3个按钮，需要 (NSArray *)viewControllers和(NSArray *)tabBarItemsAttributesForController注释掉相对应的一个，但是demo就报索引越界了，你可以自己试试。这部分最好做进一步的合并封装，我只需要传入相应的模型，也就是我关心东东，然后就自动创建了，对我不太关心的地方，最好是封装起来，要不我自定义起来，需要这改，哪改改，不好用哦？在易用性上需要进一步的封装抽取？

**Comment by fanyuexiang** [comment]
....干脆让作者替你写得了...你注释掉demo里的一些东西,plusButton还没去掉呢,你看demo和readme了么,就不看看怎么设置plus button? 摊手~

**Comment by goodcyg** [comment]
@fanyuexiang 
我看了，就不能提点建议吗？你明白我在说啥吗？

**Comment by fanyuexiang** [comment]
@goodcyg  我确实不明白你在讲什么，我只知道作者上周还有回复其他issue，然鹅你这个是11月2号的。ok，毕竟是别人的地方，咱们代码小白还是多学习学习吧，说这些都没用，过年好

**Comment by ChenYilong** [comment]
加号按钮是独立的逻辑，动一行代码就可以了：注释registerPlus方法，或者调removePlus方法。

不会影响VC相关的逻辑。
