### ISSUE TITLE
在您demo上设置tabbar背景图问题

### ISSUE THREAD

**Issue by TML007** [ChenYilong/CYLTabBarController#196]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 4. Here is my Debug log

![snip20171106_9](https://user-images.githubusercontent.com/19261542/32428541-29e55818-c301-11e7-8b2b-105594557b76.png)

打开你demo里的这句话UITabBar *tabBarAppearance = [UITabBar appearance];
     [tabBarAppearance setBackgroundImage:[UIImage imageNamed:@"tab_bar"]];  运行，就变成上图形式

**Comment by menghany** [comment]
同样的问题~

**Comment by ChenYilong** [comment]
图片不行，换个图片

**Comment by sanlunaifen** [comment]
一样，而且用的就是你demo里面的图片

**Comment by sanlunaifen** [comment]
在CYLTabBar.m文件- (void)layoutSubviews方法里面做出以下修改即可隐藏那条线，代码如下
NSArray *subviews = self.subviews;
    for (UIView *subview in subviews) {
        if ([subviews isKindOfClass:NSClassFromString(@"@_UIBarBackground")]) {
            NSArray<__kindof UIView*> *bgSubviews = subview.subviews;
            if (bgSubviews.count > 1) {
                UIView *destView = bgSubviews[1];
                if (CGRectGetHeight(destView.bounds) < 1.0 ) {
                    destView.hidden = YES;
                    //destView这条线的高是0.5,此问题应该是iOS10以上才有，图层背景变了多了个_UIBarBackground，此判断只是为了避免隐藏错其他东西，直接隐藏bgSubviews[1]应该也OK的
//                                                        --此修改由墨夜提供
                }
            }
             break;
        }
    }

**Comment by sanlunaifen** [comment]
另外背景图如果是要居中凸起，则需要判断屏幕宽度，三张图，320，375，414，因为这种图片不好拉伸，也可动态生成，core graphics可以画一张image出来，如有其它方法麻烦说下，蟹蟹

**Comment by sanlunaifen** [comment]
对对对 我又来了 关于背景图中间凸起那个 可以把image绘制一下就行了 代码如下 
- (UIImage *) scaleImage:(UIImage *)image toScale:(float)scaleSize {
    
    UIGraphicsBeginImageContext(CGSizeMake([UIScreen mainScreen].bounds.size.width * scaleSize, image.size.height * scaleSize));
    
    [image drawInRect:CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width * scaleSize, image.size.height * scaleSize)];
    
    UIImage *scaledImage = UIGraphicsGetImageFromCurrentImageContext();
    
    UIGraphicsEndImageContext();
    
    return scaledImage;
}

**Comment by ChenYilong** [comment]
嗯，我看下

**Comment by ChenYilong** [comment]
@sanlunaifen 上面你列的方法怎么用的？


 ```Objective-C
- (UIImage *) scaleImage:(UIImage *)image toScale:(float)scaleSize {
    
    UIGraphicsBeginImageContext(CGSizeMake([UIScreen mainScreen].bounds.size.width * scaleSize, image.size.height * scaleSize));
    
    [image drawInRect:CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width * scaleSize, image.size.height * scaleSize)];
    
    UIImage *scaledImage = UIGraphicsGetImageFromCurrentImageContext();
    
    UIGraphicsEndImageContext();
    
    return scaledImage;
}
 ```

**Comment by ChenYilong** [comment]
@sanlunaifen @TML007 1.17.0以及以上的版本，增加了 API：可以用于隐藏该分割线。

使用 `-[CYLTabBarController hideTabBadgeBackgroundSeparator]` 见 AppDelegate 类中的演示

**Comment by sanlunaifen** [comment]
@ChenYilong 在设置背景图片里面，在填充图片之前先把图片转成绘制的形式，并不是根据设备做判断，因为你直接放图片可能会存在拉伸问题，但是你要是自己绘制一张和图片一样的图片就没事了
     UITabBar *tabBarAppearance = [UITabBar appearance];
     UIImage *image = [self scaleImage:[UIImage imageNamed:@"tab_bar"] toScale:1.0];
     [tabBarAppearance setBackgroundImage:image];

**Comment by ChenYilong** [comment]
@sanlunaifen 多谢， Demo 已经更新到你的做法 见 https://github.com/ChenYilong/CYLTabBarController/commit/c56415ad57523e67797d78d065c339920536b855

**Comment by sanlunaifen** [comment]
@ChenYilong 不客气，也感谢大神的开源

**Comment by kiss7xin** [comment]
iOS11找不到UIBarBackground这个图层，要想隐藏顶部的线，需要隐藏barStyle
self.tabBar.barStyle = UIBarStyleBlack;
