### ISSUE TITLE
在Tabbar里面，Navgationbar push页面时bar会出现闪烁

### ISSUE THREAD

**Issue by Jasee7** [ChenYilong/CYLTabBarController#197]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype ：YES
 6. Issue Type：Bug

## 1. How to repeat the problem.

页面结果是rootViewController是tabbar controller，其中每一个分别是NavigationController。正常使用hidesBottomBarWhenPushed 交互是正常的。假如Page1，page1 present了一个页面，再dismiss，之后每一次push sub vc时候就会出现navigationbar在进入页面时候闪烁。

## 2. Please help me in this way.

看能否协助定位一下问题，修复改现象。

如果不隐藏bottombar，把这个去掉。就全部都正常。navigationbar不会闪烁

**Comment by KBvsMJ** [comment]
@Jasee7  我这是这样尝试修复的:
在CYLTabBar.m文件中重写setframe方法:具体如下
```
- (void)setFrame:(CGRect)frame{
    if (self.superview &&CGRectGetMaxY(self.superview.bounds) !=CGRectGetMaxY(frame)) {
        frame.origin.y =CGRectGetHeight(self.superview.bounds) -CGRectGetHeight(frame);
    }
    [super setFrame:frame];
    
}
```

**Comment by coderGui** [comment]
@Jasee7 
I also encountered such a problem.There is no solutionThe problem in the system of the UITabBarController also have this problem, is not find a solution.Do you have a good solution to help

我也遇到这样的问题。
目前还没有解决
这个问题在系统的UITabBarController 也会存在这样的问题，目前还未找到解决办法。请问你有好的解决办法帮助下吗

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/207

**Comment by ChenYilong** [comment]
fixed in v1.15.0
