### ISSUE TITLE
你好，请问能实现  tabbaritem 纯文字，选中之后带下划线，那种样式吗？

### ISSUE THREAD

**Issue by buoge** [ChenYilong/CYLTabBarController#2]
你好，请问能实现  tabbaritem 纯文字，选中之后带下划线，那种样式吗？tabbar 选中，划线动画移动到相应位置。

是需要在layout subview 方法中自定义吗？

**Comment by ChenYilong** [comment]
这种样式不支持，因为用的是系统自带的tabbar实现的，所以实现动画的话，是不太可能的。你的这种需求只能自定义tabbar了，先把tabbar隐藏掉，然后自己创建一个view放在屏幕底部。

**Comment by buoge** [comment]
感谢，回答，我目前是按您说的这种思路，自定义view 实现的，不知道还有没有更好的实现方案，所以来请教， 再次感谢！
