### ISSUE TITLE
iPad下，只有三个tabbarItem不支持等分排列？

### ISSUE THREAD

**Issue by ynot16** [ChenYilong/CYLTabBarController#200]
![test](https://user-images.githubusercontent.com/10579296/32882014-f6e12362-caed-11e7-9b4a-a25790f47941.png)
如上图，iPad下，item并不是均等分布，左右是有margin的，导致item与item之间的selectionIndicatorImage出现小部分重叠，而在iPhone上是均等分布的，不出现以上问题。
能否实现下图效果？
![test2](https://user-images.githubusercontent.com/10579296/32882036-029129f0-caee-11e7-95dc-33c6d233044d.png)

**Comment by ChenYilong** [comment]
现在的版本就是支持等分排列的，请更新重试。
