### ISSUE TITLE
默认 创建CYLTabBarController 是在APPdelegate. 中 ，但我想让CYLTabBarController 在另一个界面 创建的时候，CYLTabBarController 的代理就不执行了

### ISSUE THREAD

**Issue by fantengteng** [ChenYilong/CYLTabBarController#201]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：NO
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

1 . 设置   self.window.rootViewController = Root;
 self.window = [[UIWindow alloc]initWithFrame:[UIScreen mainScreen].bounds];
    RootC *Root = [[RootC alloc]init];
    self.window.rootViewController = Root;
    [self.window makeKeyAndVisible];

2 在 RootC 中 创建  CYLTabBarController  创建方法如下
  PZ_TabBarControllerConfig *tabBarControllerConfig = [[PZ_TabBarControllerConfig alloc] init];
    CYLTabBarController *tabBarController = tabBarControllerConfig.tabBarController;
    tabBarController.delegate = self;
    AppDelegate* appDelagete = (AppDelegate *)[UIApplication sharedApplication].delegate;
    appDelagete.window.rootViewController = tabBarController;

3 这样创建 delegate 方法 就不执行了 
- (void)tabBarController:(UITabBarController *)tabBarController didSelectControl:(UIControl *)control {

}

## 2. Please help me in this way.

我想让 在其他根试图创建的时候 代理 也可以执行

**Comment by NOMBER2011** [comment]
你好，你的这个问题我也遇到了，你现在解决了没？帮我解决下

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/362

**Comment by ChenYilong** [comment]
目前demo就是你的这种方式，可以正常执行，请更新重试。

**Comment by ChenYilong** [comment]
我在最近的demo中，尝试了，这种方式是可以的。

结构如你所言：AppDelegate--RootVC-> VC1 --> TabBarVC:


 ```Objective-C
@implementation MainTabBarController

- (instancetype)init {
    if (!(self = [super init])) {
        return nil;
    }
    /**
     * 以下两行代码目的在于手动设置让TabBarItem只显示图标，不显示文字，并让图标垂直居中。
     * 等效于在 `-tabBarItemsAttributesForController` 方法中不传 `CYLTabBarItemTitle` 字段。
     * 更推荐后一种做法。
     */
    UIEdgeInsets imageInsets = UIEdgeInsetsZero;//UIEdgeInsetsMake(4.5, 0, -4.5, 0);
    UIOffset titlePositionAdjustment = UIOffsetMake(0, -3.5);
    CYLTabBarController *tabBarController = [CYLTabBarController tabBarControllerWithViewControllers:self.viewControllers
                                                                               tabBarItemsAttributes:self.tabBarItemsAttributesForController
                                                                                         imageInsets:imageInsets
                                                                             titlePositionAdjustment:titlePositionAdjustment
                                                                                             context:nil
                                             ];
    [self customizeTabBarAppearance:tabBarController];
    self.navigationController.navigationBar.hidden = YES;
    tabBarController.delegate = self;
    return (self = (MainTabBarController *)tabBarController);
}
 ```

**Comment by deanli08** [comment]
@ChenYilong 我发现如果在demo里面把MainTabBarController.h 这行方法updateTabBarCustomizationWhenTabBarItemWidthDidUpdate注释掉，就不会走代理 。初始化后直接走dealloc了这里面是持有了self（MainTabBarController）
//我这样写直接不走代理。
AppDelegate
`@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    self.window.backgroundColor = [UIColor whiteColor];
    [self.window makeKeyAndVisible];
    [self.window setRootViewController: [[LZTTabBarController alloc] init]];

    return YES;
}
`
`#import "CYLTabBarController.h"
@interface LZTTabBarController : CYLTabBarController
@end
@implementation LZTTabBarController
-(void)dealloc{
    NSLog(@"直接走 dealloc");
}
- (instancetype)init {
    if (!(self = [super init])) {
        return nil;
    }
    /* 以下两行代码目的在于手动设置让TabBarItem只显示图标，不显示文字，并让图标垂直居中。
    * 等效于在 `-tabBarItemsAttributesForController` 方法中不传 `CYLTabBarItemTitle` 字段。
    * 更推荐后一种做法。
    */
    UIEdgeInsets imageInsets = UIEdgeInsetsZero;//UIEdgeInsetsMake(4.5, 0, -4.5, 0);
    UIOffset titlePositionAdjustment = UIOffsetMake(0, -2.);
    CYLTabBarController *tabBarController = [CYLTabBarController tabBarControllerWithViewControllers:self.viewControllers tabBarItemsAttributes:self.tabBarItemsAttributesForController imageInsets:imageInsets titlePositionAdjustment:titlePositionAdjustment ];
    self.navigationController.navigationBar.hidden = YES;
    // 选中状态下的文字属性
    NSMutableDictionary *selectedAttrs = [NSMutableDictionary dictionary];
    selectedAttrs[NSForegroundColorAttributeName] = RGBA(125, 126, 251, 1);
    // 设置文字属性
    UITabBarItem *tabBar = [UITabBarItem appearance];
    [tabBar setTitleTextAttributes:selectedAttrs forState:UIControlStateSelected];
    tabBarController.delegate = self;
    return (self = (LZTTabBarController *)tabBarController);
}
//delegate不走
- (void)tabBarController:(UITabBarController *)tabBarController didSelectControl:(UIControl *)control{

}
`

**Comment by ChenYilong** [comment]
我看看

**Comment by ChenYilong** [comment]
更新 demo 修复二次初始化，不走代理方法不走代理方法的问题，

详情见： 
 - https://github.com/ChenYilong/CYLTabBarController/commit/91f6de1af523f096d6ccc2b8a5accbc04b31f850

 - https://github.com/ChenYilong/CYLTabBarController/issues/161
