### ISSUE TITLE
iphoneX ：怎么让tabbar 与横条所在背景色相同

### ISSUE THREAD

**Issue by koky397848081** [ChenYilong/CYLTabBarController#204]
## Base Info for this issue 

tab下面横条所在部分设置背景色好像有层半透明遮罩，怎么让tabbar背景色 与横条所在背景色相同

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
横条颜色，系统控制的。无法保持一致。
