### ISSUE TITLE
‘A’ presentViewController ‘B’ , ‘B’ dissmiss的completion的回掉里push ‘C’,tabBar的图片和字体混乱

### ISSUE THREAD

**Issue by UknowHui** [ChenYilong/CYLTabBarController#205]
## Base Info for this issue 

 1. Version：v1.14.0
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：no
 6. Issue Type：Bug
## 1. How to repeat the problem.

iphone x 

‘A’ presentViewController ‘B’ ,
 ‘B’ dissmiss的completion的回掉里push ‘C’,
tabBar的图片和字体混乱

**Comment by UknowHui** [comment]
@ChenYilong

**Comment by coderGui** [comment]
@UknowHui    I also encountered such a problem.There is no solutionThe problem in the system of the UITabBarController also have this problem, is not find a solution.Do you have a good solution to help

我也遇到这样的问题。
目前还没有解决
这个问题在系统的UITabBarController 也会存在这样的问题，目前还未找到解决办法。请问你有好的解决办法帮助下吗

**Comment by coderGui** [comment]
@UknowHui   我已经找到解决办法。  通过下面的方式完美解决了我的问题。
https://stackoverflow.com/questions/46214740/ios-11-iphone-x-simulator-uitabbar-icons-and-titles-being-rendered-on-top-coveri
http://www.jianshu.com/p/7b36dacf5744

**Comment by ChenYilong** [comment]
升级至v1.16.1

**Comment by UknowHui** [comment]
@coderGui thank you

**Comment by UknowHui** [comment]
@ChenYilong OK
