### ISSUE TITLE
设置TabBar文字颜色不起作用

### ISSUE THREAD

**Issue by zhangjianjun056** [ChenYilong/CYLTabBarController#208]
你好，请问为何我用代码如下：
// 设置tabBarItem 的选中和不选中文字属性
        // 普通状态下的文字属性
        let normalAttrs = [NSAttributedStringKey(rawValue: "NSForegroundColorAttributeName"):UIColor.black]
        // 选中状态下的文字属性
        let selectedAttrs = [NSAttributedStringKey(rawValue: "NSForegroundColorAttributeName"):UIColor.white]
        // 设置文字属性
        let tabBar = UITabBarItem.appearance()
        tabBar.setTitleTextAttributes(normalAttrs, for: .normal)
        tabBar.setTitleTextAttributes(selectedAttrs, for: .selected)
为何设置了之后，TabBar的颜色还是没有变化，请大神帮忙看一下吧，谢谢！

**Comment by ChenYilong** [comment]
这个需要支持下，现在确实是不支持设置颜色。

**Comment by ChenYilong** [comment]
demo中已经演示了如何设置颜色，可以参考demo里的做法。
