### ISSUE TITLE
PlusButton全局生效？

### ISSUE THREAD

**Issue by Steven-Yung** [ChenYilong/CYLTabBarController#209]
## Base Info for this issue 

当在`AppDelegate`注册了PlusButton后，所有使用到TabBarController的地方都加上了PlusButton？

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

当在`TabBarController`里`Push`另一个`TabBarController`的时候就出现这种问题了

## 2. Please help me in this way.

首页我使用TabBarController，有5个item分别对应4个`UINavigationController`和一个`PlusButton`，需求是`PlusButton`只在最外层有`PlusButton`,当其中一个`UINavigationController`对应的`ViewController` `Push`一个`TabBarController`后，在这个内层的`TabBarController`只显示正常的`Item`就好了，但是实际情况是在内层`TabBarController`也有一个`PlusButton`

**Comment by lifengios** [comment]
同问，而且我的push一个tabController之后，pop回首页那个 plusBtn 不见了。。

**Comment by ChenYilong** [comment]
接口里有设置context的地方

**Comment by ChenYilong** [comment]
目前上述的逻辑已经修复了，可以多个CYLTabBarController并存了。不存在该问题了，内部采用context进行区分。
