### ISSUE TITLE
pod search "CYLTabBarController" Not Found

### ISSUE THREAD

**Issue by tangkunyin** [ChenYilong/CYLTabBarController#21]
执行：pod search "CYLTabBarController" ，结果说这个库找不到。执行pod update --verbose，还是卡着不动。已用VPN翻墙，google速度正常，rubygems官网访问正常。不知道这个为啥不行呢？？

**Comment by ChenYilong** [comment]
```Objective-C
pod search "CYLTabBarController"
 ```


是在本地搜索CYLTabBarController



 ```Objective-C
pod update --verbose --no-repo-update

 ```

 是在禁止升级本地CocoaPods的spec仓库，

所以要尝试去升级本地的CocoaPods的spec仓库才行。

**Comment by tangkunyin** [comment]
嗯，最终换成官方的镜像并翻墙解决了。
