### ISSUE TITLE
plusButton 点击相应区域异常

### ISSUE THREAD

**Issue by TinySungo** [ChenYilong/CYLTabBarController#210]
## Base Info for this issue 

 1. Version：v1.14.0
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 1. How to repeat the problem.

实现两个代理

+ (UIViewController *)plusChildViewController {
    ImageSelectViewController *plusChildViewController = [[ImageSelectViewController alloc] init];
    
    UIViewController *nav = [[UINavigationController alloc] initWithRootViewController:plusChildViewController];
    plusChildViewController.title = @"添加日记";
    
    return nav;
}

+ (NSUInteger)indexOfPlusButtonInTabBar {
    return 2;
}

## 2. Please help me in this way.

//RootViewController 中添加 tabBarController
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    [CYLPlusButtonClass registerPlusButton];
    CYLTabBarControllerConfig *tabBarControllerConfig = [[CYLTabBarControllerConfig alloc] init];
    CYLTabBarController *tabBarController = tabBarControllerConfig.tabBarController;
    tabBarController.delegate = self;
    [self addChildViewController:tabBarController];
    [self.view addSubview:tabBarController.view];
}

#pragma mark - CYLTabBarControllerDelegate

- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController {
    
    [[self cyl_tabBarController] updateSelectionStatusIfNeededForTabBarController:tabBarController shouldSelectViewController:viewController];
}

## 4. Here is my Debug log

// 点击plusButton 无法跳转 viewController，反而点击按钮下方空白区域可跳转（plusButton没有写title，所以是空白区域）

**Comment by ChenYilong** [comment]
请升级到v1.16.1版本

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/228
