### ISSUE TITLE
iPhone打电话,或者发热点有设备连接时,tabBar会下移

### ISSUE THREAD

**Issue by coderchou** [ChenYilong/CYLTabBarController#211]
## Base Info for this issue 

 1. Version：v1.16.0
 2. Language：Objective-C
 4. iOS System Version：iOS10.3.1
 5. Prototype（是否是真机）：YES
 6. Issue Type：Enhancement

## 1. How to repeat the problem.

iPhone打电话,或者发热点有设备连接时,tabBar会下移,双击home键,发现整个tabBarController的view都向下移动20pt
## 2. Please help me in this way.

iPhone打电话,或者发热点有设备连接时,希望tabBar不会发生下移,谢谢大神

**Comment by coderchou** [comment]
![1](https://user-images.githubusercontent.com/24978714/33714111-bfa863dc-db88-11e7-988f-2a597712775a.png)

**Comment by coderchou** [comment]
![2](https://user-images.githubusercontent.com/24978714/33714142-e5d88dd4-db88-11e7-97f4-4ef7bca6767a.png)

**Comment by coderchou** [comment]
当拨打电话时,状态栏的高度会增加20pt，tabBarController的view的的y坐标会由0变为20，相应的tabBarController的view的的高度会减少20。所以此时tarBar的y坐标应该减少20，但是经过打印,发现tarBar的y坐标并没有发生变化，导致tabBar的底部没有和tabBarController的view的底部重合,发生了下移。我的解决方法是在 **CYLTabBarController** 这个类的 **viewWillLayoutSubviews**方法中做处理，修改tabBar的y坐标值：

`- (void)viewWillLayoutSubviews {
    if (!(self.tabBarHeight > 0)) {
        return;
    }
    self.tabBar.frame = ({
        CGRect frame = self.tabBar.frame;
        CGFloat tabBarHeight = self.tabBarHeight;
        frame.size.height = tabBarHeight;
        frame.origin.y = [UIScreen mainScreen].bounds.size.height - tabBarHeight;
        frame;
    });
    
    //修改tabBar的y坐标值
    CGFloat tabBarH = self.tabBar.frame.size.height;
    CGRect oldFrame = self.tabBar.frame;
    oldFrame.origin.y = self.view.frame.size.height - tabBarH;
    self.tabBar.frame = oldFrame;

    NSLog(@"修改后的tabBar的frame:%@",NSStringFromCGRect(self.tabBar.frame));
    NSLog(@"修改后的tabBarController的frame:%@",NSStringFromCGRect(self.view.frame));
}`

**Comment by ChenYilong** [comment]
问题已经确认，下个版本修复。

**Comment by ChenYilong** [comment]
fixed，请升级到v1.17.0或者以上版本。
