### ISSUE TITLE
在App运行期间,希望加入PlusButton可以随时显示和隐藏的功能

### ISSUE THREAD

**Issue by include11** [ChenYilong/CYLTabBarController#212]
应用场景如下：
1.未登录的情况下，不需要PlusButton按钮
2.已登录的情况下，需要显示PlusButton按钮
3.已登录的情况下注销，相当于未登录，这时候需要隐藏PlusButton按钮

**Comment by ChenYilong** [comment]
这个功能后序会支持，已经有排期计划，

**Comment by ChenYilong** [comment]
支持动态更新 | 可动态删除PlusButton ，可以动态更新样式 </p> ![enter image description here](http://i63.tinypic.com/208ba7a.jpg)

**Comment by wyk111wyk** [comment]
有范例代码么？

**Comment by ChenYilong** [comment]
这里提供了方案：https://github.com/ChenYilong/CYLTabBarController/issues/247
