### ISSUE TITLE
iPhoneSE上点击tabbar图片上下拉伸变形

### ISSUE THREAD

**Issue by PilotLee** [ChenYilong/CYLTabBarController#213]
## Base Info for this issue 

iPhoneSE上图片拉伸 点击越来越长。。。

 1. Version：v1.14.0
 2. Language：Objective-C
 4. iOS System Version：iOS10.2.1
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

用如下初始化方法 就会有问题 当然只是在手里的一个iphoneSE 有这样问题  其他机型和模拟器目前还未发现
    RootTabBarController *rootTabBar = [[RootTabBarController alloc]initWithViewControllers:[RootTabBarController ViewControllers] tabBarItemsAttributes:[RootTabBarController customizeTabBar] imageInsets:UIEdgeInsetsMake(-6.5, 0, -4.5, 0) titlePositionAdjustment:UIOffsetMake(0, -3.5)];
    return rootTabBar;

用如下的方法 就不会有问题
    RootTabBarController *rootTabBar = [[RootTabBarController alloc]initWithViewControllers:[RootTabBarController ViewControllers] tabBarItemsAttributes:[RootTabBarController customizeTabBar] ];
    return rootTabBar;

图片 2x3x 名字均一样 一个44x44  一个66x66

## 3. Here is a Demo. 

demo 就是按照安装步骤正常的  只是在单独的这个机型上 这个设置图片和文字内边距的方法下出了问题

## 4. Here is my Debug log

啥都没有

**Comment by ChenYilong** [comment]
缺少@1x图片，请添加该类型图片即可，4s机型可以复现。

**Comment by wangxiusen** [comment]
我也遇到了这个问题 我加了@1x图片也没有得到解决？

**Comment by PilotLee** [comment]
tabbaritem inset 左右 和上下都设置对称就可以了发自我的iPhone------------------ 原始邮件 ------------------发件人: wangxiusen  <notifications@github.com>发送时间: 2018年3月6日 18:16收件人: ChenYilong/CYLTabBarController <CYLTabBarController@noreply.github.com>抄送: Lee <15651095004@163.com>, Author <author@noreply.github.com>主题: 回复：[ChenYilong/CYLTabBarController] iPhoneSE上点击tabbar图片上下拉伸变形 (#213)我也遇到了这个问题 我加了@1x图片也没有得到解决？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ChenYilong/CYLTabBarController","title":"ChenYilong/CYLTabBarController","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ChenYilong/CYLTabBarController"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wangxiusen in #213: 我也遇到了这个问题 我加了@1x图片也没有得到解决？"}],"action":{"name":"View Issue","url":"https://github.com/ChenYilong/CYLTabBarController/issues/213#issuecomment-370732930"}}}

**Comment by ChenYilong** [comment]
#50

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/383
