### ISSUE TITLE
你好,掉这个cyl_popSelectTabBarChildViewControllerAtIndex方法切换tabbar的时候,发现成功之后在切换回来并没有到根控制器

### ISSUE THREAD

**Issue by iumiaomiao** [ChenYilong/CYLTabBarController#214]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
写个demo给我，luohanchenyilong@163.com

**Comment by iumiaomiao** [comment]
已经发送,请查收,谢谢

**Comment by ChenYilong** [comment]
请更新到v1.17.2以上的版本，该问题已经修复。
