### ISSUE TITLE
请问有没有方法可以在修改语言后刷新Tab本身的文字？

### ISSUE THREAD

**Issue by wyk111wyk** [ChenYilong/CYLTabBarController#217]
## Base Info for this issue 

 1. Version：v1.17.1
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
这里有完整方案介绍：https://github.com/ChenYilong/CYLTabBarController/issues/247
