### ISSUE TITLE
怎样在其他的页面获取到CYLTabBarController

### ISSUE THREAD

**Issue by am1993421** [ChenYilong/CYLTabBarController#218]
1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：NO

self.tabBarController好像不行 怎样在其他的页面获取到CYLTabBarController 谢谢！

**Comment by ChenYilong** [comment]
v1.17.3版本更新下，然后重试下。
