### ISSUE TITLE
可以添加两个 PushButton 按钮吗?

### ISSUE THREAD

**Issue by loss99** [ChenYilong/CYLTabBarController#219]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
近期会考虑添加该功能，主要的思路是不同的context，只要匹配上就可以展示。目前还仅仅支持一个plusbutton。

**Comment by ChenYilong** [comment]
我觉得你的需求类似于这种：https://github.com/ChenYilong/CYLTabBarController/issues/139
