### ISSUE TITLE
push后导航栏会变成白色

### ISSUE THREAD

**Issue by luo-h** [ChenYilong/CYLTabBarController#221]
从一级界面push到二级界面导航栏颜色就会变成白色，请问这是怎么回事，检查好久没看出问题啊

**Comment by ChenYilong** [comment]
导航栏颜色需要自己手动控制

**Comment by luo-h** [comment]
我在二级控制器也修改不了导航栏的颜色，是push到二级控制器后主导航栏颜色有个向上收起的过程，然后变成了白色

**Comment by ChenYilong** [comment]
版本号提供下，另外能否提供一个demo给我 luohanchenyilong艾特163.com

**Comment by luo-h** [comment]
你好，我之前本来写了demo发给你，但是demo又是对的，我找到原因了，是因为我导入了一个三方库WRNavigationBar就会出现这个问题，具体原因我也不知道，只要导入库就算不导入头文件都会出现问题，神奇

**Comment by ChenYilong** [comment]
了解了，如果问题解决了，可以关掉issue
