### ISSUE TITLE
重新设置viewControllers bug

### ISSUE THREAD

**Issue by pingguoilove** [ChenYilong/CYLTabBarController#222]
## Base Info for this issue 

 1. Version：v1.13.2
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug
## 1. How to repeat the problem.

1. rootVC为CYLTabBarController  
2.viewDidLoad设置viewControllers
3.过2秒重新设置viewControllers，屏幕会黑掉。如果设置viewControllers后设置selectedIndex，屏幕不会黑掉，但会导致页面切换过去，但是底部tabbarItem的选中状态不正确(例如TabBarController的selectedIndex=1,tabBarItem选中的是第2个。

**Comment by ChenYilong** [comment]
发个demo给我luohanchenyilong艾特163.com

**Comment by ChenYilong** [comment]
版本号也标注下，目前最新版是1.17.4

**Comment by pingguoilove** [comment]
好的，谢谢大神这么快回复

**Comment by pingguoilove** [comment]
设置代码如下
```objc
- (void)refreshControllersBug1 {
    self.tabBarController.tabBarItemsAttributes = self.tabBarItemsAttributesForController;
    self.tabBarController.viewControllers = self.viewControllers;
}

- (void)refreshControllersBug2 {
    self.tabBarController.tabBarItemsAttributes = self.tabBarItemsAttributesForController;
    self.tabBarController.viewControllers = self.viewControllers;
    self.tabBarController.selectedIndex = 1;
}
```

bug1:重新设置viewcontrollers，但是不修改selectedIndex，selectedViewController不正常，手动点击切换tab后正常。
bug2:重新设置viewcontrollers，然后设置selectedIndex，底部tabbar的selectItem状态不同步。手动点击切换tab后正常。

[bug demo](git@github.com:pingguoilove/CYLTabBarControllerBug.git)

**Comment by ChenYilong** [comment]
周末给你看下

**Comment by pingguoilove** [comment]
@ChenYilong 谢谢

**Comment by XL-Andrew** [comment]
同问，有解决方案么？也是遇到这个问题

**Comment by pingguoilove** [comment]
@XL-Andrew 我目前用系统原生的TabBarController啦，目前也没用到定制plus button

**Comment by pingguoilove** [comment]
@XL-Andrew 我自定义了tabbar，也没出现这个问题。应该是CYLTabBarController有点小问题

**Comment by dudongdaoqi** [comment]
我也出现的了这个bug

**Comment by ChenYilong** [comment]
这里给出了方案：https://github.com/ChenYilong/CYLTabBarController/issues/247
