### ISSUE TITLE
设置了tabbaritem图片偏移量之后，添加小红点位置显示不正确，每次点击都会往上做累加偏移

### ISSUE THREAD

**Issue by liubang0909** [ChenYilong/CYLTabBarController#223]
## Base Info for this issue 

 1. Version：v1.17.4
 2. Language：Objective-C
 4. iOS System Version：iOS11.2
 5. Prototype（是否是真机）：NO
 6. Issue Type：Q-A

## 1. How to repeat the problem.

    UIEdgeInsets imageInsets =UIEdgeInsetsMake(-10, 0,0, 0);//不正常
    UIEdgeInsets imageInsets =UIEdgeInsetsMake(-5, 0,5, 0);//正常
是我对UIEdgeInsetsMake这个属性理解有问题？如果我要用能拖拽的badgeview是否直接替换三方的就可以？本人是小白，希望大腿能指教下，感谢🙏

**Comment by ChenYilong** [comment]
听你的描述，初步判断为库的bug

**Comment by ChenYilong** [comment]
请先调整下imageInsets，保证不偏移。随后版本会修复。

**Comment by liubang0909** [comment]
好的👌 小问题

**Comment by PilotLee** [comment]
UIEdgeInsets 必须设置上左下右 必须设置对称 不然就会出bug 设置堆成就行了

**Comment by ChenYilong** [comment]
v1.19.0更改小红点实现方式，并增加多个API自定义红点UI样式、动画效果。请更新重试。相关API展示在CYLBadgeProtocol.h 中
效果图：
![enter image description here](http://i64.tinypic.com/2h835ae.jpg)

**Comment by liubang0909** [comment]
感谢🙏

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/383
