### ISSUE TITLE
indexOfPlusButtonInTabBar 指定位置的问题

### ISSUE THREAD

**Issue by xuanlingzi** [ChenYilong/CYLTabBarController#225]
## Base Info for this issue 

 1. Version：v1.16.0
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：NO
 6. Issue Type：Bug

## 1. How to repeat the problem.

Example 的 CYLPlusButtonSubclass.m 使用 plusChildViewController 方式，只要 indexOfPlusButtonInTabBar 指定的是0-3的位置，则会出现图中情况
<img width="383" alt="2017-12-25 10 34 54" src="https://user-images.githubusercontent.com/5276407/34331175-4772ff28-e95f-11e7-98cc-a1b60cd09e44.png">

## 2. Please help me in this way.
有没有办法在不加PlusButton的方式，只放大某个 TabBarItem 的图片

## 4. Here is my Debug log

选择其他TabItem，第一次点击PlusButton
2017-12-25 10:38:20.551200+0800 CYLTabBarController[57418:7851241] 🔴类名与方法名：+[CYLPlusButtonSubclass shouldSelectPlusChildViewController]（在第153行），描述：PlusButton is not selected
继续点击 PlusButton
2017-12-25 10:38:22.867790+0800 CYLTabBarController[57418:7851241] 🔴类名与方法名：+[CYLPlusButtonSubclass shouldSelectPlusChildViewController]（在第151行），描述：PlusButton is selected
2017-12-25 10:38:26.491625+0800 CYLTabBarController[57418:7851241] 🔴类名与方法名：+[CYLPlusButtonSubclass shouldSelectPlusChildViewController]（在第151行），描述：PlusButton is selected

**Comment by HobaoKing** [comment]
我也遇到相同的问题， 
` + (UIViewController *)plusChildViewController { 
    UIViewController *plusChildViewController = [[UIViewController alloc] init];
    plusChildViewController.view.backgroundColor = [UIColor redColor];
    plusChildViewController.navigationItem.title = @"PlusChildViewController";
    UIViewController *plusChildNavigationController = [[UINavigationController alloc]
                                                   initWithRootViewController:plusChildViewController];
    return plusChildNavigationController;
 } 

+ (NSUInteger)indexOfPlusButtonInTabBar {
    return 2;
} 
`

**Comment by kangtian** [comment]
我也遇到了啊  DOME  也没这样的样品

**Comment by mrliu555464** [comment]
修改一下源码吧， 我也遇到这个问题了， 作者在计算TabBar的X坐标的时候 出现了错误。 我把修改后的放上来。 
[self.tabBarButtonArray enumerateObjectsUsingBlock:^(UIView * _Nonnull childView, NSUInteger buttonIndex, BOOL * _Nonnull stop) {
            //调整UITabBarItem的位置
            CGFloat childViewX;
            //by Loki
            if (buttonIndex <= plusButtonIndex) {
                childViewX = buttonIndex * CYLTabBarItemWidth;
            }else {
                childViewX = (buttonIndex - 1) * CYLTabBarItemWidth + CYLPlusButtonWidth;
            }
            //Old
//            if (buttonIndex >= plusButtonIndex) {
//                childViewX = buttonIndex * CYLTabBarItemWidth + CYLPlusButtonWidth;
//            } else {
//                childViewX = buttonIndex * CYLTabBarItemWidth;
//            }
            //仅修改childView的x和宽度,yh值不变
            childView.frame = CGRectMake(childViewX,
                                         CGRectGetMinY(childView.frame),
                                         CYLTabBarItemWidth,
                                         CGRectGetHeight(childView.frame)
                                         );
        }];

**Comment by ChenYilong** [comment]
@xuanlingzi @HobaoKing @kangtian @mrliu555464 @pengqun v1.17.5版本已经发布修复了该问题，请更新重试。
