### ISSUE TITLE
swift下加号无法显示

### ISSUE THREAD

**Issue by wongwenlei** [ChenYilong/CYLTabBarController#226]
## Base Info for this issue 

 1. Version：v1.17.4
 2. Language：Swift4.0
 4. iOS System Version：iOS11.2
 5. Prototype（是否是真机）：NO
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

中间的plus按钮无法显示

## 2. Please help me in this way.

swift使plus按钮正常显示

## 3. Here is a Demo. 

通过邮箱发送demo

**Comment by WeMadeCode** [comment]
我也出现了这个问题

**Comment by ChenYilong** [comment]
从1.17.4版本起，需要通过规定的初始化方法来进行初始化，


 ```Objective-C
- (instancetype)initWithViewControllers:(NSArray<UIViewController *> *)viewControllers
                  tabBarItemsAttributes:(NSArray<NSDictionary *> *)tabBarItemsAttributes;
 ```

现在仓库里的swift-demo还未更新，稍后会更新。

**Comment by ChenYilong** [comment]
另外也欢迎帮忙修改下仓库里的swift demo，提一个pr。

**Comment by WeMadeCode** [comment]
@ChenYilong  多谢指点，仓库里的Swift版本有点老了，最新写了个https://github.com/WeMadeCode/CYLTabBarController-Swift
Swift版本的简单用法，希望指点与采纳

**Comment by ChenYilong** [comment]
@WeMadeCode 十分感谢，另外你再检查下你的demo，截止你的第三个  commit ：18355f87e99bb09f1b5ebd10ddd11b451c129ffc demo无法这个正常运行，pod install也是失败的，请检查target name设置是否与podfile 里的设置能够匹配。

**Comment by WeMadeCode** [comment]
@ChenYilong  Sorry 由于我修改工程名的操作，造成了这个问题
https://github.com/WeMadeCode/CYLTabBarController-Swift
我重新传了一份
麻烦您了。

**Comment by ChenYilong** [comment]
@WeMadeCode 已经采纳，并在文档中进行了署名，感谢。我的仓库中也已经上传了你的 [最新版](https://github.com/WeMadeCode/CYLTabBarController-Swift/commit/f8628799b72caaaa516340a58ef182b962b68d17)  ，代码未做修改，欢迎验证下我仓库中的版本是否属于你的预期。后期如果你这边有更新的话，欢迎提PR，再次表示感谢。

**Comment by WeMadeCode** [comment]
@ChenYilong 非常感谢  我以后将继续学习CYLTabBarController，并将提交更多的Swift版本功能

**Comment by eveloson** [comment]
@ChenYilong 那么StoryBoard创建的怎么初始化呢

**Comment by kcchen2012** [comment]
我也遇到一样的疑问，“那么StoryBoard创建的怎么初始化呢？”

**Comment by rxvincent** [comment]
同样的问题，请问通过StoryBoard创建的有没有办法解决？

**Comment by rxvincent** [comment]
自行解决，在Storyboard连接的类里的viewDidLoad()，我加入了以下的代码
`super.viewDidLoad()
        setBarItem()//设置图标名称
        setViewControllers()//将原本连接到children的vc连接到viewControllers
        MainFunctionButton.register()//注册加号
        (tabBar as! CYLTabBar).context = "CYLTabBarController"//手动设置context`
不知道这样写会不会导致崩溃类问题，iOS12的iphoneX成功

**Comment by ChenYilong** [comment]
Storyboard的tabbar在图形界面也可以自定义归属类

**Comment by rxvincent** [comment]
应该说，在Storyboard指定tabBarController的归属类后，不会调用任何init方法，而跟plusButton相关的逻辑我看到放在了setContext里面，如果是用Storyboard创建是不会调用这个方法的

**Comment by ChenYilong** [comment]
多谢提供解决方案
