### ISSUE TITLE
 cyl_popSelectTabBarChildViewControllerAtIndex不改变状态

### ISSUE THREAD

**Issue by chiyaoyao** [ChenYilong/CYLTabBarController#227]
## Base Info for this issue 

 [self.viewController cyl_popSelectTabBarChildViewControllerAtIndex:1];
用这个跳转到自定义tabbaritem。不会改变状态

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
需要像如下调用一个方法，参考Demo里的演示：

https://github.com/ChenYilong/CYLTabBarController/blob/master/Example/AppDelegate.m#L95

 ```Objective-C
#pragma mark - delegate

- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController {
    [[self cyl_tabBarController] updateSelectionStatusIfNeededForTabBarController:tabBarController shouldSelectViewController:viewController];
    return YES;
}
 ```

**Comment by ChenYilong** [comment]
截止v1.17.4，popSelect系列方法还没有兼容包含 CYLPlusChildViewController 的场景，稍后会兼容下，目前可以通过自主改变plusButton选择状态进行兼容。

**Comment by chiyaoyao** [comment]
下载测试demo https://github.com/ChenYilong/CYLTabBarController/blob/master/Example/Classes/View/CYLPlusButtonSubclass.m#L87 只将这里修改成
[button addTarget:button action:@selector(plusChildViewController) forControlEvents:UIControlEventTouchUpInside];
https://github.com/ChenYilong/CYLTabBarController/blob/master/Example/Classes/Module/Home/CYLHomeViewController.m#L56
注释 [self cyl_popSelectTabBarChildViewControllerAtIndex:4];
会跳转至发现界面，但是发现按钮不会改变状态，其他几个按钮可以

**Comment by chiyaoyao** [comment]
怎么取到 plusButton

**Comment by ChenYilong** [comment]
因为plusbutton是接入方初始化的，所以自己可以直接获取

**Comment by chiyaoyao** [comment]
UIButton *buttn = CYLExternPlusButton;
        buttn.selected = YES;
        [self cyl_popSelectTabBarChildViewControllerAtIndex:1];
最后这样实现，测试可行
