### ISSUE TITLE
CYLPlusButton  越界响应问题

### ISSUE THREAD

**Issue by kangtian** [ChenYilong/CYLTabBarController#228]
## Base Info for this issue 

 1. Version：v1.17.5
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：NO
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

![1](https://user-images.githubusercontent.com/13611448/34348212-05f59d9a-ea44-11e7-97b1-ac3a882efc7a.gif)

**Comment by kangtian** [comment]
点 同城 空包区域响应的却是 CYLPlusButton

**Comment by ChenYilong** [comment]
包空什么意思，详细描述下复现步骤。

**Comment by kangtian** [comment]
点 同城区域响应的却是 CYLPlusButton

**Comment by kangtian** [comment]
界面三个功能按钮，中间按钮凸出 ，占位面积不大 ， 左边按钮能正常响应。 右边按钮  左侧空白区域响应的是 凸出按钮的控制器

**Comment by ChenYilong** [comment]
最新版1.17.5测试没有该问题，建议你改变下plusButton的背景颜色，看下你点击的是否就是plusButton。

**Comment by ChenYilong** [comment]
真对plusViewController场景，确实有该问题，已经修复。更新下1.17.6

**Comment by fanyuexiang** [comment]
@ChenYilong 1.17.6依然存在这个问题.plusViewController场景下,plusButton 后面的那个barItem的相应区域不正常

**Comment by kangtian** [comment]
弃坑  换别的了

**Comment by lilin87788** [comment]
@kangtian 相比之下目前这个框架我认为是最好的了，而且作者一直在用心维护

**Comment by ChenYilong** [comment]
如#234 所言：在 PlusChildViewController 样式里， 由于在框架内部，错误设置了 plusButton 的宽度，导致CYLPlusButton 越界响应问题，后在1.17.6版本中，绕过，但并未彻底解决，现在在1.17.23版本中彻底解决。往更新重试。
