### ISSUE TITLE
iOS11 设置背景图片后,调用hideTabBadgeBackgroundSeparator,顶部阴影不移除

### ISSUE THREAD

**Issue by lionnner** [ChenYilong/CYLTabBarController#229]
## Base Info for this issue 

 1. Version： v1.16.0
 2. Language：Objective-C
 4. iOS System Version：iOS11.2.1
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

下载现有的demo 直接打开设置背景图片的代码，顶部阴影没有消失。
[tabBarController hideTabBadgeBackgroundSeparator]; 这个方法没有隐藏顶部阴影。
![screen shot 2017-12-28 at 11 18 17](https://user-images.githubusercontent.com/19425203/34399286-f7f1509e-ebc0-11e7-8b0d-a39f948f8b1d.png)

**Comment by ChenYilong** [comment]
是个问题，后期会修复掉

**Comment by ChenYilong** [comment]
新版本已经更新hideTabBadgeBackgroundSeparator内部实现，修复了该问题。
