### ISSUE TITLE
点击横屏，tabbar 的Y值会发生改变，而我的需求不需要改变

### ISSUE THREAD

**Issue by Casabalnca** [ChenYilong/CYLTabBarController#231]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by Casabalnca** [comment]
[CYLTabBarController-master 3.zip](https://github.com/ChenYilong/CYLTabBarController/files/1592917/CYLTabBarController-master.3.zip)

**Comment by ChenYilong** [comment]
目前已经修复，强制高度了，目前demo里有演示，你点击进某个二级页面会有横屏的展示。
