### ISSUE TITLE
更新到最新版本，plusButton消失了

### ISSUE THREAD

**Issue by CherishSmile** [ChenYilong/CYLTabBarController#233]
## Base Info for this issue 

 1. Version：v1.17.6
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
swift版本吗？swift版本看本仓库中最新demo里的演示。

**Comment by ChenYilong** [comment]
oc的话发demo给我luohanchenyilong艾特163.com

**Comment by CherishSmile** [comment]
OC,本来之前版本好好的，用cocoapods更新到最新版本，中间的plusButton,不见了。找了好长时间，不知道怎么回事。

**Comment by ChenYilong** [comment]
贴一下CYLTabBarController的初始化方式，现在必须要用接口给出的初始化接口，简单new一个是不行的，要用给出的initWith方法。

**Comment by CherishSmile** [comment]
CYLTabBarController *tab = [[CYLTabBarController alloc] init];
用的这个

**Comment by CherishSmile** [comment]
知道原因了，必须用提供的初始化接口。谢谢了

**Comment by ChenYilong** [comment]
参考这个issue：https://github.com/ChenYilong/CYLTabBarController/issues/248
