### ISSUE TITLE
点击tabbar 按钮部分区域不响应

### ISSUE THREAD

**Issue by bluesea** [ChenYilong/CYLTabBarController#234]
## Base Info for this issue 

使用Demo例子运行，设置tabbar按钮一共3个（包括自定义的不规则按钮）。
问题：点击最后个tabbar的按钮，前半段区域不响应
点击 PlusButton 跳转到指定 UIViewController时候才这样。。

 1. Version：v1.17.6
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

**Comment by bluesea** [comment]
另外使用的不规则按钮点击跳转到指定VC，才会这样。。。

**Comment by fanyuexiang** [comment]
这个是个bug, 当只有两个tabbar item时, 然后在设置一个PlusButton,这时候点击最后一个item,item 的响应范围有问题,只有等待作者更新了

**Comment by bluesea** [comment]
并非是" 当只有两个tabbar item",三个的时候也一样有这问题

**Comment by bluesea** [comment]
暂时在hitTest方法那边判断了点击index是否是plusindex处理...不太靠谱

**Comment by ChenYilong** [comment]
谁花个图，详细描述下

**Comment by bluesea** [comment]
<img width="409" alt="wx20180110-165031 2x" src="https://user-images.githubusercontent.com/1192659/34763503-6c8434ac-f626-11e7-9b33-753ce4cd660c.png">
<img width="738" alt="wx20180110-165045 2x" src="https://user-images.githubusercontent.com/1192659/34763533-81f66508-f626-11e7-9435-a4962aa2ff05.png">
点击最后个tabbar的左侧，其实是点击选择了第二个tabbar，导致不响应、、

**Comment by ChenYilong** [comment]
#228

**Comment by bluesea** [comment]
我看了228的问题，结果是1.17.6版本还存在该问题额

**Comment by shengxiaolei** [comment]
同样还是存在该问题诶

**Comment by ftxbird** [comment]
...我刚遇到...  有人有解决方案了么

**Comment by YingWenMingZi** [comment]
解决了这个问题了吗？1.17.6版本还是出现这个问题

**Comment by aiyang** [comment]
- (void)layoutSubviews {
    [super layoutSubviews];
    NSArray *sortedSubviews = [self sortedSubviews];
    self.tabBarButtonArray = [self tabBarButtonFromTabBarSubviews:sortedSubviews];
    if (self.tabBarButtonArray.count == 0) {
        return;
    }
    [self setupTabImageViewDefaultOffset:self.tabBarButtonArray[0]];
    CGFloat tabBarWidth = self.bounds.size.width;
    CGFloat tabBarHeight = self.bounds.size.height;
    
    if (!CYLExternPlusButton) {
        return;
    }
    
    if (![self hasPlusChildViewController]) {
        self.tabBarItemWidth = CYLTabBarItemWidth;
    }
    
    BOOL addedToTabBar = [_plusButton.superview isEqual:self];
    if (!addedToTabBar) {
        CYLTabBarItemWidth = (tabBarWidth) / CYLTabbarItemsCount;
        [self.tabBarButtonArray enumerateObjectsUsingBlock:^(UIView * _Nonnull childView, NSUInteger buttonIndex, BOOL * _Nonnull stop) {
            //仅修改childView的x和宽度,yh值不变
            CGFloat childViewX = buttonIndex * CYLTabBarItemWidth;
            [self changeXForChildView:childView childViewX:childViewX tabBarItemWidth:CYLTabBarItemWidth];
        }];
        
    } else {
        CYLTabBarItemWidth = (tabBarWidth - CYLPlusButtonWidth) / CYLTabbarItemsCount;
        CGFloat multiplierOfTabBarHeight = [self multiplierOfTabBarHeight:tabBarHeight];
        CGFloat constantOfPlusButtonCenterYOffset = [self constantOfPlusButtonCenterYOffsetForTabBarHeight:tabBarHeight];
        _plusButton.center = CGPointMake(tabBarWidth * 0.5, tabBarHeight * multiplierOfTabBarHeight + constantOfPlusButtonCenterYOffset);
        NSUInteger plusButtonIndex = [self plusButtonIndex];
        [self.tabBarButtonArray enumerateObjectsUsingBlock:^(UIView * _Nonnull childView, NSUInteger buttonIndex, BOOL * _Nonnull stop) {
            //调整UITabBarItem的位置
            CGFloat childViewX;
            if ([self hasPlusChildViewController]) {
                if (buttonIndex <= plusButtonIndex) {
                    if (buttonIndex == plusButtonIndex) {
                        self.tabBarItemWidth = CYLPlusButtonWidth;
                    }else{
                        self.tabBarItemWidth = CYLTabBarItemWidth;
                    }
                    childViewX = buttonIndex * CYLTabBarItemWidth;
                } else {
                    childViewX = (buttonIndex - 1) * CYLTabBarItemWidth + CYLPlusButtonWidth;
                    self.tabBarItemWidth = CYLTabBarItemWidth;
                }
            } else {
                if (buttonIndex >= plusButtonIndex) {
                    childViewX = buttonIndex * CYLTabBarItemWidth + CYLPlusButtonWidth;
                } else {
                    childViewX = buttonIndex * CYLTabBarItemWidth;
                }
            }
            //仅修改childView的x和宽度,yh值不变
            [self changeXForChildView:childView childViewX:childViewX tabBarItemWidth:self.tabBarItemWidth];
        }];
        //bring the plus button to top
        [self bringSubviewToFront:_plusButton];
    }
    

}

**Comment by aiyang** [comment]
在CYLTabBar.m文件中替换一下这个方法
- (void)layoutSubviews {
    [super layoutSubviews];
    NSArray *sortedSubviews = [self sortedSubviews];
    self.tabBarButtonArray = [self tabBarButtonFromTabBarSubviews:sortedSubviews];
    if (self.tabBarButtonArray.count == 0) {
        return;
    }
    [self setupTabImageViewDefaultOffset:self.tabBarButtonArray[0]];
    CGFloat tabBarWidth = self.bounds.size.width;
    CGFloat tabBarHeight = self.bounds.size.height;
    
    if (!CYLExternPlusButton) {
        return;
    }
    
    if (![self hasPlusChildViewController]) {
        self.tabBarItemWidth = CYLTabBarItemWidth;
    }
    
    BOOL addedToTabBar = [_plusButton.superview isEqual:self];
    if (!addedToTabBar) {
        CYLTabBarItemWidth = (tabBarWidth) / CYLTabbarItemsCount;
        [self.tabBarButtonArray enumerateObjectsUsingBlock:^(UIView * _Nonnull childView, NSUInteger buttonIndex, BOOL * _Nonnull stop) {
            //仅修改childView的x和宽度,yh值不变
            CGFloat childViewX = buttonIndex * CYLTabBarItemWidth;
            [self changeXForChildView:childView childViewX:childViewX tabBarItemWidth:CYLTabBarItemWidth];
        }];
        
    } else {
        CYLTabBarItemWidth = (tabBarWidth - CYLPlusButtonWidth) / CYLTabbarItemsCount;
        CGFloat multiplierOfTabBarHeight = [self multiplierOfTabBarHeight:tabBarHeight];
        CGFloat constantOfPlusButtonCenterYOffset = [self constantOfPlusButtonCenterYOffsetForTabBarHeight:tabBarHeight];
        _plusButton.center = CGPointMake(tabBarWidth * 0.5, tabBarHeight * multiplierOfTabBarHeight + constantOfPlusButtonCenterYOffset);
        NSUInteger plusButtonIndex = [self plusButtonIndex];
        [self.tabBarButtonArray enumerateObjectsUsingBlock:^(UIView * _Nonnull childView, NSUInteger buttonIndex, BOOL * _Nonnull stop) {
            //调整UITabBarItem的位置
            CGFloat childViewX;
            if ([self hasPlusChildViewController]) {
                if (buttonIndex <= plusButtonIndex) {
                    if (buttonIndex == plusButtonIndex) {
                        self.tabBarItemWidth = CYLPlusButtonWidth;
                    }else{
                        self.tabBarItemWidth = CYLTabBarItemWidth;
                    }
                    childViewX = buttonIndex * CYLTabBarItemWidth;
                } else {
                    childViewX = (buttonIndex - 1) * CYLTabBarItemWidth + CYLPlusButtonWidth;
                    self.tabBarItemWidth = CYLTabBarItemWidth;
                }
            } else {
                if (buttonIndex >= plusButtonIndex) {
                    childViewX = buttonIndex * CYLTabBarItemWidth + CYLPlusButtonWidth;
                } else {
                    childViewX = buttonIndex * CYLTabBarItemWidth;
                }
            }
            //仅修改childView的x和宽度,yh值不变
            [self changeXForChildView:childView childViewX:childViewX tabBarItemWidth:self.tabBarItemWidth];
        }];
        //bring the plus button to top
        [self bringSubviewToFront:_plusButton];
    }
    

}

**Comment by ChenYilong** [comment]
如#228 所言：在 PlusChildViewController 样式里， 由于在框架内部，错误设置了 plusButton 的宽度，导致CYLPlusButton 越界响应问题，后在1.17.6版本中，绕过，但并未彻底解决，现在在1.17.23版本中彻底解决。往更新重试。多谢@aiyang 提供方案。
