### ISSUE TITLE
能否支持button之间自定义间距

### ISSUE THREAD

**Issue by gdfyj90** [ChenYilong/CYLTabBarController#235]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Enhancement（希望能支持一个新需求）

## 2. Please help me in this way.

ipad上希望可以实现button之间自定义间距，而不是平均分布

**Comment by ChenYilong** [comment]
初始化方式里有自定义间距的接口。
