### ISSUE TITLE
在pad上baritem的排列和iphone上不一致

### ISSUE THREAD

**Issue by gdfyj90** [ChenYilong/CYLTabBarController#236]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

你的demo在pad运行，tabbaritem变成了图片在左文字在右，这个是系统自动调整的吗，如何改成和iphone的一样呢

**Comment by ChenYilong** [comment]
系统自动调整的，需要CYLTabBar的traitCollection方法进行如下重写：


 ```Objective-C

// In iOS 11, UITabBarItem's have the title to the right of the icon in horizontally regular environments
// (i.e. the iPad).  In order to keep the title below the icon, it was necessary to subclass UITabBar and override
// traitCollection to make it horizontally compact.

- (UITraitCollection *)traitCollection {
    return [UITraitCollection traitCollectionWithHorizontalSizeClass:UIUserInterfaceSizeClassCompact];
}
 ```

**Comment by rakuyoMo** [comment]
这一块儿能不能在 `CYLTabBar` 中提供一个接口？可以用一个 `bool` 值来控制是否变为上下显示。
