### ISSUE TITLE
能否给plusBtn一个生命周期，去管理plusBtn的出现和消失

### ISSUE THREAD

**Issue by bluestonesea** [ChenYilong/CYLTabBarController#237]
现在有很多APP 会根据活动进行plusBtn这种突出主题活动，但是在活动结束后会让他消失，现在没有好的方法能让这个plusBtn让开发者去掌控他的出现和消失呢？

**Comment by Qinzhao** [comment]
我也很需要，希望给我方法， 如何编写这块控制

**Comment by 2010212392** [comment]
我们现在也有这种需求 可否给个方案   谢谢

**Comment by LCWCG** [comment]
同求，谢谢

**Comment by ChenYilong** [comment]
这里给出了解决方案，https://github.com/ChenYilong/CYLTabBarController/issues/247

同时也可以动态隐藏plusbutton
