### ISSUE TITLE
关于tabbar 上方黑线的问题

### ISSUE THREAD

**Issue by TinySungo** [ChenYilong/CYLTabBarController#238]
## Base Info for this issue 

 1. Version：v1.14.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

tabbar的subViewController（MineViewController） 中 present了一个横屏的RotationNavigationController根视图控制器是 RotationViewController，dismiss之后Tabbar 出现上方黑线。

1. RotationNavigationController 重写了旋转相关三个方法
- (BOOL)shouldAutorotate {
    return NO;
}
- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskLandscapeLeft;
}
- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation {
    return UIInterfaceOrientationLandscapeLeft;
}

2. 在MineViewController 的 viewWillAppear中写了隐藏黑线
    if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 10.0) {
        self.tabBarController.tabBar.subviews[0].subviews[1].hidden = YES;
    }

3. RotationViewController  dismiss 之后，Tabbar出现了黑线

**Comment by ChenYilong** [comment]
//去除 TabBar 自带的顶部阴影
    需要使用 -[CYLTabBarController hideTabBarShadowImageView] 

见README

并参考：https://github.com/ChenYilong/CYLTabBarController/issues/386

**Comment by ChenYilong** [comment]
你是隐藏后，别的页面又出现了？
