### ISSUE TITLE
图标能否支持iconfont

### ISSUE THREAD

**Issue by iNathan-yanboo** [ChenYilong/CYLTabBarController#240]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

图标能否支持iconfont

**Comment by ChenYilong** [comment]
原理上是支持的，使用iconfont 初始化为UIImage对象后，进行CYLTabBarController的初始化就可以了。
