### ISSUE TITLE
底部的TabBar 消失

### ISSUE THREAD

**Issue by LWHai** [ChenYilong/CYLTabBarController#242]
## Base Info for this issue 

 1. Version：v1.16.0
 2. Language：Objective-C
 4. iOS System Version：iOS11  iOS8
 5. Prototype（是否是真机）：NO
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

用storyboard 创建的ViewController 底部的TabBar 消失 但是我不用storyboard 直接new的就没事一旦点击了切换到storyboard 创建的ViewController就消失了，是暂时不支持这样添加的方式吗？

## 3. Here is a Demo. 

@implementation RDTabBarController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    [self settupViewControllers];
}

- (void)settupViewControllers
{
    RDEquipmentViewController *eq = [RDEquipmentViewController shareStoryboardViewController];
    NYNavigationController *eqNav = [[NYNavigationController alloc] initWithRootViewController:eq];
    
    RDDataViewController *dt = [RDDataViewController shareStoryboardViewController];
    NYNavigationController *dtNav = [[NYNavigationController alloc] initWithRootViewController:dt];
    
    RDMyViewController *my = [RDMyViewController shareStoryboardViewController];
    NYNavigationController *myNav = [[NYNavigationController alloc] initWithRootViewController:my];
    
    
    //设置TabBarItem样式
    [self setUpTabBarItemsAttributesForController];
    
    [self setViewControllers:@[eqNav, dtNav , myNav]];
}

**Comment by LWHai** [comment]
问题解决了。整个navigation 用storyboard创建就没事了。

**Comment by ChenYilong** [comment]
里面也有storyboard的demo链接

**Comment by ChenYilong** [comment]
文档里

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/241

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/170
