### ISSUE TITLE
PlusBtn突然消失？？？切换界面，Btn消失。

### ISSUE THREAD

**Issue by Kid-J** [ChenYilong/CYLTabBarController#244]
## Base Info for this issue 

1. PlusBtn突然消失？？？
2. 切换界面，Btn消失，有PopViewController或者右滑返回。

 1. Version：v1.17.0
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

1. 暂没发现复现规律

**Comment by pengcff** [comment]
我这边也复现了，在注销账号重新登录后，问题代码出现在CYLTabBar.m第140行
`BOOL addedToTabBar = [_plusButton.superview isEqual:self];`
这里addedToTabBar返回了NO，下面是po 出来的一些Log

(lldb) po _plusButton
<DDPlusButtonSubclass: 0x7f912a419d60; baseClass = UIButton; frame = (153.5 -29.3; 68 68); opaque = NO; layer = <CALayer: 0x600000432320>>

(lldb) po _plusButton.superview
<CYLTabBar: 0x7f912a76a160; baseClass = UITabBar; frame = (0 618; 375 49); hidden = YES; autoresize = W+TM; gestureRecognizers = <NSArray: 0x604000446000>; layer = <CALayer: 0x60c000238660>>

(lldb) po self
<CYLTabBar: 0x7f9130066a50; baseClass = UITabBar; frame = (0 618; 375 49); autoresize = W+TM; layer = <CALayer: 0x600000a3bf80>>

(lldb) po self.subviews
<__NSArrayM 0x60800065b270>(
<_UIBarBackground: 0x7f9130066cf0; frame = (0 0; 375 49); userInteractionEnabled = NO; layer = <CALayer: 0x600000a3b8e0>>,
<UITabBarButton: 0x7f9130240590; frame = (2 1; 90 48); opaque = NO; layer = <CALayer: 0x60c000634d20>>,
<UITabBarButton: 0x7f912a714e20; frame = (96 1; 90 48); opaque = NO; layer = <CALayer: 0x60c000635ae0>>,
<UITabBarButton: 0x7f9130247d40; frame = (190 1; 89 48); opaque = NO; layer = <CALayer: 0x60c0008244e0>>,
<UITabBarButton: 0x7f9130236da0; frame = (283 1; 90 48); opaque = NO; layer = <CALayer: 0x60c000236800>>
)

(lldb) po _plusButton.superview.subviews
<__NSArrayM 0x600000a47e90>(
<_UIBarBackground: 0x7f912a76aa40; frame = (0 0; 375 49); userInteractionEnabled = NO; layer = <CALayer: 0x60c000238800>>,
<UITabBarButton: 0x7f912a65cdd0; frame = (0 1; 76.75 48); opaque = NO; layer = <CALayer: 0x60800022ec20>>,
<UITabBarButton: 0x7f912a65df50; frame = (76.75 1; 76.75 48); opaque = NO; layer = <CALayer: 0x60800022ed20>>,
<UITabBarButton: 0x7f912a65ebe0; frame = (221.5 1; 76.75 48); opaque = NO; layer = <CALayer: 0x60800022f380>>,
<UITabBarButton: 0x7f912a65f450; frame = (298.25 1; 76.75 48); opaque = NO; layer = <CALayer: 0x60800022f6c0>>,
<DDPlusButtonSubclass: 0x7f912a419d60; baseClass = UIButton; frame = (153.5 -29.3; 68 68); opaque = NO; layer = <CALayer: 0x600000432320>>
)

(lldb) 

也就是说存在了两个CYLTabBar，plusBtn跑到另外一个去了，麻烦作者有空看下@ChenYilong

**Comment by pengcff** [comment]
1.刚跟进了下，发现是我们自己业务逻辑问题导致创建了两个CYLTabBarController
2.但是我们在创建新的CYLTabBarController之前，旧的是有做nil处理的，也就是说CYLTabBarController = nil后，旧的CYLTabBar还是存在，plusBtn在旧的tabbar上面，不在新的tabbar上

**Comment by ChenYilong** [comment]
现在的api有context属性，添加下
