### ISSUE TITLE
tabBarController.delegate代理方法不走,并且只在iPhoneX中 push后 tabbar不消失

### ISSUE THREAD

**Issue by SpTTlv** [ChenYilong/CYLTabBarController#246]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
如何设置代理的，贴下代码。tabbar是否消失需要代码控制，贴下代码

**Comment by SpTTlv** [comment]
谢谢解答,  代理问题解决了 .     tabbar是否消失需要代码控制 这个代码是什么,在哪个地方

**Comment by SpTTlv** [comment]
找到了  在Nav的push方法中!IS_IPHONE_X 我没有注释 谢谢

**Comment by NOMBER2011** [comment]
我也遇到不走代理的问题了？

#import "DubbingRootViewController.h"

@interface DubbingRootViewController ()<UITabBarControllerDelegate, CYLTabBarControllerDelegate>
@property (nonatomic, strong) UIView *launchMask;
@property (nonatomic, strong) LOTAnimationView *launchAnimation;
@property (nonatomic, strong) CYLTabBarController *tabBarController;
@end

@implementation DubbingRootViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    [self setupLaunchMask];
}
- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
}
- (void)setupLaunchMask{
    _launchMask = [[UIView alloc] initWithFrame:self.view.bounds];
    [self.view addSubview:_launchMask];
    
    _launchAnimation = [LOTAnimationView animationNamed:@"data"];
    _launchAnimation.cacheEnable = NO;
    _launchAnimation.frame = self.view.bounds;
    _launchAnimation.contentMode = UIViewContentModeScaleToFill;
    _launchAnimation.animationSpeed = 1.2;
    [_launchMask addSubview:_launchAnimation];
    
    
    if (_launchMask && _launchAnimation) {
        WEAKSELF;
        [_launchAnimation playWithCompletion:^(BOOL animationFinished) {
            
            [UIView animateWithDuration:0.3 animations:^{
                weakSelf.launchMask.alpha = 0;
            } completion:^(BOOL finished) {
                [weakSelf.launchAnimation removeFromSuperview];
                weakSelf.launchAnimation = nil;
                [weakSelf.launchMask removeFromSuperview];
                weakSelf.launchMask = nil;
            }];
            
            [self setGuidePage];
        }];
    }
    
}

-(void)setGuidePage{
    
    //判断是否需要显示：（内部已经考虑版本及本地版本缓存）
    BOOL canShow = [XZMCoreNewFeatureVC canShowNewFeature];
    
    if(canShow){ // 初始化新特性界面
        TFKeyWindow.rootViewController = [XZMCoreNewFeatureVC newFeatureVCWithImageNames:@[@"01_png",@"02_png",@"03_png"] enterBlock:^{
            
            [self mainViewController];
            
        } configuration:^(UIButton *enterButton) {
            
            enterButton.frame=CGRectMake(SCREEN_WIDTH-60, 30, 50, 30);
            [enterButton setTitle:@"进入" forState:0];
            [enterButton setTitleColor:[UIColor whiteColor] forState:0];
            enterButton.layer.cornerRadius=5;
            enterButton.layer.masksToBounds=YES;
            enterButton.layer.borderColor=[UIColor whiteColor].CGColor;
            enterButton.layer.borderWidth=1;
        }];
        
    }else{
        
        [self mainViewController];
    }
    
}

-(void)mainViewController{
    
    TabBarControllerConfig *tabBarControllerConfig = [[TabBarControllerConfig alloc] init];
    self.tabBarController = tabBarControllerConfig.tabBarController;
    self.tabBarController.delegate = self;
    TFKeyWindow.rootViewController=self.tabBarController;
   
    
}
#pragma mark - delegate

- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController {
    [[self cyl_tabBarController] updateSelectionStatusIfNeededForTabBarController:tabBarController shouldSelectViewController:viewController];
    return YES;
}

- (void)tabBarController:(UITabBarController *)tabBarController didSelectControl:(UIControl *)control {
    UIView *animationView;
    
    if ([control cyl_isTabButton]) {
        //更改红标状态
        //        if ([[self cyl_tabBarController].selectedViewController cyl_isShowTabBadgePoint]) {
        //            [[self cyl_tabBarController].selectedViewController cyl_removeTabBadgePoint];
        //        } else {
        //            [[self cyl_tabBarController].selectedViewController cyl_showTabBadgePoint];
        //        }
        
        animationView = [control cyl_tabImageView];
    }
    
    //  即使 PlusButton 也添加了点击事件，点击 PlusButton 后也会触发该代理方法。
    //    if ([control cyl_isPlusButton]) {
    //        UIButton *button = CYLExternPlusButton;
    //        animationView = button.imageView;
    //    }
    
    if ([self cyl_tabBarController].selectedIndex % 2 == 0) {
        
        [self addScaleAnimationOnView:animationView repeatCount:1];
    } else {
        [self addRotateAnimationOnView:animationView];
    }
}

//缩放动画
- (void)addScaleAnimationOnView:(UIView *)animationView repeatCount:(float)repeatCount {
    //需要实现的帧动画，这里根据需求自定义
    CAKeyframeAnimation *animation = [CAKeyframeAnimation animation];
    animation.keyPath = @"transform.scale";
    animation.values = @[@1.0,@1.3,@0.9,@1.15,@0.95,@1.02,@1.0];
    animation.duration = 1;
    animation.repeatCount = repeatCount;
    animation.calculationMode = kCAAnimationCubic;
    [animationView.layer addAnimation:animation forKey:nil];
}

//旋转动画
- (void)addRotateAnimationOnView:(UIView *)animationView {
    // 针对旋转动画，需要将旋转轴向屏幕外侧平移，最大图片宽度的一半
    // 否则背景与按钮图片处于同一层次，当按钮图片旋转时，转轴就在背景图上，动画时会有一部分在背景图之下。
    // 动画结束后复位
    animationView.layer.zPosition = 65.f / 2;
    [UIView animateWithDuration:0.32 delay:0 options:UIViewAnimationOptionCurveEaseIn animations:^{
        animationView.layer.transform = CATransform3DMakeRotation(M_PI, 0, 1, 0);
    } completion:nil];
    
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [UIView animateWithDuration:0.70 delay:0 usingSpringWithDamping:1 initialSpringVelocity:0.2 options:UIViewAnimationOptionCurveEaseOut animations:^{
            animationView.layer.transform = CATransform3DMakeRotation(2 * M_PI, 0, 1, 0);
        } completion:nil];
    });
}

**Comment by NOMBER2011** [comment]
这个是我入口累的方法，帮我看下，谢谢各位了
@interface AppDelegate ()
@property (nonatomic, strong) UIView *launchMask;
@property (nonatomic, strong) LOTAnimationView *launchAnimation;
@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
   
    [self loadRootViewController];
    
   
    
  //  [self setGuidePage];
 
    
    return YES;
}

- (void)loadRootViewController{
    
    //初始化
    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    self.window.backgroundColor = [UIColor whiteColor];
    [self.window makeKeyAndVisible];
    self.window.rootViewController = [[DubbingRootViewController alloc] init];
    
    
    [MTVersionHelper checkNewVersion];
    [TF_NetApiConstant sharedInstance];
}

**Comment by ChenYilong** [comment]
tabbar消失是代码控制的，需要重写 push方法，demo有演示。
