### ISSUE TITLE
重设tabBarItemsAttributes失败,应该如何解决

### ISSUE THREAD

**Issue by lixianshen** [ChenYilong/CYLTabBarController#247]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

在视图初始化过程中,加载网络图片,成功后设置图片,这个时候,tabbar已经初始化完成,通过更改tabBarItemsAttributes,修改 tabbarItem 的图片

**Comment by yangzheng006** [comment]
你是怎么解决的？我现在也与到了这个问题

**Comment by ChenYilong** [comment]
不支持重制： 

// CYLTabBarController不支持UITabBarController同样的更新viewControllers并刷新UI，因此此处采用生成新的tab bar的方式


 ```Objective-C
        MainTabBarController *tabBarController = [[MainTabBarController alloc] initWithViewControllers:viewControllers tabBarItems:tabBarItems];
        if (tabBarItems.count == 1) {
            tabBarController.tabBar.hidden = YES;
        }
        self.viewControllers = @[tabBarController];

 ```

参考 ：https://github.com/ChenYilong/CYLTabBarController/issues/288

**Comment by xiaogehenjimo** [comment]
@ChenYilong 重新创建一个新tabBar控制器, 里面的控制器也重新创建了啊

**Comment by zhaodazhou** [comment]
plusButton的隐藏与否，只能通过重新new一个tabbar来控制吗？

**Comment by ChenYilong** [comment]
> plusButton的隐藏与否，只能通过重新new一个tabbar来控制吗？

目前的实现是这样

**Comment by my-lsk** [comment]
> @ChenYilong 重新创建一个新tabBar控制器, 里面的控制器也重新创建了啊

确实是的，有好的解决方法吗
