### ISSUE TITLE
PlusButton不生效

### ISSUE THREAD

**Issue by Coco1991** [ChenYilong/CYLTabBarController#248]
最新的PlusButton不生效， 老版本是可以了

**Comment by anotherNight** [comment]
[HZBarPlusBtn registerPlusButton];调用无效

**Comment by anotherNight** [comment]
1.17.6

**Comment by Bluner** [comment]
https://github.com/Bluner/CYLTabBarController
一个临时修正此问题的补丁

**Comment by angel-cry** [comment]
我也遇到了，可能作者版本容错的时候没考虑周全。我从比较老的版本升级上来，在-application:didFinishLaunchingWithOptions: 方法里面调用 [YourClass registerPlusButton]，plusButton并不会出现。
        解决办法：
        CYLTabBarController *tabBarController = [[CYLTabBarController alloc] init];
        [tabBarController setViewControllers:@[v1,v2,v3,v4]];
        tabBarController.tabBarItemsAttributes = @[dict1,dict2,dict3,dict4];
        替换成CYLTabBarController中的实例，例如：
        CYLTabBarController *tabBarController = [[CYLTabBarController alloc]initWithViewControllers:@[v1,v2,v3,v4] tabBarItemsAttributes:@[dict1,dict2,dict3,dict4]];

**Comment by zengfx** [comment]
@angel-cry 楼上正解，感谢🙏！
