### ISSUE TITLE
UINavigationController的层级

### ISSUE THREAD

**Issue by gordanyang** [ChenYilong/CYLTabBarController#250]
## Base Info for this issue 

通常在使用UITabBarController过程中，会存在两种比较常见的层级处理方式:
第一种:
├── UITabBarController
└──── UINavigationController
└────── UIViewController
└──────── SubviewControllers
第二种:
├── UINavigationController
└──── UITabBarController
└────── UIViewController
└──────── SubviewControllers

请问，是否支持第二种的层级处理？

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
支持
