### ISSUE TITLE
IPhone X tabbar 图标上移

### ISSUE THREAD

**Issue by lzylzy1991** [ChenYilong/CYLTabBarController#251]
## Base Info for this issue 

 1. Version：v1.14.0
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：IPhone X

<img width="577" alt="7077f1a5-8832-4ae2-9767-57ff8b2e6789" src="https://user-images.githubusercontent.com/14507003/35900848-0b5fa97c-0ba2-11e8-9315-4dda964f938f.png">

**Comment by xiaobeifeng** [comment]
你好，我出现了和你一样的问题，请问你的问题解决了吗？

**Comment by bluesea** [comment]
发现tabBarController.tabBarHeight = CYL_IS_IPHONE_X ? 65 : 40;这代码注释掉就没问题了...

**Comment by xiaobeifeng** [comment]
感谢🙏

在 2018年3月1日，下午2:59，平 <notifications@github.com<mailto:notifications@github.com>> 写道：


发现tabBarController.tabBarHeight = CYL_IS_IPHONE_X ? 65 : 40;这代码注释掉就没问题了...

**Comment by aimm** [comment]
我也是这个问题，但是没找到 tabBarController.tabBarHeight = CYL_IS_IPHONE_X ? 65 : 40 这句代码啊

**Comment by aimm** [comment]
因为没有放iPhone X的启动页图片！！

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/312
