### ISSUE TITLE
能不能动态改变中间plusButton的图片

### ISSUE THREAD

**Issue by Yueeeeee** [ChenYilong/CYLTabBarController#252]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by zhuweideng** [comment]
@Yueeeeee 
`#import "CYLPlusButton.h"

在需要的VC中
- (void)viewWillAppear:(BOOL)animated{
    [super viewWillAppear:animated];    
    UIImage *buttonImage = [UIImage imageNamed:@"main_tab_pub_add"];
    [CYLExternPlusButton setImage:buttonImage forState:UIControlStateNormal];
}`

**Comment by ChenYilong** [comment]
可以，参考：https://github.com/ChenYilong/CYLTabBarController/issues/18
