### ISSUE TITLE
无法实现系统样式的高斯模糊的TabBar

### ISSUE THREAD

**Issue by zzyspace** [ChenYilong/CYLTabBarController#255]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：YES
 6. Issue Type：Enhancement

## 1. How to repeat the problem.
如何实现有透明度的(系统样式的高斯模糊)的tabbar? [[UITabBar appearance] setTranslucent:YES]; 无效

**Comment by zzyspace** [comment]
不设置tabBar的backgroundColor即可.

**Comment by FrankSwift** [comment]
并不能达到更系统一样的效果，请问你怎么设置的
