### ISSUE TITLE
代理方法问题

### ISSUE THREAD

**Issue by junwangInChina** [ChenYilong/CYLTabBarController#259]
## Base Info for this issue 

 1. Version：v1.17.6
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：NO
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.
你好：
      我发现，这个代理方法里面返回了NO之后
      - (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController 
      这个方法任然会执行
      - (void)tabBarController:(UITabBarController *)tabBarController didSelectControl:(UIControl *)control 
      这样会有一个小bug，比我Tabbar设置了4个item，其中的某一个设置满足某些条件后才能访问，此时shouldSelectViewController方法里对该item返回NO，虽然页面不会切换过去，但是didSelectControl方法还是会执行，此时如果设置的点击动画

  if ([control cyl_isTabButton]) {
        //更改红标状态
        if ([[self cyl_tabBarController].selectedViewController cyl_isShowTabBadgePoint]) {
            [[self cyl_tabBarController].selectedViewController cyl_removeTabBadgePoint];
        } else {
            [[self cyl_tabBarController].selectedViewController cyl_showTabBadgePoint];
        }
        animationView = [control cyl_tabImageView];
    } 

这段代码会拿到被禁止的那个item的View，用来执行动画
造成的效果就是点击了某个item，页面没切换，但是被点击的item还是执行动画。

## 2. Please help me in this way.

建议：shouldSelectViewController方法里返回了NO，didSelectControl方法就不需要执行了

## 3. Here is a Demo. 

使用你自己提供的Demo，将shouldSelectViewController方法稍微修改一下即可出现。

## 4. Here is my Debug log

PS：可能是我没有发现其他的设置问题。

**Comment by ChenYilong** [comment]
可以仅仅在需要return YES时才调用`-updateSelectionStatusIfNeededForTabBarController:shouldSelectViewController:viewController`否则不调用即可。

比如像这样：

 ```Objective-C
- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController {
    BOOL shouldSelectViewController = YES;//OR NO
    //only update selection status when you should select viewController
    if (shouldSelectViewController) {
        [[self cyl_tabBarController] updateSelectionStatusIfNeededForTabBarController:tabBarController shouldSelectViewController:viewController];
    }
    //添加仿淘宝tabbar，第一个tab选中后有图标覆盖
    if ([viewController.tabBarItem.cyl_tabButton cyl_isTabButton]|| [viewController.tabBarItem.cyl_tabButton cyl_isPlusButton]) {
        CGFloat index = [tabBarController.viewControllers indexOfObject:viewController];
        BOOL shouldSelectedCoverShow = (index == 0);
        [self setSelectedCoverShow:shouldSelectedCoverShow];
    }
    
    return shouldSelectViewController;
}
 ```

**Comment by ChenYilong** [comment]
更新 demo 修复二次初始化，不走代理方法不走代理方法的问题，

详情见： 
 - https://github.com/ChenYilong/CYLTabBarController/commit/91f6de1af523f096d6ccc2b8a5accbc04b31f850

 - https://github.com/ChenYilong/CYLTabBarController/issues/161
