### ISSUE TITLE
如果不设置plusBtn，但是有5个按钮，想让中间放大的情况？怎么弄？

### ISSUE THREAD

**Issue by Michaelyb520** [ChenYilong/CYLTabBarController#26]
如果不设置plusBtn，但是有5个按钮，想让中间放大的情况？怎么弄？

**Comment by Michaelyb520** [comment]
即中间按钮并不是plusBtn。而是tabbar原生的按钮，但要求他放大。

**Comment by ChenYilong** [comment]
这个需要框架进行支持，后续会添加改功能。敬请关注

**Comment by ChenYilong** [comment]
也可以变一种思路： reference： [《iOS 修改UITabBar的默认点击行为》]( http://www.jianshu.com/p/7c440689574b )

**Comment by hugolubingshen** [comment]
我也有这种需求，就是想点击plusBtn，实现跟tabbar item一样的跳转

**Comment by ChenYilong** [comment]
我的1.2.9已经支持了，详情见文档
