### ISSUE TITLE
自定义小红点无效

### ISSUE THREAD

**Issue by Abnerzj** [ChenYilong/CYLTabBarController#266]
## Base Info for this issue 

在Demo的AppDelegate中提供了自定义配置TabBar方法`-customizeTabBarAppearance`，所以也想把自定义小红点（样式和位置）也统一放在这里面，结果一直都无效。调试发现此时`self.cyl_tabBarController.tabBar.items`为空，只有主窗口设置了`self.cyl_tabBarController.tabBar.items`才有值。为了方便维护，可否支持把自定义小红点的代码统一放在`-customizeTabBarAppearance`中。

 1. Version：v1.16.0
 2. Language：Objective-C
 4. iOS System Version：iOS11.3
 5. Prototype（是否是真机）：YES
 6. Issue Type：Enhancement（希望能支持一个新需求）

## 1. How to repeat the problem.

此段代码放在`-customizeTabBarAppearance`方法中无效，设置AppDelegate的keywindow后可用。
for (UIViewController *vc in _tabBarController.viewControllers) {
            UIView *tabBadgePointView = [UIView cyl_tabBadgePointViewWithClolor:[UIColor colorWithHexString:@"#ef5958"] radius:5.0];
            [vc cyl_setTabBadgePointView:tabBadgePointView];
            [vc cyl_setTabBadgePointViewOffset:UIOffsetMake(4, 4)];
}

**Comment by ChenYilong** [comment]
`customizeTabBarAppearance` 这个时候tabbar还没有初始化成功，所以在这里设置是无效的，`tabBadgePointView` 必须要在初始化成功后设置。

`[UITabBar appearance] `必须在初始化之前调用，所有他们是不能放在一起的。

**Comment by Abnerzj** [comment]
自定义红点可不可以跟tabbar一块初始化呢。

**Comment by ChenYilong** [comment]
v1.19.0更改小红点实现方式，并增加多个API自定义红点UI样式、动画效果。请更新重试。相关API展示在CYLBadgeProtocol.h 中
效果图：
![enter image description here](http://i64.tinypic.com/2h835ae.jpg)
