### ISSUE TITLE
iPhone X 下，选中的背景色位置错乱

### ISSUE THREAD

**Issue by Ryan-Wong-iOS** [ChenYilong/CYLTabBarController#267]
## Base Info for this issue 

![simulator screen shot - iphone x - 2018-04-14 at 10 49 25](https://user-images.githubusercontent.com/13427237/38763668-cbf9a908-3fd2-11e8-9d5c-7ab536ff1599.png)

 1. Version：v1.17.6
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

Demo中运行 customizeTabBarSelectionIndicatorImage 这个方法就会出现

## 2. Please help me in this way.

选中像其他设备型号那样满颜色的效果

**Comment by ChenYilong** [comment]
背景图是自己创建的，高度设置不对把，X的高度要区分。
