### ISSUE TITLE
iPhone X 上可能出现没有tabbar的情况

### ISSUE THREAD

**Issue by onceMu** [ChenYilong/CYLTabBarController#270]
v1.16.0 版本
OC
iOS11 以上
真机
iPhone X
Bug：
     iPhone X 上可能出现出现没有tabbar的情况，因为是用户反应，并没有复现这个问题。
     根据用户的截图展示 第一个子controller 已经加载出来，但是底部tabar 没有展示。

**Comment by ChenYilong** [comment]
看下是不是push的第二个页面内部有透明背景，导致卡顿，pop后，无法正常显示。

**Comment by onceMu** [comment]
根据用户反馈不是，启动应用的时候就没有tabbar。现在遇到了一两个反馈，设备都是iPhone X。

**Comment by onceMu** [comment]
根据反馈的截图，感觉是tabbar 没有初始化成功。我刻意的将图片和标题 置为空，这时候tabbar 最上面的分割线还是会存在的，但是反馈出来的截图，没有分割线。
<img width="169" alt="wechatimg2606" src="https://user-images.githubusercontent.com/3349775/40301055-75280b3e-5d1d-11e8-9b55-b7315f6e48d8.png">

**Comment by ChenYilong** [comment]
更新到 1.17.10，重试下

**Comment by onceMu** [comment]
好的。
