### ISSUE TITLE
顶部黑线去除，iPhoneX 上Tabbar显示异常，使用了scaleImage:toScale:方法设置背景图 tabbar顶部出现两条灰色线

### ISSUE THREAD

**Issue by lztbwlkj** [ChenYilong/CYLTabBarController#272]
## Base Info for this issue 

 1. Version：v1.16.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

copy你demo的代码 出现几个问题
## 3. Here is a Demo. 

![2018-04-25 5 24 22](https://user-images.githubusercontent.com/20568661/39237259-905b1312-48ad-11e8-8ff2-4ebb8c397036.png)
另外发现在使用了+ (UIImage *)scaleImage:(UIImage *)image toScale:(float)scaleSize;这个方法 我的tabbar顶部会出现线条重叠的问题，看图：
![a8d3025a76f924d866e3e108cb32201a](https://user-images.githubusercontent.com/20568661/39237491-45936d38-48ae-11e8-81ad-20caf9094aa5.jpg) 另外说明:我用不经过+scaleImage:方法处理的原始图片 是不会出现这个问题的 

顶部黑线的问题 ：
    tabBarAppearance.barStyle = UIBarStyleBlack;
用了这个属性自动去除掉了，设置了其他的属性都无法去除；
![6f190185-0623-40c2-b5b6-52b01b88916a](https://user-images.githubusercontent.com/20568661/39237740-e8ff89b6-48ae-11e8-9697-1e3eede60891.png)

**Comment by ChenYilong** [comment]
v1.17.6 顶部黑线已经可以用 `- (void)hideTabBadgeBackgroundSeparator;`移除iPhoneX 上顶部黑线。
scaleImage:toScale:这个方法只是demo 演示，需要自己调节。

**Comment by DemonLover** [comment]
首先，很感谢您能回复我的问题：
+ (UIImage *)scaleImage:(UIImage *)image toScale:(float)scaleSize 它内部是重绘得到新的图片、而这个重绘后的新图片上面多出来一条黑色线条阴影，它并不是TabBar自带的顶部黑线；
后来发现是UIGraphicsBeginImageContext(CGSizeMake(width, height));这句话在作怪、
最后我替换为UIGraphicsBeginImageContextWithOptions(size, NO, 1.0); 顶部重绘得到的黑色线条完美解决了
