### ISSUE TITLE
顶部黑线去除，iPhoneX 上Tabbar显示异常，使用了scaleImage:toScale:方法设置背景图 tabbar顶部出现两条灰色线

### ISSUE THREAD

**Issue by DemonLover** [ChenYilong/CYLTabBarController#273]
## Base Info for this issue 

 1. Version：v1.16.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
v1.17.6 顶部黑线已经可以用 `- (void)hideTabBadgeBackgroundSeparator;`移除iPhoneX 上顶部黑线。
scaleImage:toScale:这个方法只是demo 演示，需要自己调节。
