### ISSUE TITLE
viewController.tabBarItem.selectedImage = selectedImage  无效

### ISSUE THREAD

**Issue by HobaoKing** [ChenYilong/CYLTabBarController#274]
## Base Info for this issue 

        selectedImage = [selectedImage imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal]; 
 最新的版本，这一行被注释掉了， 我这边会导致viewController.tabBarItem.selectedImage = selectedImage 无效。

**Comment by ChenYilong** [comment]
具体是什么问题，请详细描述下。viewController.tabBarItem.selectedImage = selectedImage 中右侧赋值前设置，    selectedImage = [selectedImage imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal]; 

再赋值，这样可以吗？

**Comment by ChenYilong** [comment]
v1.17.8已修复，更新下
