### ISSUE TITLE
怎么修改tabbar的title？

### ISSUE THREAD

**Issue by tanjieaa** [ChenYilong/CYLTabBarController#276]
## Base Info for this issue 

 1. Version：v1.16.0
 2. Language：Objective-C
 4. iOS System Version：iOS10以上
 5. Prototype（是否是真机）：YES
 6. Issue Type：Enhancement（希望能支持一个新需求）、Q-A

## 2. Please help me in this way.

因为我项目是支持多语言版本，当切换其他语言，使用通知更换语言，但是tabbar上的title应该怎么切换呢，我拿到对应tabbar控制器，使用vc.tabBarItem.title更换，但是更换不了

**Comment by yangzheng006** [comment]
怎么完成的？

**Comment by ChenYilong** [comment]
这里给出了详细的方案：https://github.com/ChenYilong/CYLTabBarController/issues/247
