### ISSUE TITLE
iPhone X 上 自定义 badgeView 在push 过程中会出现 tabbar 上下位移的问题

### ISSUE THREAD

**Issue by onceMu** [ChenYilong/CYLTabBarController#277]
## Base Info for this issue 

iPhone X 上自定义badgeView 在push 过程中会出现 tabbar 上下位移的问题
自定义badgeview 继承自UIView，badgeView 里面很简单，就一个Label。
在iPhone x 上，debug 发现CYLTabbar中的layoutsubview 被多次调用，初始化的时候 tabbar的subviews  
uitabbarbutton 对象的 frame 为 frame = (2 1; 90 48);当进行push操作的时候 frame 会变成 frame = (2 1; 90 82)。
这个时候的frame 变化是由于 CYLTabBarController.m 中 - (void)viewDidLayoutSubviews 函数中的  [self.tabBar layoutSubviews] 方法造成的。

**Comment by ChenYilong** [comment]
fixed in v1.17.10
