### ISSUE TITLE
pod 集成报错

### ISSUE THREAD

**Issue by HackRoy** [ChenYilong/CYLTabBarController#279]
[!] CocoaPods could not find compatible versions for pod "CYLTabBarController":
  In snapshot (Podfile.lock):
    CYLTabBarController (= 1.17.10, ~> 1.17.9)

  In Podfile:
    CYLTabBarController (~> 1.17.9)

None of your spec sources contain a spec satisfying the dependencies: `CYLTabBarController (~> 1.17.9), CYLTabBarController (= 1.17.10, ~> 1.17.9)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by ChenYilong** [comment]
use `pod update` to update your  CocoaPods libs
