### ISSUE TITLE
设置选中 Item 的文字颜色无效

### ISSUE THREAD

**Issue by devtofu** [ChenYilong/CYLTabBarController#28]
![58a70d40-3876-455a-80c4-5b27ed4d50db](https://cloud.githubusercontent.com/assets/12134966/12031668/bbb44f3e-ae49-11e5-9fe0-98dea0ab33ef.png)
![700bbf14-cb48-40be-90b4-db51eecb88f2](https://cloud.githubusercontent.com/assets/12134966/12031677/db206132-ae49-11e5-8246-285f13c1eb34.png)

选中之后还是黑色的。 帮忙看下，谢谢！

**Comment by ChenYilong** [comment]
是否是最新版？使用的pods 安装的话，提供下版本号

**Comment by ChenYilong** [comment]
最后一行，改成把 highlighted 改为 selected

**Comment by devtofu** [comment]
是最新版的，直接下载的 zip,   刚才下载修改了下试出来的

**Comment by devtofu** [comment]
诶哟，好蠢，我加过了 selected 就是没把 highlighted 删掉。 可以了

**Comment by devtofu** [comment]
demo 里设置的是  highlighted
