### ISSUE TITLE
PlusButton设置了选中和未选中图片，不生效

### ISSUE THREAD

**Issue by zhongdom** [ChenYilong/CYLTabBarController#280]
## Base Info for this issue 

 1. Version：~> 1.17.11
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 1. How to repeat the problem.

PlusButton不生效设置了选中和未选中图片，点击选中之后并不会切换状态，一直都是显示未选中的图片

**Comment by ChenYilong** [comment]
button的selected状态要自己控制。

**Comment by ChenYilong** [comment]
其他issue讨论过

**Comment by zhongdom** [comment]
我尝试在下面这个方法中更改按钮状态，但是未生效
```
+ (BOOL)shouldSelectPlusChildViewController {
    BOOL isSelected = CYLExternPlusButton.selected;
    if (isSelected) {
        NSLog(@"🔴类名与方法名：%@（在第%@行），描述：%@", @(__PRETTY_FUNCTION__), @(__LINE__), @"PlusButton is selected");
    } else {
        NSLog(@"🔴类名与方法名：%@（在第%@行），描述：%@", @(__PRETTY_FUNCTION__), @(__LINE__), @"PlusButton is not selected");
    }
    return YES;
}

```
改变按钮状态是用`CYLExternPlusButton.selected`这种方式吗？
