### ISSUE TITLE
v(1.17.13)  ios10.3.1 TabbarItem不响应点击事件

### ISSUE THREAD

**Issue by WSFeng** [ChenYilong/CYLTabBarController#284]
1. Version：CYLTabBarController (1.17.13)
 2. Language：Objective-C
 4. iOS System Version：iOS10.3.1
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 1. How to repeat the problem.

在CYLTabBar.m文件中走完这个方法后
- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event
在正确返回点击的tabbar item 后,不做任何tabbar切换响应

**Comment by WSFeng** [comment]
@all 
需要解决方案的同学, 在CYLTabBar 类的方法 - (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event 中编写如下代码, 代码位置大约为387行
.........
..........
 return self.plusButton;
        }
    }
    //TODO:ios10.3.1这个地址是错的 [return selectedTabBarButton], 跟系统方法返回不一致[super hitTest:point withEvent:event]
    if(![self.subviews containsObject:self.tabBarButtonArray.firstObject]) {
        ///如果无需重新布局: 调用下面的语法
        self.tabBarButtonArray = [self tabBarButtonFromTabBarSubviews:[self sortedSubviews]];
        ///如果需要重新布局: 调用下面的语法
        [self layoutSubviews];
    }


NSArray *tabBarButtons = self.tabBarButtonArray;
.........
........

**Comment by WSFeng** [comment]
希望 @ChenYilong  在后续的代码发布中,fix掉这个问题

**Comment by ChenYilong** [comment]
好的，多谢提供方案

**Comment by liweican1992** [comment]
碰到了同样的问题 希望可以修复，多谢~

**Comment by liangxueliang** [comment]
@WSFeng 你的解决方案在 iOS 10.3.3 的 iPhone 5上面不行喔

**Comment by ChenYilong** [comment]
我在1.24.2版本中做了限制，只有(width > 10)的item才会被认为是item，应该已经修复了该问题，请更新确认。

**Comment by ChenYilong** [comment]
#228
