### ISSUE TITLE
我想点击tabbar的某个按钮之后 想直接push到另一个页面，是要破坏代码的封装性么....

### ISSUE THREAD

**Issue by beydeng** [ChenYilong/CYLTabBarController#286]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 4. Here is my Debug log

谢谢

**Comment by ameue** [comment]
@ChenYilong 你好，假设TabBarController有3TabBarItem，当前选中第一个TabBarItem，这个页面中有一个按钮，点击按钮push一个页面，当这个页面返回的时候，TabBarController选中的是第三个TabBarItem，这样可以吗

**Comment by ChenYilong** [comment]
现在的demo已经演示了，你进最新demo，点击鱼塘tab，进cell的二级，然后就有提示。会push到别的tab的二极页面。

**Comment by ChenYilong** [comment]
> @ChenYilong 你好，假设TabBarController有3TabBarItem，当前选中第一个TabBarItem，这个页面中有一个按钮，点击按钮push一个页面，当这个页面点击返回按钮或者用手势返回后，TabBarController已经选中的是第三个TabBarItem，这样可以吗

不需要破坏封装性，我给了API可以实现这个功能。

**Comment by ameue** [comment]
@ChenYilong  感谢回复
demo一种情况是（有plus button）：在第二tab进入二级二级页面后，点击页面才做处理，这个时候手势返回的时候还是选中的第二个tab
第二种情况（没有plus button）：在第二tab进入二级页面后，点击页面，pop-选中另外一个tab-再push一个页面，这种情况，原生的也可以处理。
我想咨询的是，在第二tab进入二级页面后，在这个二级页面点返回，或者是手势返回后，都已经选中另外一个tab。

**Comment by ChenYilong** [comment]
你看下demo实现，这个可以。有popSelect接口。index 传入对应的值

**Comment by ameue** [comment]
@ChenYilong  感谢你的回复
这样是能实现的，原生的tabbar也可以。
可能我的表述不清楚，我的想法是，在TabA --(push)-->A2（a2
是TabB的模块里面的页面）后，没有再次点击页面执行testPush，实际上tabbar已经选中了TabB，在页面上实际看到的效果是，如果在A2使用手势返回后，看到的效果是TabB已经选中

**Comment by ChenYilong** [comment]
有没有对标的app效果，QQ或者微信？这样好理解。

**Comment by ameue** [comment]
那要加个QQ吧：我的QQ号447716634

**Comment by ameue** [comment]
UU加速器，启动APP后，点击‘全部游戏’tab，然后点击页面右上角的‘搜索按钮’，然后点击页面上的‘王者荣耀’，进入下一个页面后，再用手势返回，看到的结果是‘加速’tab选中了。

**Comment by ChenYilong** [comment]
UU Game Booster by NetEase Games https://itunes.apple.com/nz/app/uu-game-booster/id1187805308?mt=8 ？

**Comment by ameue** [comment]
https://itunes.apple.com/cn/app/%E7%BD%91%E6%98%93uu%E5%8A%A0%E9%80%9F%E5%99%A8-%E4%B8%93%E4%B8%9A%E7%9A%84%E6%89%8B%E6%B8%B8%E5%8A%A0%E9%80%9F%E5%B7%A5%E5%85%B7/id1319788668?mt=8

**Comment by ChenYilong** [comment]
在点击王者荣耀按钮时，执行popSelect index的值1，然后再push新页面。这样是否可行。

**Comment by ameue** [comment]
不行，点击返回和手势返回，tabbar消失了
