### ISSUE TITLE
根据文档在AppDelegate中初始化tabbar, 然后通过导航条Push第二个页面时,tabbar不会自动隐藏.

### ISSUE THREAD

**Issue by MQL9011** [ChenYilong/CYLTabBarController#287]
## Base Info for this issue 

 1. Version：v1.16.0
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：NO
 6. Issue Type：Bug

## 1. How to repeat the problem.

 根据文档在AppDelegate中初始化tabbar, 然后通过导航条Push第二个页面时,tabbar不会自动隐藏.
不知道是不是我哪里少了啥设置, 但是看文档,应该是默认Push就会隐藏的.

以下是我在AppDelegate中初始化tabbar的代码
![image](https://user-images.githubusercontent.com/11871158/43810640-75f659ec-9aeb-11e8-9837-96db91425054.png)

![image](https://user-images.githubusercontent.com/11871158/43810628-641a0ba6-9aeb-11e8-893e-d7687ca63ae6.png)

这里是通过导航条push时的代码
![image](https://user-images.githubusercontent.com/11871158/43810648-7ce77538-9aeb-11e8-84b7-234c5be2d5cf.png)

**Comment by MQL9011** [comment]
好吧...原来不是默认设置的, 是需要自己去重写导航条的Push方法,在里头自己设置啊,跟文档中说的不一样啊
![image](https://user-images.githubusercontent.com/11871158/43811218-02884080-9aee-11e8-9ac6-545f292dfaca.png)

**Comment by ChenYilong** [comment]
非默认设置，tabbar隐藏消失需要自己控制。
