### ISSUE TITLE
能不能动态更新图标和标题？

### ISSUE THREAD

**Issue by yangzheng006** [ChenYilong/CYLTabBarController#288]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
![](http://ww1.sinaimg.cn/large/006tNc79ly1g48e1kygwij30u02bo0yx.jpg)
