### ISSUE TITLE
1.17.16 调用update selection status if needed forTabBarController 重大bug

### ISSUE THREAD

**Issue by OrageKK** [ChenYilong/CYLTabBarController#289]
## Base Info for this issue 

 1. Version：v1.17.16
 2. Language：Objective-C
 4. iOS System Version：iOS11.4.1
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

从1.17.4 更新到1.17.16 调用下面的方法
```objective-c
- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController {
   
	[[self cyl_tabBarController] updateSelectionStatusIfNeededForTabBarController:tabBarController shouldSelectViewController:viewController];
    return YES;
    
}
```
这个代理方法会走两次
```objective-c
- (void)tabBarController:(UITabBarController *)tabBarController didSelectControl:(UIControl *)control
```

**Comment by ChenYilong** [comment]
收到，是有这个问题，请问你这个代理方法中会进行什么操作吗？
帮忙贴下你在这里面写的代码，我评估下，预计下个版本能修复。

**Comment by OrageKK** [comment]
> 收到，是有这个问题，请问你这个代理方法中会进行什么操作吗？
> 帮忙贴下你在这里面写的代码，我评估下，预计下个版本能修复。


代理方法中进行了按钮点击的数据埋点和缩放动画。调用两次导致了错乱。
目前我把
```objc
[[self cyl_tabBarController] updateSelectionStatusIfNeededForTabBarController:tabBarController shouldSelectViewController:viewController];
```
注释掉

**Comment by yiwade00** [comment]
注释掉 // [[self cyl_tabBarController] updateSelectionStatusIfNeededForTabBarController:tabBarController shouldSelectViewController:viewController];
下面改下这个
if ([control cyl_isPlusButton]) {
        UIButton *button = CYLExternPlusButton;
        button.selected=YES;
        animationView = button.imageView;
    }else{
        UIButton *button = CYLExternPlusButton;
        button.selected = NO;
    }
作者不知道啥时候更新呢

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/259

**Comment by ChenYilong** [comment]
fix in v1.17.22  
more infomation: https://github.com/ChenYilong/CYLTabBarController/commit/8399c7b7555f926dd2b0434c80667255fbfd0ad1

**Comment by yiwade00** [comment]
1.17.22 咋一直更新不上呢 是我网速慢么 cocoaods  update好像不行呢

**Comment by ChenYilong** [comment]
该问题已经修复，具体用法参考这里： https://github.com/ChenYilong/CYLTabBarController/issues/259

**Comment by OrageKK** [comment]
> 该问题已经修复，具体用法参考这里： #259

👌了解
