### ISSUE TITLE
Swift版的iPad下,倒数第二个TabBarItem不能点击

### ISSUE THREAD

**Issue by 308823810** [ChenYilong/CYLTabBarController#290]
## Base Info for this issue 

 1. Version：v1.17.4
 2. Language：Swift
 4. iOS System Version：iOS11.3
 5. Prototype（是否是真机）：NO,真机应该也有这个问题
 6. Issue Type：Bug

## 1. How to repeat the problem.

Demo中的Swift版本,在iOS11.4下,在iPad运行,倒数第二个"消息"按钮,大概率不能响应点击
![image](https://user-images.githubusercontent.com/15311758/44183151-79e59980-a13c-11e8-9eb3-62783a8feb89.png)

## 2. Please help me in this way.

希望能修复
## 3. Here is a Demo. 
Example-Swift

## 4. Here is my Debug log
无日志信息

**Comment by ChenYilong** [comment]
如#234 所言：在 PlusChildViewController 样式里， 由于在框架内部，错误设置了 plusButton 的宽度，导致CYLPlusButton 越界响应问题，后在1.17.6版本中，绕过，但并未彻底解决，现在在1.17.23版本中彻底解决。望更新重试。
