### ISSUE TITLE
App启动之初的我设置默认选中加号控制器了,怎么设置CYLPlusButtonSubclass变成选中状态

### ISSUE THREAD

**Issue by xhzth7091** [ChenYilong/CYLTabBarController#292]
我设置了CYLPlusButtonSubclass选中状态的文字和图片,我选中了加号控制器以后,CYLPlusButtonSubclass没有变成选中的状态,怎么设置,求教,   我直接用CYLPlusButtonSubclass去设置Selected,不行
<img width="645" alt="e85ac762-9df0-4460-ae17-f6c2a1958348" src="https://user-images.githubusercontent.com/13980546/44441149-c37f2a00-a5fd-11e8-8282-6a4ad5dd69bf.png">

<img width="459" alt="9bdce6ab-3c2d-446c-853a-836fc6f6ce7c" src="https://user-images.githubusercontent.com/13980546/44441343-a26b0900-a5fe-11e8-85b4-09862f7bff32.png">

**Comment by DemonLover** [comment]
可以试试在方法- (void)tabBarController:(UITabBarController *)tabBarController didSelectControl:(UIControl *)control 


 // 即使 PlusButton 也添加了点击事件，点击 PlusButton 后也会触发该代理方法。
    if ([control cyl_isPlusButton]) {
        UIButton *button = CYLExternPlusButton;
        button.selected = YES;
        animationView = button.imageView;
    }else{
        UIButton *button = CYLExternPlusButton;
        button.selected = NO;
    }

**Comment by ChenYilong** [comment]
自定义plusButton中直接设置selected属性即可。

**Comment by ChenYilong** [comment]
本issue最上面第一张图片红色箭头对应的方法建议加一个延时，参照demo里的做法。
