### ISSUE TITLE
shouldSelectViewController   return NO

### ISSUE THREAD

**Issue by chocolatemetoprolol** [ChenYilong/CYLTabBarController#293]
- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController
{
    return NO; 
}

但是 下面这个方法还是会执行

- (void)tabBarController:(UITabBarController *)tabBarController didSelectControl:(UIControl *)control{
   
}

**Comment by ChenYilong** [comment]
fixed in v1.18.0
