### ISSUE TITLE
iPhone X 适配问题，文字和图片重叠

### ISSUE THREAD

**Issue by iOSchuang** [ChenYilong/CYLTabBarController#296]
## Base Info for this issue 

在iPhone X 上，tabbar同时显示图片和文字，图片和文字重叠

 1. Version：v1.16.0
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：模拟器
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

下载的demo在模拟器上运行，当同时显示图片和文字的时候，有重叠。
![image](https://user-images.githubusercontent.com/15044460/44842605-e7371580-ac78-11e8-9d6f-a618c257443c.png)

**Comment by ChenYilong** [comment]
相同问题，集成时设置的
自定义高度有问题。 https://github.com/ChenYilong/CYLTabBarController/issues/309
