### ISSUE TITLE
关于- (void)tabBarController:didSelectControl:被多次调用

### ISSUE THREAD

**Issue by lztbwlkj** [ChenYilong/CYLTabBarController#297]
## Base Info for this issue 

- (void)tabBarController:(UITabBarController *)tabBarController didSelectControl:(UIControl *)control ；有时候会被调用两次，很奇怪！

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by DemonLover** [comment]
这个Bug我修改的方式是: 在原框架中注释掉  [self didSelectControl:nil];这个一行代码 
如果中间自定义按钮出现选择状态的问题 可以手动去管理选中状态：
- (void)tabBarController:(UITabBarController *)tabBarController didSelectControl:(UIControl *)control {
    UIView *animationView；
  if ([control cyl_isTabButton]) {

  }

  if ([control cyl_isPlusButton]) {
        UIButton *button = CYLExternPlusButton;
        button.selected = YES;
        animationView = button.imageView;
     }else{
        UIButton *button = CYLExternPlusButton;
        button.selected = NO;
     }
    [self addScaleAnimationOnView:animationView repeatCount:1];
}

**Comment by zzcshao** [comment]
希望作者能尽快修复下这个bug ~

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/259

**Comment by ChenYilong** [comment]
fix in 1.17.22
more info:
https://github.com/ChenYilong/CYLTabBarController/commit/8399c7b7555f926dd2b0434c80667255fbfd0ad1

**Comment by ChenYilong** [comment]
这个问题已经修复，用法参考：https://github.com/ChenYilong/CYLTabBarController/issues/259
