### ISSUE TITLE
[en]bug appears when use cyl_showTabBadgePoint and cyl_popSelectTabBarChildViewControllerAtIndex at same time [cn]设置红点之后在原tabbar 上出现黑条

### ISSUE THREAD

**Issue by yFeii** [ChenYilong/CYLTabBarController#298]
## Base Info for this issue 

在tabbar=2的列表push->详情。在详情页调 cyl_popSelectTabBarChildViewControllerAtIndex   时出现黑条

 
 1. Version：pod 'CYLTabBarController', '~> 1.17.4'
 2. Language：Objective-C
 4. iOS System Version：iOS11
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug、

## 1. How to repeat the problem.
在tabbar=2的列表push->详情。在详情页调 cyl_popSelectTabBarChildViewControllerAtIndex   时出现黑条
图在这
[https://i.loli.net/2018/09/05/5b8f61e63eff7.png](url)

**Comment by ChenYilong** [comment]
我复现了：
![emassuite02](https://user-images.githubusercontent.com/2911921/53501677-926d3e00-3ae7-11e9-86f1-03f7cdb6fff2.gif)

**Comment by ChenYilong** [comment]
v1.19.0更改小红点实现方式，解决了该问题，并增加多个API自定义红点UI样式、动画效果。请更新重试。

**Comment by yFeii** [comment]
好的
