### ISSUE TITLE
第一次用,浪费老子一下午..发现是版本更新了,导致中间那个按钮出来,作者,每个人都不一定按照你那种创建方式啊..服气

### ISSUE THREAD

**Issue by whyAreYouSoShy** [ChenYilong/CYLTabBarController#299]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
题目没看懂，帮忙详细描述下，给你造成困扰，深表歉意。

**Comment by ChenYilong** [comment]
参考这个issue：https://github.com/ChenYilong/CYLTabBarController/issues/248
