### ISSUE TITLE
按钮响应区域问题

### ISSUE THREAD

**Issue by StanOz** [ChenYilong/CYLTabBarController#3]
我把 demo 两侧的 item 各去掉一个后，按钮的响应区域就变成下图的样子了：
![wechat_1445851872](https://cloud.githubusercontent.com/assets/12152553/10725491/62600172-7c07-11e5-9e0a-0ec7d795d1e3.jpeg)

**Comment by ChenYilong** [comment]
这个是iOS系统对tabbar做的优化，请在真机上进行右手体验。如果你将iPhone切换到左手模式，触摸区域将“反过来”，有兴趣可以试一下。

**Comment by StanOz** [comment]
感谢解答。
