### ISSUE TITLE
抽屉效果？

### ISSUE THREAD

**Issue by CoderSimonWong** [ChenYilong/CYLTabBarController#300]
CYLTabBarController 有没有提供 Airbnb-app 这个app的抽屉效果？

**Comment by ChenYilong** [comment]
暂未提供，欢迎提PR，
不过我的这个demo里有涉及抽屉效果，但没涉及  CYLTabBarController
https://github.com/ChenYilong/CollectionViewClassifyMenu

**Comment by CoderSimonWong** [comment]
OK，谢谢解答。
