### ISSUE TITLE
使用此框架时，我自己自定义的导航条背景图怎么设置不成功能

### ISSUE THREAD

**Issue by xjryuanmeng** [ChenYilong/CYLTabBarController#301]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
本库，不会影响navBar的设置，请检查设置方式，或者把设置方式贴以下。
