### ISSUE TITLE
新出iphoneXS之后，判断刘海屏问题

### ISSUE THREAD

**Issue by Jubian** [ChenYilong/CYLTabBarController#302]
项目中CYL_IS_IPHONE_X，判断刘海屏还是通过屏幕尺寸来判断的

现在新出了iphoneXS之后，刘海屏已经不能简单通过屏幕尺寸判断了，希望可以通过别的方法来判断刘海屏，比如手机型号，希望作者能尽快更新，不影响IPhoneXs之后的适配问题

**Comment by KangYJie** [comment]
用statusbar判断  
Device_Is_iPhoneX  
（[[UIApplication sharedApplication] statusBarFrame].size.height>20?:NO）

**Comment by ChenYilong** [comment]
v1.17.7 support iPhone XS Max

**Comment by janicezhw** [comment]
> 用statusbar判断
> Device_Is_iPhoneX
> （[[UIApplication sharedApplication] statusBarFrame].size.height>20 ? YES : NO）

这种判断在横屏情况，是错误的。
