### ISSUE TITLE
点击TabBar，tabBarController:didSelectControl:方法会调用两次

### ISSUE THREAD

**Issue by gongsunqingyang** [ChenYilong/CYLTabBarController#305]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
fixed：https://github.com/ChenYilong/CYLTabBarController/issues/297
