### ISSUE TITLE
触摸范围问题

### ISSUE THREAD

**Issue by mazhengji123** [ChenYilong/CYLTabBarController#306]
## Base Info for this issue 

 1. Version：v1.17.17
 2. Language：Objective-C
 4. iOS System Version：iOS12
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 1. How to repeat the problem.
只有两个item时开启plusChildViewController 并且中间button不使用title 最右边item触摸范围很小

## 3. Here is a Demo. 

已发送邮箱 发件人mazhengji123@gmail.com

**Comment by ChenYilong** [comment]
v1.17.20 已经优化，请更新，重试

**Comment by mazhengji123** [comment]
CYLTabBarController-master 3.zip
<https://drive.google.com/file/d/1_b_w5ry8HlmUVbTNy5Omt1J3S4FnLlNx/view?usp=drive_web>
感谢回复 现在发现了一个新问题 有两个item且plusbutton在中间时两个item与两个边界的距离不相同

微博@iOS程序犭袁 <notifications@github.com> 于2018年10月30日周二 下午4:01写道：
