### ISSUE TITLE
iOS 12.1 beta版 Tabbar点击跳转时item出现错位问题

### ISSUE THREAD

**Issue by BruceYoungHaha** [ChenYilong/CYLTabBarController#307]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.
iOS 12.1 beta版 Tabbar点击跳转时item出现错位，文字消失，图标及小圆点出现偏移。

**Comment by Samuel0807** [comment]
I also find this.
