### ISSUE TITLE
iOS 12.1 beta版 pop返回时，item出现错位，文字消失，图标及小圆点出现位置偏移

### ISSUE THREAD

**Issue by BruceYoungHaha** [ChenYilong/CYLTabBarController#308]
## Base Info for this issue 

 1. Version：v1.17.17
 2. Language：Objective-C
 4. iOS System Version：iOS12.1 Beta
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.
iOS 12.1 beta版 pop返回时，item出现错位，文字消失，图标及小圆点出现位置偏移

**Comment by xiangshun110** [comment]
same question

**Comment by ChenYilong** [comment]
已经修复，见 ：https://github.com/ChenYilong/CYLTabBarController/issues/312
