### ISSUE TITLE
X系列 tabbar 位置错乱

### ISSUE THREAD

**Issue by Kim66666** [ChenYilong/CYLTabBarController#309]
X系列 tabbar 位置错乱
![image](https://user-images.githubusercontent.com/23734281/46724713-35462c80-ccad-11e8-8fdf-eda95459307d.png)

**Comment by ChenYilong** [comment]
这个是你设置了自定义高度，建议根据机型设置不同高度，或者使用系统默认高度。

**Comment by ChenYilong** [comment]
这里有更详细的讨论，建议升级到1.17.21重试 https://github.com/ChenYilong/CYLTabBarController/issues/312

**Comment by ChenYilong** [comment]
iPhoneX 适配也可以参考： https://github.com/ChenYilong/CYLTabBarController/issues/324
