### ISSUE TITLE
您好，请问是否支持自定义TabBar？

### ISSUE THREAD

**Issue by LYluyu** [ChenYilong/CYLTabBarController#311]
## Base Info for this issue 

您好，请问是否支持自定义TabBar？

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
文档中给出了，自定义的流程。是有文档里，以外的自定义需求吗？可以描述下需求
