### ISSUE TITLE
iOS12.1 popViewControllerAnimated，UINavigationController返回时，item出现错位，文字消失，图标及小圆点出现位置偏移。过1-2秒才恢复到正常位置

### ISSUE THREAD

**Issue by xhzth7091** [ChenYilong/CYLTabBarController#312]
## Base Info for this issue 

Xcode Version：v9.4.1
 1. Version：v1.17.13
 2. Language：Objective-C
 4. iOS System Version：iOS12.1 beta 3
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

UINavigationController popViewControllerAnimated的时候，item出现错位，文字消失，图标及小圆点出现位置偏移。过1-2秒才恢复到正常位置,我试了一下你最新的版本v1.17.17和v1.2.5，也都存在这个问题，只有中间的加号不会改变位置

**Comment by RockXeng** [comment]
+1,求解

**Comment by YaoJuan** [comment]
我也遇到了同样的情况

**Comment by ChenYilong** [comment]
今天看下

**Comment by xhzth7091** [comment]
> 今天看下
用你的CYLTabBarController哪个版本？

**Comment by xhzth7091** [comment]
> 今天看下
我试了一下，重新再下载了一份版本v1.17.17和v1.17.13的，popViewControllerAnimated时候，item还是会出现错位，文字消失，图标及小圆点出现位置偏移。用的是真机iPhone6s，iOS12.1 beta 3。

**Comment by RockXeng** [comment]
@ChenYilong 这个问题解决了吗？

**Comment by LoneyLi** [comment]
我也遇到同样的问题

**Comment by ChenYilong** [comment]
今天在看了，尽量今明两天发一版本

**Comment by miniLV** [comment]
+1,和这个库应该没什么关系，用系统UINavigationController + UITabBarController 一样会遇到这个问题
```
- (void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated{
    
    if (self.childViewControllers.count > 0) {
        //如果没这行代码，是正常显示的
        viewController.hidesBottomBarWhenPushed = YES;
    }
    
    [super pushViewController:viewController animated:animated];
}
```

**Comment by ChenYilong** [comment]
【change log】CYLTabBarController v1.17.20 修复了iOS12.1 bate版本中遇到的问题。问题描述：设置hidesBottomBarWhenPushed后，pop到上个页面，会出现 tabBar 布局错乱的问题。 用系统UINavigationController + UITabBarController 一样会遇到这个问题，目前已经在CYLTabBarController新版本中绕过。库的使用方法不变，只需要更新库即可。

相关代码修改：https://github.com/ChenYilong/CYLTabBarController/commit/2c741c8bffd47763ad2fca198202946a2a63c4fc

更多change log见：https://github.com/ChenYilong/CYLTabBarController/releases

**Comment by RockXeng** [comment]
为何更新不到1.17.20？ 我用pods更新到的版本是1.17.17。求解

**Comment by eric1202** [comment]
> 为何更新不到1.17.20？ 我用pods更新到的版本是1.17.17。求解

pod repo update
我刚才从1.17.14 升级到了 1.17.20 可以的

**Comment by ChenYilong** [comment]
v1.17.21 已经发布：

change log：

 -  [work-arounds]compatible for iPhoneX for issue #312
 -  work-arounds 方案，解决 iOS12.1上，iPhoneX 位置跳动的问题。

相关提交见：https://github.com/ChenYilong/CYLTabBarController/commit/2ec965962b70b3c282406265b572bf10af8bb648

**Comment by shuai214** [comment]
[[UITabBar appearance] setTranslucent:NO];

**Comment by VisualEcho** [comment]
> [[UITabBar appearance] setTranslucent:NO];

我今天也碰到了，搞了半天，也是这么搞定的。不过看其他地方也有说改frame也可以解决，我没有试过

**Comment by ChenYilong** [comment]
iPhoneX 适配也可以参考： #324

**Comment by ChenYilong** [comment]
Apple在 iOS12.1.1已经修复该问题，v1.17.23版本进行版本判断，仅仅在iOS12.1与iOS12.1.1之间才进行hook处理。其他版本与系统版本保持一致。

**Comment by lyleLH** [comment]
> [[UITabBar appearance] setTranslucent:NO];

it works for me，thanks

**Comment by ChenYilong** [comment]
系统尽在少数的系统版本中出现该bug,后续更新iOS已经修复,并且该bug可以在初始化时绕过,初始化时绕过的方案成本较低,于是本库已将内置修复系统bug的代码删除.请使用初始化方案绕过.

**Comment by ZD19920819** [comment]
使用[[UITabBar appearance] setTranslucent:NO]; 会造成其他第三方存在一些问题

**Comment by Liyongcong** [comment]
你好想问下这个问题应该怎么处理
