### ISSUE TITLE
iPhone XR，XS Max适配

### ISSUE THREAD

**Issue by nanshanyi** [ChenYilong/CYLTabBarController#313]
## Base Info for this issue 

 1. Version：v1.17.17
 2. Language：Objective-C
 4. iOS System Version：iOS12
 5. Prototype（是否是真机）：NO

模拟器XR，XS Max跑，tabbar的文字和图片重叠。这个是真机显示才正常么？

**Comment by ChenYilong** [comment]
新版本再测试下。

**Comment by crespoxiao** [comment]
@ChenYilong 貌似 1.17.20 没有解决 xr tabbar 的这问题，关键是模拟器上看起来正常。
