### ISSUE TITLE
创建新项目调用tabBarControllerWithViewControllers直接崩溃

### ISSUE THREAD

**Issue by OliverLance** [ChenYilong/CYLTabBarController#316]
## Base Info for this issue 

+ (instancetype)tabBarControllerWithViewControllers:(NSArray<UIViewController *> *)viewControllers
                              tabBarItemsAttributes:(NSArray<NSDictionary *> *)tabBarItemsAttributes
                                        imageInsets:(UIEdgeInsets)imageInsets
                            titlePositionAdjustment:(UIOffset)titlePositionAdjustment
                                            context:(NSString *)context

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by OliverLance** [comment]
但是你的demo是可以运行

**Comment by ChenYilong** [comment]
集成的方式、crash日志贴下

**Comment by OliverLance** [comment]
1、使用Pods方式集成
2、日志如下

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f90c29b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010e178735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f8568fc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010f97b5a1 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x000000010f907d7b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   OLBaseProject                       0x000000010c0e4d8b -[CYLTabBarControllerConfig tabBarItemsAttributesForController] + 187
	6   OLBaseProject                       0x000000010c0e48c4 -[CYLTabBarControllerConfig tabBarController] + 164
	7   OLBaseProject                       0x000000010c0ec152 -[AppDelegate application:didFinishLaunchingWithOptions:] + 546
	8   UIKitCore                           0x00000001160244d7 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 280
	9   UIKitCore                           0x0000000116025ec4 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3979
	10  UIKitCore                           0x000000011602b527 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1623
	11  UIKitCore                           0x00000001168cde3e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 866
	12  UIKitCore                           0x00000001168ca403 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	13  UIKitCore                           0x00000001168cda7b -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 233
	14  UIKitCore                           0x00000001168ce435 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1085
	15  UIKitCore                           0x000000011688bb31 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 795
	16  UIKitCore                           0x000000011688b7db -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 435
	17  UIKitCore                           0x00000001168d092c __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 584
	18  UIKitCore                           0x00000001168d1256 _performActionsWithDelayForTransitionContext + 100
	19  UIKitCore                           0x00000001168d068b -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 221
	20  UIKitCore                           0x00000001168c9aa1 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	21  UIKitCore                           0x0000000116029d46 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 515
	22  UIKitCore                           0x000000011605b856 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 357
	23  FrontBoardServices                  0x0000000119376dda -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
	24  FrontBoardServices                  0x0000000119381f43 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 271
	25  FrontBoardServices                  0x000000011938163a __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 53
	26  libdispatch.dylib                   0x00000001107e363e _dispatch_client_callout + 8
	27  libdispatch.dylib                   0x00000001107e6bb4 _dispatch_block_invoke_direct + 301
	28  FrontBoardServices                  0x00000001193b63c8 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	29  FrontBoardServices                  0x00000001193b6080 -[FBSSerialQueue _performNext] + 457
	30  FrontBoardServices                  0x00000001193b6660 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	31  CoreFoundation                      0x000000010f86fb31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	32  CoreFoundation                      0x000000010f86f3a3 __CFRunLoopDoSources0 + 243
	33  CoreFoundation                      0x000000010f869a4f __CFRunLoopRun + 1263
	34  CoreFoundation                      0x000000010f869221 CFRunLoopRunSpecific + 625
	35  GraphicsServices                    0x0000000112d011dd GSEventRunModal + 62
	36  UIKitCore                           0x000000011602d115 UIApplicationMain + 140
	37  OLBaseProject                       0x000000010c0efde0 main + 112
	38  libdyld.dylib                       0x0000000110859551 start + 1
