### ISSUE TITLE
遇到一个PlusButton会莫名消失的bug，提供一下出现的流程。

### ISSUE THREAD

**Issue by wuyueyang** [ChenYilong/CYLTabBarController#318]
## Base Info for this issue 

 1. Version：v1.16.1
 2. Language：Objective-C
 4. iOS System Version：iOS12
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug、Q-A

## 1. How to repeat the problem.

前提，之前一直用1.16.1版本，PlusButton并没有出现问题。

就在刚才，我想测试一下在 iPhone XS Max 上PlusButton显示是否正常。

1. 先在真机上运行了一下（iOS 12.0，IPhone 5s），PlusButton显示正常。

2. 换 iPhone XS Max 的模拟器 运行，PlusButton显示正常。

3. 看到作者更新了1.17.20，用pod更新了一下第三方库。然后运行，正常。

4. 调整 PlusButton 的位置，添加了如下代码，显示正常

```objc
+ (CGFloat)constantOfPlusButtonCenterYOffsetForTabBarHeight:(CGFloat)tabBarHeight {
    // 如果是X系列手机, plus按钮要网上偏移一点
    if ([OverallControl isX]) {
        
        return -15;
    }
    return 0;
}
```

5. 使用 iPhone 8 Plus 模拟器 运行，PlusButton 消失。

6. 换 iPhone XS Max 的模拟器 运行，PlusButton 消失。

7. 怀疑库有问题，回滚到1.16.1，用 iPhone 8 Plus 模拟器 运行，PlusButton 消失。

8. 真机运行了（iOS 12.0，IPhone 5s），PlusButton显示正常。

9. 用 iPhone 8 Plus 模拟器 运行，PlusButton 显示正常。

10. 换 iPhone XS Max 的模拟器 运行，PlusButton显示正常。

**Comment by LoneyLi** [comment]
遇到过同样的问题

**Comment by LoneyLi** [comment]
@ChenYilong 我的出现这种情况的流程是 ：用户退出登录后我会把登录页面设置为根试图 ，登录成功，重新把CYLTabBarController 设置为根试图，这个时候就可能出现plusButton消失的情况

**Comment by ChenYilong** [comment]
发个demo来

**Comment by wuyueyang** [comment]
> @ChenYilong 我的出现这种情况的流程是 ：用户退出登录后我会把登录页面设置为根试图 ，登录成功，重新把CYLTabBarController 设置为根试图，这个时候就可能出现plusButton消失的情况

哦对，我也是切换 window 的根视图的登录逻辑，有可能是这个原因

**Comment by ChenYilong** [comment]
每次初始化CYLTabBarController，PlusButton都要重新注册。这是一个功能，方便根据需求将plusButton移除。
