### ISSUE TITLE
 iPhone 5真机 iOS 10.3.3 系统 tabbarItem 响应范围小，很难点击

### ISSUE THREAD

**Issue by liangxueliang** [ChenYilong/CYLTabBarController#319]
## Base Info for this issue 

 1. Version：v1.17.20
 2. Language：Objective-C
 4. iOS System Version：iOS 10.3.3
 5. Prototype（是否是真机）：YES
 6. Issue Type：Q-A

## 1. How to repeat the problem.

iPhone 5 tabbarItem 响应范围很小，很偏，很难点击
## 2. Please help me in this way.

在同样的手机上运行 demo 是没问题的，我想知道出现这个问题的原因以及如何解决

**Comment by ChenYilong** [comment]
其它系统没问题吗？

**Comment by liangxueliang** [comment]
是的，我目前就在 iPhone 5 上面遇到，而我这部 iPhone 5 是 10.3.3 系统的。在其他手机和系统上面都没问题


| |
梁学良
|
|
邮箱：liang_xueliang@126.com
|

签名由 网易邮箱大师 定制

在2018年10月30日 18:07，微博@iOS程序犭袁 写道：

其它系统没问题吗？

**Comment by liangxueliang** [comment]
我在模拟器上面也试了一下，iPhone 5 模拟器的版本是 10.3.1 的，也有这个问题。然后要点击途中黑色涂鸦附近的位置才可以选中
![img_0092](https://user-images.githubusercontent.com/13880601/47764565-b6b73a80-dd00-11e8-867f-7d5121b09d60.PNG)

**Comment by ChenYilong** [comment]
设置下item的背景色，或者看下层级，看下背景的frame有多大。

**Comment by liangxueliang** [comment]
看过了，frame 看起来是没有问题的
![1541057910653](https://user-images.githubusercontent.com/13880601/47839050-41c12f00-ddec-11e8-8cb9-5a1861b5770f.jpg)

**Comment by wangjin007** [comment]
系统 10.3.1  iPhone5SE  下面点击是响应  很难点击

**Comment by hccgk** [comment]
推荐参考https://github.com/ChenYilong/CYLTabBarController/issues/284

**Comment by ChenYilong** [comment]
推荐参考#284，已经修复，请更新。
