### ISSUE TITLE
一次App生命周期内,创建两次Tabbar后,第二次的TabBar背景色,按钮颜色都不正确

### ISSUE THREAD

**Issue by CHNLiPeng** [ChenYilong/CYLTabBarController#32]
因为有设计到用户退出登陆后,要再次创建Tabbar的需求。
希望解决。。。十分感谢，

**Comment by ChenYilong** [comment]
详细描述下，没听太懂

**Comment by CHNLiPeng** [comment]
```
CYLTabBarControllerConfig *config = [[CYLTabBarControllerConfig alloc ] init];
    self.tabBarController `=config.tabBarController;`
self.window.rootViewController = self.tabBarController;
```
我的App可以登陆和退出登陆,
第一次登陆的时候，第一次执行了上面的代码。
当我退出登陆后，切换账号再重新登陆的时候,就会第二次执行以上代码，
这时候创建出来的TabbarController，下面的栏，颜色不对。

**Comment by ChenYilong** [comment]
你是说，当你第二次调用时，上面的代码导致了你的tabbar颜色不一致。如果真是这样，这个是bug了吧。

**Comment by devtofu** [comment]
我也是同样的问题，暂时的解决办法是只调用了一次 alloc

**Comment by ChenYilong** [comment]
@devtofu 帮忙把你遇到的问题，还有解决方法详细说下吧最好贴下代码，我定位下问题

**Comment by CHNLiPeng** [comment]
请问此问题有找出原因吗？衷心感谢

**Comment by ChenYilong** [comment]
@CHNLiPeng  能不能贴一些代码，让我知道你怎么用的。贴一些图，然我看下bug 的效果。

**Comment by devtofu** [comment]
@ChenYilong 才看到，等下我抽出 demo 传上来。

**Comment by ChenYilong** [comment]
@devtofu 坐等，有了 Demo，马上就能修好。

**Comment by CHNLiPeng** [comment]
请问@devtofu有上传demo吗？如果他没上传，我就发一份demo给你。

**Comment by ChenYilong** [comment]
@CHNLiPeng 
没有，我一个 Demo 都没收到。。坐等。。。😂

**Comment by CHNLiPeng** [comment]
已经发送了Demo给你了，出现问题的位置也标注好了

**Comment by devtofu** [comment]
@ChenYilong 咋发 demo, 项目忙一直没看 git ..  😂 刚才撸好了一个

**Comment by devtofu** [comment]
[TTTabbarDemo.zip](https://github.com/ChenYilong/CYLTabBarController/files/152279/TTTabbarDemo.zip)

我用 #warning 在 AppDelegate+TTLogin 里标注出来了。。

**Comment by ChenYilong** [comment]
ok

**Comment by CHNLiPeng** [comment]
我的发到你的邮箱去了。。。

**Comment by devjia** [comment]
同样的问题,有暂时的修复方法么

**Comment by devjia** [comment]
暂时解决方法:
修改CYLTabBar.m
`- (instancetype)sharedInit {
    if (CYLExternPlusButton) {
        self.plusButton = CYLExternPlusButton;
        [self addSubview:(UIButton *)self.plusButton];
    }
    //[self setBackgroundImage:[self imageWithColor:[UIColor whiteColor]]];
    return self;
}`

**Comment by ChenYilong** [comment]
@devjia  @CHNLiPeng @devtofu  已经修复  pod更新至1.2.2 ，请确认下是否修复了该问题。https://github.com/ChenYilong/CYLTabBarController/commit/aa6dcbb70b1ab42a4f87e244b9cc9c48d1c22d49

**Comment by devjia** [comment]
非常感谢!
我这边已经测试正常了.
