### ISSUE TITLE
iOS12.1 tabbar 每次出现icon会跳一下, 之前没有

### ISSUE THREAD

**Issue by xiaohange** [ChenYilong/CYLTabBarController#320]

**Comment by lztbwlkj** [comment]
我也碰到了

**Comment by xiaohange** [comment]
@lztbwlkj 貌似升级到1.17.20 解决了这个问题, 你试试

**Comment by ChenYilong** [comment]
新版修复了，1.17.20版本，你看下issue里，有讨论过

**Comment by xiaohange** [comment]
@ChenYilong 谢谢!

**Comment by lztbwlkj** [comment]
我的在pod的时候就不动了
![2018-11-01 4 42 49](https://user-images.githubusercontent.com/20568661/47841733-90bf9200-ddf5-11e8-814b-db7cff671776.png)

**Comment by ChenYilong** [comment]
见讨论：https://github.com/ChenYilong/CYLTabBarController/issues/312

**Comment by ChenYilong** [comment]
Apple已修复，本仓库代码已经限制特定版本下处理该bug。

**Comment by xiaohange** [comment]
@ChenYilong 谢谢, 去年出现这个问题的时候 升级到1.17.20 解决了, 万分感谢!
