### ISSUE TITLE
iPhone X系列不规则tabbar,设置backgroundImage不正确

### ISSUE THREAD

**Issue by Karthus1110** [ChenYilong/CYLTabBarController#321]
代码基本按照demo写的，图片没有延长而是只显示在了tabbar的范围内，该如何解决

![image](https://user-images.githubusercontent.com/13864988/47949684-71a23b00-df82-11e8-9294-e5bd1017baf9.png)

**Comment by Karthus1110** [comment]
@ @ChenYilong

**Comment by tanjieaa** [comment]
我也出现这个，iPhone X和iPhone XS没问题，iPhone XR和iPhone XS Max就是这样

**Comment by tanjieaa** [comment]
看了前面问题作者说的，确实是自定义高度产生的，去掉，使用系统默认的就可以了

**Comment by Karthus1110** [comment]
@tanjieaa 那你的tabbar没有拉伸问题吗？ 图片拉伸变形了 才能适配高度，切了iPhone X的图 也没用

**Comment by Karthus1110** [comment]
OK 我已经解决了、
`+ (UIImage *)scaleImage:(UIImage *)image toScale:(float)scaleSize {
    image = [image resizableImageWithCapInsets:(UIEdgeInsets){30, 10, 10, 10} resizingMode:UIImageResizingModeStretch];
    CGFloat width = [UIScreen mainScreen].bounds.size.width;
    CGFloat height = (kIsIphoneX ? kTabbarHeight + 27: kTabbarHeight + 18);
    UIGraphicsBeginImageContext(CGSizeMake(width, height));
    [image drawInRect:CGRectMake(0, 0, width,height)];
    
    UIImage *scaledImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return scaledImage;
}
`
