### ISSUE TITLE
iphonex 适配问题

### ISSUE THREAD

**Issue by Rcrosp** [ChenYilong/CYLTabBarController#324]
## Base Info for this issue 

 1. Version：v1.13.20
 2. Language：Objective-C
 4. iOS System Version：iOS12
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

进入显示布局图片和标题间距大
## 2. Please help me in this way.

正常显示

**Comment by ChenYilong** [comment]
iPhoneX上的问题，最新版本已经做了兼容，见讨论 https://github.com/ChenYilong/CYLTabBarController/issues/312

**Comment by xxalan** [comment]
用了最新的1.17.21，依旧没有解决 iphone x的适配问题，怎么破？

**Comment by xxalan** [comment]
![simulator screen shot - iphone x - 2018-11-09 at 19 56 25](https://user-images.githubusercontent.com/16459072/48261321-a0745180-e459-11e8-8509-fbf091858dac.png)

**Comment by ChenYilong** [comment]
是不是自定义了高度。加我微信

**Comment by lenvonsam** [comment]
如何解决的
@xxalan

**Comment by EasonYin** [comment]
不自定义tabbar高度就行了
