### ISSUE TITLE
- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController 无法调用

### ISSUE THREAD

**Issue by miniLV** [ChenYilong/CYLTabBarController#326]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 2. Please help me in this way.

Demo中 - `"MainTabBarController.h"`文件要在哪里设置 - `UITabBarControllerDelegate`，
在viewDidLoad 设置`self.delegate = self`不生效

```
- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController {
    不会执行
}
```

**Comment by miniLV** [comment]
在Demo中，要在哪里设置 UITabBarControllerDelegate 才会使得代理方法生效，很急需要help~

**Comment by Alienchang** [comment]
我也遇到这个问题，怎么解决的？-=-

**Comment by alkayoun** [comment]
楼主解决了吗,同样问题

**Comment by ChenYilong** [comment]
1.23.X已经解决，更新重试下。

**Comment by ChenYilong** [comment]
更新 demo 修复二次初始化，不走代理方法不走代理方法的问题，

详情见： 
 - https://github.com/ChenYilong/CYLTabBarController/commit/91f6de1af523f096d6ccc2b8a5accbc04b31f850

 - https://github.com/ChenYilong/CYLTabBarController/issues/161

**Comment by haofanning** [comment]
同样的问题，怎么解决的？
