### ISSUE TITLE
中间凸起按钮的Y坐标无法调整

### ISSUE THREAD

**Issue by peterios2016** [ChenYilong/CYLTabBarController#327]
## Base Info for this issue 

 1. Version：v1.17.21
 2. Language：Objective-C
 4. iOS System Version：iOS12
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

中间有个plusButton，设置了它的frame后发现无法调整Y坐标，只能改大小。能否增加一个对应的api去调整呢

**Comment by ChenYilong** [comment]
API已经有了，参考文档 https://github.com/ChenYilong/CYLTabBarController#%E7%AC%AC%E5%9B%9B%E6%AD%A5%E5%8F%AF%E9%80%89%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84%E5%BD%A2%E7%8A%B6%E4%B8%8D%E8%A7%84%E5%88%99%E5%8A%A0%E5%8F%B7%E6%8C%89%E9%92%AE
