### ISSUE TITLE
好像不支持从沙盒文件中读取图片啊？

### ISSUE THREAD

**Issue by gongshouhui** [ChenYilong/CYLTabBarController#329]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by gongshouhui** [comment]
提供一个初始化方法可以直接使用UIImaged对象就好了，我的需求是可以下载压缩包换皮肤

**Comment by gongshouhui** [comment]
不好意思，仔细看了下是支持UIimage初始化的，瞬间好感倍增了

**Comment by ChenYilong** [comment]
图片名，图片对象两种都可以
