### ISSUE TITLE
如何动态更改tabbar的图标选中和正常状态的颜色？ 系统的可以通过[[UITabbar appearce] setTintColor:xxx] & tabbarItem.selectedImage = [UIImage imagenamed:xxx] imagerenderingmode:xxxtemplate] 来实现

### ISSUE THREAD

**Issue by 304164084** [ChenYilong/CYLTabBarController#331]
在系统原生的tabbar中可以通过 设置两种状态的图标为 template模式。 再通过 [uitabbar appreace] settintcolor:xx  或者是unselectedtintcolor:xx  。来设置两种状态的图标渲染颜色。
但是在您的库中， 我又看到settintcolor:这个 API 但是我调用却无效果。 
然后我又想通过类似系统的设置方法来设置两种状态的图标。进行调用系统的方法来实现。 但是发现您这未提供类似系统的设置图标的API。

最后想问 使用您的库, 如何实现该功能？

期待一龙大神的回复！
下面是我使用系统的UITabBarController实现的简单效果
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    
    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    ViewController *vc1 = [[ViewController alloc] init];
    ViewController *vc2 = [[ViewController alloc] init];
    UITabBarController *tvc = [[UITabBarController alloc] init];
    [tvc setViewControllers:@[vc1, vc2]];
    
    [tvc.tabBar.items enumerateObjectsUsingBlock:^(UITabBarItem * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
        NSString *title = [NSString stringWithFormat:@"vc->%ld", idx];
        UIImage *selectedImage = [[UIImage imageNamed:@"tabbar_cate_highlight"] imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
        UIImage *normalImage = [[UIImage imageNamed:@"tabbar_cate"] imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
        
        obj.title = title;
        obj.image = normalImage;
        obj.selectedImage = selectedImage;
    }];
    
    [[UITabBar appearance] setTintColor:[UIColor redColor]];
    [[UITabBar appearance] setUnselectedItemTintColor:[UIColor yellowColor]];
    
    self.window.rootViewController = tvc;
    
    [self.window makeKeyAndVisible];
    return YES;
}`

**Comment by ChenYilong** [comment]
关于tintColor设置：

我是这么设定的：


 ```Objective-C
//  CYLTabBarController.m
- (UIImage *)getImageFromImageInfo:(id)imageInfo {
    UIImage *image = nil;
    if ([imageInfo isKindOfClass:[NSString class]]) {
        image = [UIImage imageNamed:imageInfo];
        image = [image imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
    } else if ([imageInfo isKindOfClass:[UIImage class]]) {
        image = (UIImage *)imageInfo;
    }
    return image;
}
 ```

所以如果你是以字符串形式引用的图片资源，会主动给使用图片原色，
如果是UIImage引用的图片资源，则tintColor属性会生效。

**Comment by ChenYilong** [comment]
参考方案：https://github.com/ChenYilong/CYLTabBarController/issues/303

**Comment by Abnerzj** [comment]
> 关于tintColor设置：
> 
> 我是这么设定的：
> 
> ```objc
> //  CYLTabBarController.m
> - (UIImage *)getImageFromImageInfo:(id)imageInfo {
>    UIImage *image = nil;
>    if ([imageInfo isKindOfClass:[NSString class]]) {
>        image = [UIImage imageNamed:imageInfo];
>        image = [image imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
>    } else if ([imageInfo isKindOfClass:[UIImage class]]) {
>        image = (UIImage *)imageInfo;
>    }
>    return image;
> }
> ```
> 
> 所以如果你是以字符串形式引用的图片资源，会主动给使用图片原色， 如果是UIImage引用的图片资源，则tintColor属性会生效。

我的需求是选中图片不用根据tintColor渲染，有自己的选中图片，getImageFromImageInfo方法中，imageInfo参数赋值的是UIImage，但是一直会被tintColor影响，如果需要不被影响，imageInfo参数为UIImage时，也需要设置渲染模式为UIImageRenderingModeAlwaysOriginal。
- (UIImage *)getImageFromImageInfo:(id)imageInfo {
   UIImage *image = nil;
   if ([imageInfo isKindOfClass:[NSString class]]) {
       image = [UIImage imageNamed:imageInfo];
       image = [image imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
   } else if ([imageInfo isKindOfClass:[UIImage class]]) {
       image = (UIImage *)imageInfo;
   }
   return image;
}
