### ISSUE TITLE
角标加上之后 无法消失的问题

### ISSUE THREAD

**Issue by beydeng** [ChenYilong/CYLTabBarController#332]
角标加上之后，无法消失角标，是什么原因导致的啊

**Comment by beydeng** [comment]
当我在一个控制器里面 
    if ([self cyl_isShowTabBadgePoint]) {
        
        [self cyl_removeTabBadgePoint];
        
    }
添加如上方法的时候，角标无法消失

**Comment by ChenYilong** [comment]
内部实现如下：

 ```Objective-C
- (void)cyl_removeTabBadgePoint {
    if (self.cyl_isPlusChildViewController) {
        return;
    }
    [self.cyl_tabButton cyl_removeTabBadgePoint];
    [[[self cyl_getViewControllerInsteadOfNavigationController] cyl_tabBarController].tabBar layoutIfNeeded];
}
 ```
请检查TabBarVC的Child是否是 natigationController，如果是的话，建议用[self.natigationController cyl_removeTabBadgePoint];
