### ISSUE TITLE
大神，问一下可以调整小红点角标的位置吗

### ISSUE THREAD

**Issue by qq274936784** [ChenYilong/CYLTabBarController#333]
## Base Info for this issue 

 1. Version：v1.13.1
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
可以，小红点的坐标设置API是：

 ```Objective-C
@property (nonatomic, assign, setter=cyl_setTabBadgePointViewOffset:, getter=cyl_tabBadgePointViewOffset) UIOffset cyl_tabBadgePointViewOffset;
 ```

**Comment by ChenYilong** [comment]
v1.19.0更改小红点实现方式，并增加多个API自定义红点UI样式、动画效果。请更新重试。相关API展示在CYLBadgeProtocol.h 中
