### ISSUE TITLE
plusButton 注册之后不显示啊

### ISSUE THREAD

**Issue by zhanglongjiang** [ChenYilong/CYLTabBarController#334]
## Base Info for this issue 

 1. Version：v1.17.20
 2. Language：swift
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：NO
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
描述太笼统，无法解答，请补充细节。

**Comment by ChenYilong** [comment]
参考这个issue：https://github.com/ChenYilong/CYLTabBarController/issues/248
