### ISSUE TITLE
重置根视图为CYLTabBarController时,PlusButton会消失,再次重置会出现.

### ISSUE THREAD

**Issue by yanghuittxs** [ChenYilong/CYLTabBarController#335]
## Base Info for this issue 

 1. Version：pod 'CYLTabBarController', '~> 1.17.22'
 2. Language：Objective-C
 4. iOS System Version：iOS12
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 1. How to repeat the problem.

APP启动,进行registerPlusButton, 登录后设置根视图为CYLTabBarController,设置4个tabbaritem.界面加载完成,PlusButton存在
(a操作) 在第四个item选中的子controller中,根据业务进行了两次push操作, (此时根视图仍为CYLTabBarController)然后在当前界面重置根视图为CYLTabBarController(新的对象),界面回到第一个tabbaritem对应的子controller.

此时,PlusButton消失了.tabbar只剩下4个item了.(必现)
重复a操作
此时,PlusButton又出现了.(必现)

我在a操作中,重置根视图之前,又进行了一次registerPlusButton步骤. 此问题可避免.但是仍然出现极难复现的,无规律的.PlusButton消失 的现象.

## 2. Please help me in this way.

我的项目业务是,在APP设置界面内,手动设置切换多语言支持后,希望重置根视图回到主界面重新加载视图,但是出现PlusButton消失的现象.无法解决.help!!!

a操作必现的情况,我发现是由于新的CYLTabBarController创建后,当前tabbar进行,layoutsubviews时.  PlusButton的superview不是当前tabbar,所以没有进行布局. 所以我在重置根视图之前又进行了一次registerPlusButton步骤.但是出现了上面所说的极难复现 无规律的PlusButton消失 的现象.

无解,请大神帮助

**Comment by LoneyLi** [comment]
我的出现这种情况的流程是 ：用户退出登录后我会把登录页面设置为根试图 ，登录成功，重新把CYLTabBarController 设置为根试图，这个时候就可能出现plusButton消失的情况

**Comment by LoneyLi** [comment]
导致PlusButton消失的主要原因就是重置根试图

**Comment by TianXuang** [comment]
这个问题可以通过AppDelegate强引用tabbar来解决

**Comment by ChenYilong** [comment]
我怀疑是没有重新注册 plusButton，每次重制都要重新注册。
