### ISSUE TITLE
更新QMUIKit到2.9.3版本后，真机上tabbar不展示

### ISSUE THREAD

**Issue by ReadyFlyStone** [ChenYilong/CYLTabBarController#339]
## Base Info for this issue 

 1. Version：v1.17.22
 2. Language：Objective-C
 4. iOS System Version：iOS12.0
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 1. How to repeat the problem.

今天把QMUIKit更新到最新版（2.9.3），模拟器上可以展示底部栏，真机不展示。查看层级发现tabbar位置大小都出现问题。当把QMUIKit回退到~>2.7.0，问题消失。这里是设置了什么导致不兼容真机了？
![snip20181224_3](https://user-images.githubusercontent.com/15199443/50399465-9cf31a80-07ba-11e9-86b0-b253b8f9af7b.png)
![snip20181224_1](https://user-images.githubusercontent.com/15199443/50399466-9fee0b00-07ba-11e9-86eb-d37bb70930dd.png)

**Comment by Gayle448** [comment]
Me too,can you tell me how to fix it?

**Comment by 370966584** [comment]
今天也遇到了     发现UITabBar+QMUI.h  里面对也对tabbar做了改动可能冲突了吧  把这个分类删了就行了

**Comment by 370966584** [comment]
![image](https://user-images.githubusercontent.com/26058251/56109919-2787a180-5f85-11e9-9c18-d5b9c77c4ce0.png)

**Comment by ChenYilong** [comment]
多谢提供解决方案
