### ISSUE TITLE
求设置各tabItem的宽度

### ISSUE THREAD

**Issue by WelkinXie** [ChenYilong/CYLTabBarController#34]
求设置各tabItem的宽度和plusButton的占宽

**Comment by ChenYilong** [comment]
为什么有这个需求。是想plusButton和其他item不等宽吗

**Comment by WelkinXie** [comment]
当plusBtn左右各有一个tabItem时，左右的tabItem图片太偏离中心了，想往中间靠一点

**Comment by ChenYilong** [comment]
求截图。

**Comment by WelkinXie** [comment]
![simulator screen shot 2016 4 7 3 57 48](https://cloud.githubusercontent.com/assets/12717925/14344447/404ff99e-fcda-11e5-954e-2a6604549467.png)

**Comment by ChenYilong** [comment]
这个是等宽的，可能你感觉，等宽的话，显得不太协调，是吧，你想让左右往中间靠拢下。

**Comment by WelkinXie** [comment]
对 当中间的按钮不大的时候 旁边的就显得太偏离了

**Comment by ChenYilong** [comment]
这里有个问题，就是，你是打算让左右的item宽度变短，然后往中间靠，然后两边留肯定会留下一个不可点击的区域。

如果两边item宽度不变，只改变plusBtn的宽度，显然也达不到你想要的效果。

这个你怎么考虑的？

**Comment by devtofu** [comment]
其实是像我这个 app ,中间的钮比较大，这样和左右两个 item 靠着太近，不太协调

![4e235e8d-a45a-4e68-ab8e-241781bbdb4d](https://cloud.githubusercontent.com/assets/12134966/14344620/46cfb434-fcdb-11e5-8644-ff234479817e.png)

**Comment by ChenYilong** [comment]
@devtofu 你想怎么修改？

**Comment by WelkinXie** [comment]
是plusBtn所在的tab的宽度太长了，然而其实plusBtn实际上并不需要那么宽。我觉得最好可以按照设置的plusBtn的宽度来设置它所在的tab的宽度，然后其余的tab的宽度再按照屏幕剩余可用的宽度来平分。

**Comment by WelkinXie** [comment]
这样同时也能解决 devtofu 的问题

**Comment by ChenYilong** [comment]
这个有两种方式可以解决，

 1. 默认，plusBtn宽度是与其它item等宽，但是允许设置plusButton的宽度
 2. 默认tabbarItem宽度tabbar总宽度减去plusBtn的图片的宽度，除以tabbarItem个数。并且允许设置plusButton的宽度。

**Comment by WelkinXie** [comment]
👍 上

**Comment by WelkinXie** [comment]
感觉1比较适合做默认，但是可能2适用的情况会多点。

**Comment by WelkinXie** [comment]
感觉要先多测试几种情况看看2的适用性

**Comment by devtofu** [comment]
我觉得 1 更动态一点， 2 对图片格式上有些限制，如果图片是个 宽 < 高 的，就不好了  @ChenYilong

**Comment by ChenYilong** [comment]
CocoaPods 版本号更新至v1.2.3，能根据PlusButton的宽度自动调整TabBarItem的宽度，相关说明如下：

![enter image description here](http://i64.tinypic.com/b4uhcj.jpg)


@devtofu @WelkinXie @CHNLiPeng @devjia

**Comment by WelkinXie** [comment]
视觉效果好多了~

**Comment by ChenYilong** [comment]
@devtofu @WelkinXie @CHNLiPeng @devjia 好用的话，贴下显示效果对比，贴下图片。

**Comment by WelkinXie** [comment]
前：
![simulator screen shot 2016 4 7 3 57 48](https://cloud.githubusercontent.com/assets/12717925/14374640/e023e498-fd8a-11e5-80e3-658c1dd5dc99.png)
后：
![simulator screen shot 2016 4 8 1 05 42](https://cloud.githubusercontent.com/assets/12717925/14374641/e204d2d6-fd8a-11e5-868d-c9d4767db4ca.png)
好太多

**Comment by devtofu** [comment]
好用。 谢谢更新 ！
 
![3e19024d-5f55-4178-bb45-2d66f973727b](https://cloud.githubusercontent.com/assets/12134966/14401342/4b0a24fa-fe41-11e5-8679-aba18bfdefac.png)

**Comment by ChenYilong** [comment]
有需求，及时提
