### ISSUE TITLE
隐藏标题后,图片的确居中了,但是无法点击,最新版17.22,真机 iPhone6,10.3.1,换模拟器跑没有问题,就这个真机有问题

### ISSUE THREAD

**Issue by whyAreYouSoShy** [ChenYilong/CYLTabBarController#340]
## Base Info for this issue 

 1. Version：v1.17.22
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 4. Here is my Debug log

隐藏标题后,图片的确居中了,但是无法点击,最新版17.22

**Comment by ChenYilong** [comment]
我的demo，测试了吗？能复现吗？
