### ISSUE TITLE
[CN]如何一行代码实现Lottie动画TabBar [EN]How to add animation of Lottie with one line of code

### ISSUE THREAD

**Issue by ChenYilong** [ChenYilong/CYLTabBarController#341]
![enter image description here](http://i68.tinypic.com/ifyhoo.jpg)

----------

<p align="center">
<a href="https://github.com/ChenYilong/iOSBlog/issues/21"><img src="https://img.shields.io/static/v1.svg?label=Consider%20donating!&color=blue&message=%E7%82%B9%E5%87%BB%E6%8D%90%E8%B5%A0&color=green"></a>
</p>

<p align="center">
<a href="https://twitter.com/stevechen1010"><img src="https://img.shields.io/twitter/url/http/shields.io.svg?style=social&maxAge=2592000"></a>
<a href="http://weibo.com/luohanchenyilong"><img src="http://i67.tinypic.com/wbulbr.jpg"></a>
</a><a href="https://t.me/CYLTabBarController"><img src="http://i66.tinypic.com/of2hbn.jpg"></a></a> 
</p>

----------

[CN]v1.24.1 版本添加了Lottie动画支持，可以最少添加一行代码，就可支持 Lottie 动画 TabBar： |
:-------------| 
[EN]In version of v1.24.1, CYLTabBarController supports to add animation of Lottie with one line of code. |

![enter image description here](http://i66.tinypic.com/25oxkqo.jpg)|
:-------------:|
![enter image description here](http://i67.tinypic.com/5kkpsk.jpg)|

[CN]一行代码说明： 一个 TabBarItem 只设置一个键值 `CYLTabBarLottieURL` 即可支持。四个 TabBarItem 那就是四行代码。|
:-------------|
[EN]what does one line of code mean: If your TabBar is only conposed of one TabBarItem, you only need to assign a value to the key named `CYLTabBarLottieURL` . If it is conposed of four number of TabBarItems, you should add four lines of code.|

[CN]具体用法见：|
:-------------|
[EN]How to use it:|

[CN]初始化时将以下两个值赋值即可：|
:-------------|
[EN]Assign a values to keys listed here:|

 [CN]对比 </p>[EN]Comparation   | key1 |  key2 
:-------------:|:-------------:|:-------------:
   key    |  `CYLTabBarLottieURL`   | `CYLTabBarLottieSize`
 type of value   | `NSURL` | `NSValue`
meaning of value  | [CN]lottie 所在路径 </p> path of resource    | [CN]LottieView大小 </p> size of LottieView  
attention  | [CN]必填 </p> required | [CN]选填 </p> [EN] optional
other | [CN]根据此键值判断是否开启Lottie动画功能</p>[EN]CYLTabBarController will evaluate in this key whether the animation should be added | [CN]选填，如果未传入了，会首先取 `CYLTabBarItemImage`对应view的size，如果未传入，则会在内部取一个固定的缺省值。 </p>[EN]This key is optional, if you donot assign any value to it,  CYLTabBarController will try to assign the size of value of `CYLTabBarItemImage`. However if the value of `CYLTabBarItemImage` is null, CYLTabBarController will assign a default value to it.

[CN]代码演示：|
:-------------|
[EN]Show case:|

update `Podfile`:

 ```Objective-C
//Podfile
#pod 'CYLTabBarController', '~> 1.24.1'        # [CN]默认不依赖Lottie [EN]Do not depend on lottie by default
pod 'CYLTabBarController/Lottie', '~> 1.24.1' # [CN]依赖Lottie库 [EN] Depend on lottie 
 ```

code:

 ```Objective-C
        NSBundle *bundle = [NSBundle bundleForClass:[MainTabBarController class]];
    NSDictionary *firstTabBarItemsAttributes = @{
                                                 CYLTabBarLottieURL : [NSURL fileURLWithPath:[bundle pathForResource:@"tab_home_animate" ofType:@"json"]],
                                                 // CYLTabBarLottieSize: [NSValue valueWithCGSize:CGSizeMake(22, 22)]//选填，设置LottieView大小
                                                 };
    NSDictionary *secondTabBarItemsAttributes = @{
                                                  CYLTabBarLottieURL : [NSURL fileURLWithPath:[bundle pathForResource:@"tab_search_animate" ofType:@"json"]],
                                                  // CYLTabBarLottieSize: [NSValue valueWithCGSize:CGSizeMake(22, 22)]//选填，设置LottieView大小
                                                  };

    NSArray *tabBarItemsAttributes = @[
                                       firstTabBarItemsAttributes,
                                       secondTabBarItemsAttributes,
                                       ];

    CYLTabBarController *tabBarController = [CYLTabBarController tabBarControllerWithViewControllers:self.viewControllers
                                                                               tabBarItemsAttributes:self.tabBarItemsAttributesForController
                                                                                         imageInsets:imageInsets
                                                                             titlePositionAdjustment:titlePositionAdjustment
                                                                                             context:nil
                                             ];

 ```

----------

Posted by [微博@iOS程序犭袁](http://weibo.com/luohanchenyilong/)  
原创文章，版权声明：自由转载-非商用-非衍生-保持署名 | [Creative Commons BY-NC-ND 3.0](http://creativecommons.org/licenses/by-nc-nd/3.0/deed.zh)
<p align="center"><a href="http://weibo.com/u/1692391497?s=6uyXnP" target="_blank"><img border="0" src="http://service.t.sina.com.cn/widget/qmd/1692391497/b46c844b/1.png"/></a></a>

**Comment by ChenYilong** [comment]
v1.23.0 版本添加了Lottie动画支持，具体用法见：
CYLTabBarLottieURL

 ```Objective-C
        NSBundle *bundle = [NSBundle bundleForClass:[MainTabBarController class]];
    NSDictionary *firstTabBarItemsAttributes = @{
                                                 CYLTabBarLottieURL : [NSURL fileURLWithPath:[bundle pathForResource:@"tab_home_animate" ofType:@"json"]],
                                                 // CYLTabBarLottieSize: [NSValue valueWithCGSize:CGSizeMake(22, 22)]//选填，设置LottieView大小
                                                 };
    NSDictionary *secondTabBarItemsAttributes = @{
                                                  CYLTabBarLottieURL : [NSURL fileURLWithPath:[bundle pathForResource:@"tab_search_animate" ofType:@"json"]],
                                                  // CYLTabBarLottieSize: [NSValue valueWithCGSize:CGSizeMake(22, 22)]//选填，设置LottieView大小
                                                  };

    NSArray *tabBarItemsAttributes = @[
                                       firstTabBarItemsAttributes,
                                       secondTabBarItemsAttributes,
                                       ];

    CYLTabBarController *tabBarController = [CYLTabBarController tabBarControllerWithViewControllers:self.viewControllers
                                                                               tabBarItemsAttributes:self.tabBarItemsAttributesForController
                                                                                         imageInsets:imageInsets
                                                                             titlePositionAdjustment:titlePositionAdjustment
                                                                                             context:nil
                                             ];

 ```

**Comment by LazyJiu** [comment]
后续集成势必要引入lottie，像我这种纯oc项目，140多m的，又不想使用lottie的，一旦引入swift就要超150m😂

**Comment by HolmesZhao** [comment]
这个为了方便大佬可以单独写一个 category 么, 这样别的地方使用 lottie 的时候一行代码创建就好了😂 省的自己再写一份, 免得代码冗余

**Comment by ChenYilong** [comment]
> 项目

Lottie项目2.5.x之前用 Objective-C 实现的，之后的版本使用Swift实现的，目前CYLTabBarController依赖的是Objective-C版本。

**Comment by ChenYilong** [comment]
> 后续集成势必要引入lottie，像我这种纯oc项目，140多m的，又不想使用lottie的，一旦引入swift就要超150m😂

Lottie项目2.5.x之前用 Objective-C 实现的，之后的版本使用Swift实现的，目前CYLTabBarController依赖的是Objective-C版本。

**Comment by ChenYilong** [comment]
Lottie官网有很多，动画文件，可以直接导出json，稍微改造下就能使用。
https://lottiefiles.com/recent

版权协议 https://lottiefiles.com/page/license
CC协议，（Creative Commons license）非常宽松
Files can be used for commercial usage within Applications

**Comment by IIIOS** [comment]
根本用不起，

**Comment by korea1501541730** [comment]
XR iOS 13 release版本 动画一直刷CPU%。app直接挂了。又遇到的吗？

**Comment by TzyTman** [comment]
OC版本库在哪里？

**Comment by baishitong** [comment]
设置了   [self.cyl_tabBarController setSelectedIndex:2]; lottie动画的选中没有切换？

**Comment by ChenYilong** [comment]
> 设置了   [self.cyl_tabBarController setSelectedIndex:2]; lottie动画的选中没有切换？

参照demo，要加延迟才行。

**Comment by wyzCocoa** [comment]
您好，大牛，我想动态修改某个tabBarItem的lottie, 应该怎么做呢

**Comment by yuyedaidao** [comment]
@windforedawn  有同样的疑问，不知道这个库还在维护吗

**Comment by ChenYilong** [comment]
@windforedawn  最新版本已支持Lottie swift库与oc 库引入，在demo中演示了如何运行中刷新。但刷新目前方案会将view controllers一起刷新

**Comment by ChenYilong** [comment]
> @windforedawn  有同样的疑问，不知道这个库还在维护吗

我将你的分支也合并进主分支了，你新建的接口也添加了。你可以基于我的最新版在项目中继续使用。
