### ISSUE TITLE
iPad 侧边tabbar怎么设置

### ISSUE THREAD

**Issue by Liyongcong** [ChenYilong/CYLTabBarController#342]
## Base Info for this issue 

 1. Version：v1.17.x
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by Liyongcong** [comment]
是的，要实现，iPad上，垂直tabbar的功能

**Comment by ChenYilong** [comment]
你是指在tabbar整体在左侧展示，而非像iPhone上一样在底部展示？

**Comment by Liyongcong** [comment]
是的，就是类似系统tabbar的功能，不过tabbar是在左侧垂直的

**Comment by ChenYilong** [comment]
这个需要独立设计实现了，加我微信 chenyilong1010，详聊。
