### ISSUE TITLE
non public api

### ISSUE THREAD

**Issue by Cenfee** [ChenYilong/CYLTabBarController#343]
审核被拒 UITabBarButton non public api 

项目唯一能搜到UITabBarButton，就是这个位置，

 /* 这个问题是 iOS 12.1 的问题，只要 UITabBar 是磨砂的，并且 push viewController 时 hidesBottomBarWhenPushed = YES 则手势返回的时候就会触发。(来源于QMUIKit的处理方式)*/
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        if (@available(iOS 12.1, *)) {
            OverrideImplementation(NSClassFromString( @"UITabBarButton"), @selector(setFrame:), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP originIMP)

**Comment by Cenfee** [comment]
有朋友指招吗，应该怎么改， 要打包。。

**Comment by ChenYilong** [comment]
稍等我改下，这个问题Apple已经修复了。这段代码可以删了

**Comment by Cenfee** [comment]
谢谢作者的热心，好了麻烦说一下。

如果没那么快的话，也麻烦说下，在线等。

**Comment by Cenfee** [comment]
好的，那我先用 1.17.17

**Comment by ChenYilong** [comment]
Apple在 iOS12.1.1已经修复该问题，v1.17.23版本进行版本判断，仅仅在iOS12.1与iOS12.1.1之间才进行hook处理。其他版本与系统版本保持一致。
