### ISSUE TITLE
请问如何设置plusBtn的titleEdgeInsets，使得标题和其他tabbarItem的对齐

### ISSUE THREAD

**Issue by luckyzd** [ChenYilong/CYLTabBarController#345]
## Base Info for this issue 

 1. Version：v1.17.22
 2. Language：Objective-C
 4. iOS System Version：iOS12.1.4
 5. Prototype（是否是真机）：YES
 6. Issue Type：Q-A

请问如何设置plusBtn的titleEdgeInsets，使得标题和其他tabbarItem的对齐，谢谢！

**Comment by ChenYilong** [comment]
titleEdgeInsets调整方法在demo中有演示，请查看最新demo。
需要手动调整参数，调整对齐。
