### ISSUE TITLE
隐藏标题之后，角标位置问题

### ISSUE THREAD

**Issue by iOSchuang** [ChenYilong/CYLTabBarController#347]
## Base Info for this issue 

最新版本Demo

 1. Version：v1.17.x
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to reproduce the problem.

运行最新版本Demo,注释掉设置标题的代码，iPhone X 运行之后，角标位置偏高
## 3. Here is a Demo. 

原始Demo,注释掉设置标题代码
    NSDictionary *firstTabBarItemsAttributes = @{
//                                                 CYLTabBarItemTitle : @"首页",
                                                 CYLTabBarItemImage : @"home_normal",  /* NSString and UIImage are supported*/
                                                 CYLTabBarItemSelectedImage : @"home_highlight",  /* NSString and UIImage are supported*/
                                                 CYLTabBarItemTitlePositionAdjustment: [NSValue valueWithUIOffset:UIOffsetMake(firstXOffset, -3.5)]
                                                 //第一位 右大，下大
                                                 };
    CGFloat secondXOffset = (-25+2)/2;
    NSDictionary *secondTabBarItemsAttributes = @{
//                                                  CYLTabBarItemTitle : @"鱼塘",
                                                  CYLTabBarItemImage : @"fishpond_normal",
                                                  CYLTabBarItemSelectedImage : @"fishpond_highlight",
                                                  CYLTabBarItemTitlePositionAdjustment: [NSValue valueWithUIOffset:UIOffsetMake(secondXOffset, -3.5)]
                                                  };
    
    NSDictionary *thirdTabBarItemsAttributes = @{
//                                                 CYLTabBarItemTitle : @"消息",
                                                 CYLTabBarItemImage : @"message_normal",
                                                 CYLTabBarItemSelectedImage : @"message_highlight",
                                                 CYLTabBarItemTitlePositionAdjustment: [NSValue valueWithUIOffset:UIOffsetMake(-secondXOffset, -3.5)]
                                                 };
    NSDictionary *fourthTabBarItemsAttributes = @{
//                                                  CYLTabBarItemTitle : @"我的",
                                                  CYLTabBarItemImage : @"account_normal",
                                                  CYLTabBarItemSelectedImage : @"account_highlight",
                                                  CYLTabBarItemTitlePositionAdjustment: [NSValue valueWithUIOffset:UIOffsetMake(-firstXOffset, -3.5)]
                                                  };
    NSArray *tabBarItemsAttributes = @[
                                       firstTabBarItemsAttributes,
                                       secondTabBarItemsAttributes,
                                       thirdTabBarItemsAttributes,
                                       fourthTabBarItemsAttributes
                                       ];
    return tabBarItemsAttributes;
<img width="942" alt="001" src="https://user-images.githubusercontent.com/15044460/53724409-c7411280-3ea4-11e9-9d64-d29ba38ac25e.png">

<img width="461" alt="002" src="https://user-images.githubusercontent.com/15044460/53724430-d3c56b00-3ea4-11e9-9849-7835c7c4a2a2.png">

**Comment by ChenYilong** [comment]
这种情况可以通过调整tabbar高度解决。不显示文字，一般都需要减小tabbar高度，故之前没改，之后会做调整，保证显示正常。要是有好的想法，欢迎提出建议。

**Comment by iOSchuang** [comment]
后边优化badge的话，将badge和显示的小圆点能结合起来，相当于要自定义badge,使用的话可能更方便。
或者能否直接将小圆点的视图进行优化，可以传值进去，直接替代系统的badge。

**Comment by ChenYilong** [comment]
目前小圆点是可以传View的，上图中出现异常的是系统自带的badge。

**Comment by iOSchuang** [comment]
好的，谢谢。后边这一部分优化了，我再替换

**Comment by ChenYilong** [comment]
v1.19.0更改小红点实现方式，解决了该问题，并增加多个API自定义红点UI样式、动画效果。请更新重试。
