### ISSUE TITLE
tabBarController: shouldSelectViewController走两次

### ISSUE THREAD

**Issue by haiyucn** [ChenYilong/CYLTabBarController#348]
你好！

CYLTabBarController.m 中这段代码的目的是什么？加了这段代码会导致   tabBarController: shouldSelectViewController走两次

    BOOL shouldSelectViewController =  YES;
    try {
       shouldSelectViewController = control.cyl_isPlusButton || (control.cyl_isTabButton &&
     [self.delegate tabBarController:self shouldSelectViewController:self.viewControllers[tabIndex]]);
    } @catch (NSException *exception) {
        NSLog(@"🔴类名与方法名：%@（在第%@行），描述：%@", @(__PRETTY_FUNCTION__), @(__LINE__), exception.reason);
    }

**Comment by ChenYilong** [comment]
稍等，我今天更新一个版本，是个bug。

**Comment by ChenYilong** [comment]
v1.19.0已经修复该问题，请更新重试。
