### ISSUE TITLE
在第二个页面设置setBadgeValue，但是非得点一下，那个badge才会出现

### ISSUE THREAD

**Issue by yangsheng** [ChenYilong/CYLTabBarController#35]
如果不是第一个页面，设置Badge，就非得点一下选中后，那个badge才会出现。

我要实现：比如在首页点击一个收藏按钮，第二个页面就会多一个Badge值。这个可以吗？谢谢。

**Comment by ChenYilong** [comment]
可以啊，你需要借助下类似通知或其它机制来传递点击事件，比如，你点击收藏后，然后就可以post一个通知，然后，你就可以在第二个页面触发调用：


 ```Objective-C
    [self.navigationController.tabBarItem setBadgeValue:badgeNumber];

 ```

**Comment by yangsheng** [comment]
好的，谢谢

**Comment by wangyu6951293** [comment]
好像不行.不知道为什么.我在第一个页面发通知 第二个页面也要来回切换才可以显示

**Comment by ChenYilong** [comment]
要想绕过系统控件的懒加载机制，只能通过自定义tabbar做了，目前打算参考下下面两个库，实现下：


  1. https://github.com/Zzzard/HXRedDotTabBarItem
  2.  https://github.com/DeveloperLx/LxTabBadgePoint

**Comment by ChenYilong** [comment]
v1.13.0已经可自定义View来展示 TabBarItem 角标，默认支持未读小红点。详情参考文档。一打开APP就显示红点，已经在Demo中演示。

**Comment by ChenYilong** [comment]
@yangsheng @wangyuuuu 你们的需求在Demo中已经演示，请更新查看。

**Comment by wangyuuuu** [comment]
thanks

**Comment by FrankSwift** [comment]
我在一个界面做一些操作 希望第二个界面有小红点 [tabBarVC.viewControllers[1] cyl_showTabBadgePoint]; 并没有反应
