### ISSUE TITLE
点击PlusButton，方法走两次

### ISSUE THREAD

**Issue by iOSchuang** [ChenYilong/CYLTabBarController#351]
## Base Info for this issue 

 1. Version：v1.17.x
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to reproduce the problem.

从其他按钮切换到plusButton,- (void)tabBarController:(UITabBarController *)tabBarController didSelectControl:(UIControl *)control方法会调用两次，在plusButton界面点击plusButton,该方法会走一次，其他正常，请问是什么原因？
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/15044460/53939148-3b6df700-40ed-11e9-83df-25a0c5b38844.png">

**Comment by ChenYilong** [comment]
v1.19.2已经修复
