### ISSUE TITLE
代理如何设置在CYLTabBarController的子类中

### ISSUE THREAD

**Issue by yanashenyang** [ChenYilong/CYLTabBarController#352]
## Base Info for this issue 

代理如何设置在CYLTabBarController的子类中

 
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to reproduce the problem.

代理如何设置在CYLTabBarController的子类中
## 2. Please help me in this way.

代理如何设置在CYLTabBarController的子类中

**Comment by ChenYilong** [comment]
self.delegate = self

**Comment by ChenYilong** [comment]
更新 demo 修复二次初始化，不走代理方法不走代理方法的问题，

详情见： 
 - https://github.com/ChenYilong/CYLTabBarController/commit/91f6de1af523f096d6ccc2b8a5accbc04b31f850

 - https://github.com/ChenYilong/CYLTabBarController/issues/161
