### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by LengYi** [ChenYilong/CYLTabBarController#353]
## Base Info for this issue 

 1. Version：v1.17.x
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 4. Here is my Debug log

1.19.2没有更新到官方pod库

**Comment by LengYi** [comment]
1.19.2没有更新到官方pod库，pod库上是1.17.22

**Comment by ChenYilong** [comment]
请：
pod update
