### ISSUE TITLE
pod search 卡住

### ISSUE THREAD

**Issue by lztbwlkj** [ChenYilong/CYLTabBarController#354]
pod search CYLTabBarController 卡住10分钟了 如何解决
![WeChat8ca80dd561d8e3c5db8de1b25b4c626b](https://user-images.githubusercontent.com/20568661/54183253-ab5df200-44de-11e9-83a1-dd5d63e6ee50.png)

**Comment by ChenYilong** [comment]
“飜 /f ān/ 蘠 /q iáng/”

**Comment by lztbwlkj** [comment]
![image](https://user-images.githubusercontent.com/20568661/54428056-3c3f0280-4757-11e9-9a55-403eb8ee8e30.png)
