### ISSUE TITLE
PlusButton 更换图标后，点击会显示错误，明明是在中间显示会显示在第一个

### ISSUE THREAD

**Issue by jackhanm** [ChenYilong/CYLTabBarController#357]
## Base Info for this issue 

 1. Version：v1.17.x
 2. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by jackhanm** [comment]
<img width="340" alt="屏幕快照 2019-03-20 下午2 54 36" src="https://user-images.githubusercontent.com/16136350/54664765-2303d080-4b20-11e9-891d-b0f3514ef8a3.png">
<img width="376" alt="屏幕快照 2019-03-20 下午2 53 59" src="https://user-images.githubusercontent.com/16136350/54664770-25662a80-4b20-11e9-9dd8-a0d9df9fc991.png">
<img width="407" alt="屏幕快照 2019-03-20 下午2 53 48" src="https://user-images.githubusercontent.com/16136350/54664771-272fee00-4b20-11e9-8860-8e7bbd215ba0.png">

**Comment by jackhanm** [comment]
UIImage *buttonImage = [UIImage imageNamed:@"guafen1"];
    CYLExternPlusButton.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleBottomMargin | UIViewAutoresizingFlexibleTopMargin;
    CYLExternPlusButton.frame = CGRectMake(0.0, 0.0, buttonImage.size.width, buttonImage.size.height);
    [CYLExternPlusButton setImage:buttonImage forState:UIControlStateNormal];
    [CYLExternPlusButton setImage:buttonImage forState:UIControlStateHighlighted];
    [CYLExternPlusButton setBackgroundImage:buttonImage forState:UIControlStateNormal];
    [CYLExternPlusButton setBackgroundImage:buttonImage forState:UIControlStateHighlighted];

**Comment by jackhanm** [comment]
在页面刚出来的时候替换图片

**Comment by ChenYilong** [comment]
不要修改plusBtn的坐标。修改坐标有对应的protocol接口

**Comment by ChenYilong** [comment]
怎么样了

**Comment by VillageMud** [comment]
现在还要进行视频iPhone X异形屏，还要兼顾之前的老机器，显得有点麻烦了

**Comment by VillageMud** [comment]
6s
![image](https://user-images.githubusercontent.com/12798195/54738294-9a079a80-4bee-11e9-9928-200ff84da477.png)
iphone x
![image](https://user-images.githubusercontent.com/12798195/54738310-b0adf180-4bee-11e9-9f17-3199ac8a7d65.png)
