### ISSUE TITLE
hideTabBadgeBackgroundSeparator 方法调用后背景颜色变成灰黑色

### ISSUE THREAD

**Issue by a497500306** [ChenYilong/CYLTabBarController#358]
使用你例子中的swift版,
![image](https://user-images.githubusercontent.com/12522414/55207997-7c05ef80-5217-11e9-8712-764c1f4488bd.png)
![image](https://user-images.githubusercontent.com/12522414/55208005-84f6c100-5217-11e9-8eda-f1d3e536c88e.png)

**Comment by ChenYilong** [comment]
v1.20.0 已经修复，更新重试。
