### ISSUE TITLE
tabBar三个菜单，外加一个自定义Button，然后显示最右边，下面的距离没有平均分布

### ISSUE THREAD

**Issue by ulongx** [ChenYilong/CYLTabBarController#36]
```
- (instancetype)plusButton {

PulishButtonSubClass *button = [[PulishButtonSubClass alloc] init];

[button setImage:[UIImage imageNamed:@"camera"] forState:UIControlStateNormal];
[button sizeToFit];

[button addTarget:button action:@selector(clickPublish) forControlEvents:UIControlEventTouchUpInside];

return button;


}
# pragma mark - CYLPlusButtonSubclassing

 (NSUInteger)indexOfPlusButtonInTabBar {
    return 3;
}
```

**Comment by ChenYilong** [comment]
求截图

**Comment by ulongx** [comment]
发到你的QQ了

**Comment by ChenYilong** [comment]
我测试了下，是正常的。估计是你的button太小了。
![enter image description here](http://i65.tinypic.com/2ms1rh0.jpg)

你把这一行代码改下，

 ```Objective-C
[button sizeToFit];
 ```

改成：


 ```Objective-C
button.frame = CGRectMake(0.0, 0.0, w, h);
 ```

**Comment by ulongx** [comment]
好的，我试试

**Comment by ulongx** [comment]
谢谢，可以了，是按钮大小的问题，如果单是放一个照相机的图片，一般是多大的尺寸？

**Comment by ChenYilong** [comment]
这个要看设计图了吧，通常情况下，你可以写死 `[UIScreen mainScreen].bounds.size.width / [CYLTabBarController allItemsInTabBarCount]`。

**Comment by ChenYilong** [comment]
你的app叫什么名字？

**Comment by ulongx** [comment]
好的谢谢，App才开始。正在搭框架。嘿嘿

**Comment by bloodspasm** [comment]
十分有用(๑′ᴗ‵๑)

**Comment by GKman6657** [comment]
你好，请问plusButton中间的actionSheet  选中其中一个“拍照”，怎么push 到下一级controller？

**Comment by Liyongcong** [comment]
> 谢谢，可以了，是按钮大小的问题，如果单是放一个照相机的图片，一般是多大的尺寸？

我现在也遇到这个问题了，用的最新版本，没有平分，不知道为啥

**Comment by ChenYilong** [comment]
目前plus Button是用的反向依赖，需要根据你自定义的PlusButton大小来设置其他tabitem的大小。所以你需要自已设置大小。但iOS26之后，所有按钮都是均分的。都是系统预设的大小。plusButton的自定义大小不能超过系统默认大小。

**Comment by ChenYilong** [comment]
> 你好，请问plusButton中间的actionSheet  选中其中一个“拍照”，怎么push 到下一级controller？

以tabbarController为baseNavigationController进行push.或者以selectedViewController为导航控制器push
