### ISSUE TITLE
lottie太难pod下来了，建议把依赖lottie的类分文件夹依赖

### ISSUE THREAD

**Issue by jackiehu** [ChenYilong/CYLTabBarController#363]
lottie太难pod下来了，建议把依赖lottie的类分文件夹依赖，很多人可能不需要lottie

**Comment by ChenYilong** [comment]
是个问题，你什么意见，是把Lottie改前缀改造后加到库里，不需要pod 依赖吗？

**Comment by jackiehu** [comment]
s.subspec 'CYLTabBarController' do |ss|
          ss.source_files = 'CYLTabBarController/CYLTabBarController/**/*' 
          ss.public_header_files = "CYLTabBarController/CYLTabBarController/**/*.{h}"
    end
    s.subspec 'Lottie' do |ss| 
          ss.dependency 'Lottie'
          ss.source_files = 'CYLTabBarController/Lottie/**/*' 
          ss.public_header_files = "CYLTabBarController/Lottie/*.{h}"
    end
这样分两级目录呢？

**Comment by ChenYilong** [comment]
加你Q了，详聊。
