### ISSUE TITLE
你好，pod之后报错，请问是什么原因？

### ISSUE THREAD

**Issue by 542604974** [ChenYilong/CYLTabBarController#367]
错误的内容： 

> /Users/apple/Downloads/CYLTabBarController-master/Pods/Pods/Target Support Files/Pods-CYLTabBarController/Pods-CYLTabBarController.debug.xcconfig: unable to open file (in target "CYLTabBarController" in project "CYLTabBarController") (in target 'CYLTabBarController')

**Comment by ChenYilong** [comment]
是在podfile所在文件夹执行pod的吗？

**Comment by zhaoychehe** [comment]
![image](https://user-images.githubusercontent.com/10723944/56582348-a88c0c00-6609-11e9-8c19-731a0cddaed2.png)

**Comment by 542604974** [comment]
按照楼上的箭头，选择第二个就可以了，谢谢@zhaoychehe

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/368

**Comment by XuYoujin** [comment]
设置后还是有问题.

**Comment by XuYoujin** [comment]
pod 失败
![image](https://user-images.githubusercontent.com/29814321/57284153-2f011d00-70e3-11e9-9f97-8fb010fa5a73.png)

**Comment by ChenYilong** [comment]
pod成功后，打开 .xcworkspace文件，

Xcode版本Version 10.2.1 (10E1001)是可以直接运行的，

10.1版本需要单独处理：

需要切换一下 pods

![WechatIMG51](https://user-images.githubusercontent.com/2911921/57609901-5ef86680-75a2-11e9-8b4e-0a585786b466.png)


![WechatIMG54](https://user-images.githubusercontent.com/2911921/57609895-5acc4900-75a2-11e9-9095-e3790adbbc1d.jpeg)
