### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by AllisonWangJiaoJiao** [ChenYilong/CYLTabBarController#368]
模拟器运行一直提示下面的错误：

> Showing Recent Messages:
 /Users/allison/Downloads/CYLTabBarController-1.24.0/Pods/Pods/Target Support Files/Pods-CYLTabBarController/Pods-CYLTabBarController.debug.xcconfig: unable to open file (in target "CYLTabBarController" in project "CYLTabBarController") (in target 'CYLTabBarController')

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/367
