### ISSUE TITLE
请问如果我中间的按钮点击model一个ViewController怎么实现？

### ISSUE THREAD

**Issue by 542604974** [ChenYilong/CYLTabBarController#37]
请问如果我中间的按钮点击model一个ViewController怎么实现？

**Comment by ChenYilong** [comment]
直接在 `CYLPlusButtonSubclass.m ` 里 `- (void)clickPublish `方法里写就好了

**Comment by 542604974** [comment]
那这个self不知道怎么填，我搞不清楚这个self指向哪里[self presentViewController:loginController animated:YES completion:nil];

**Comment by 542604974** [comment]
哦，懂了，可以了，谢谢，嘿嘿嘿

**Comment by ChenYilong** [comment]
你怎么写的，可以贴写代码，分享下

**Comment by 542604974** [comment]
UITabBarController *tabBarController = (UITabBarController *)self.window.rootViewController;
    UIViewController *viewController = tabBarController.selectedViewController;

    ZQMiddleBarController *MiddleBarController = [ZQMiddleBarController new];
    [viewController presentViewController:MiddleBarController animated:YES completion:nil];

你都写好了，我直接用就行了，但如果我要push呢，因为谁知道变态经理需求会不会改

**Comment by ChenYilong** [comment]
这样写：


 ```Objective-C
   CYLTabBarController *tabbarController = [self cyl_tabBarController];
   UIViewController *viewController = tabbarController.selectedViewController;
   [viewController presentViewController:loginController animated:YES completion:nil];
 ```
