### ISSUE TITLE
低栏图标虽点击升高，且会出现点击事件丢失问题[BUG]

### ISSUE THREAD

**Issue by 13hoop** [ChenYilong/CYLTabBarController#370]
hi,
感谢您的贡献，使用中有2个用户在不同手机以及不同系统出现过以下问题，现象如图
![image](https://user-images.githubusercontent.com/7189963/57439786-55f15780-7279-11e9-8d14-eca6846f763d.png)
即：
低栏图标会升高，并且点击一次会升高一次，同时造成点击事件响应丢失
猜测肯能是图片布局时产生的问题

 1. Version：1.18.0(https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec) 
 2. Language of App ：Objective-C
 4. iOS System Version：iOS12.2
 5. Prototype（是否是真机）：YES iphone6s
 6. Issue Type：Bug

------- 

另一次

1. Version：1.18.0(https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec) 
 2. Language of App ：Objective-C
 4. iOS System Version：iOS11.0
 5. Prototype（是否是真机）：YES iphone6p
 6. Issue Type：Bug

但此问题并不好复现，在同样手机/系统情况下，也只有部分特定某几部机器会现，而其它相同的型号手机正常

**Comment by ChenYilong** [comment]
初始化时是否设置了 imageInsets 这个参数，注意这个参数上和下、左和右，相加必须为0.

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/223

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/383
