### ISSUE TITLE
引入lottie动画，设置badge失效

### ISSUE THREAD

**Issue by liaoshaolim** [ChenYilong/CYLTabBarController#371]
![enter image description here](http://i68.tinypic.com/ifyhoo.jpg)

----------

<p align="center">
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec"><img src="https://img.shields.io/badge/Pod-GetLatestVersion-green.svg?style=flat"></a>
<a href=""><img src="https://img.shields.io/badge/Swift-compatible-orange.svg"></a>
<a href=""><img src="https://img.shields.io/badge/platform-iOS%208.0%2B-ff69b5152950834.svg"></a>
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/LICENSE"><img src="https://img.shields.io/badge/license-MIT-green.svg?style=flat"></a>
</p>

<p align="center">
<a href="https://github.com/ChenYilong/iOSBlog/issues/21"><img src="https://img.shields.io/static/v1.svg?label=QQ%E3%80%81Telegram%20Group&color=blue&message=%E7%82%B9%E5%87%BB%E8%8E%B7%E5%8F%96QQ%E3%80%81Telegram%E7%BE%A4%E4%BF%A1%E6%81%AF&color=green"></a>
</p>

<p align="center">
<a href="https://twitter.com/stevechen1010"><img src="https://img.shields.io/twitter/url/http/shields.io.svg?style=social&maxAge=2592000"></a>
<a href="http://weibo.com/luohanchenyilong"><img src="http://i67.tinypic.com/wbulbr.jpg"></a>
</a><a href="https://t.me/CYLTabBarController"><img src="http://i66.tinypic.com/of2hbn.jpg"></a></a> 
</p>

----------

## Base Info for this issue 

 1. Version：1.2.4(https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec) 
 2. Language of App ：Objective-C
 4. iOS System Version：iOS12.2
 5. Prototype（是否是真机）：模拟器
 6. Issue Type：（希望能支持一个新需求）、Q-A

## 1. How to reproduce the problem.

1.tabBarItemsAttributesForController （我这边item是通过lottie进行动画的，很高兴看到最新版支持lottie），添加了 CYLTabBarLottieURL 这个 key
2.[self cyl_tabBarController] setViewDidLayoutSubViewsBlockInvokeOnce...
按照建议在这边设置badge

然后，badge就失效了，因为我去掉 CYLTabBarLottieURL 这个key之后，badge都正常了
## 2. Please help me in this way.

badge 不与 lottie 相互影响
## 3. Here is a Demo. 
我直接在项目中集成的，demo，不好提供，希望问题我已经讲清楚了

## 4. Here is my Debug log

----------

<p align="center"><a href="http://weibo.com/u/1692391497?s=6uyXnP" target="_blank"><img border="0" src="http://service.t.sina.com.cn/widget/qmd/1692391497/b46c844b/1.png"/></a></a>

**Comment by ChenYilong** [comment]
setViewDidLayoutSubViewsBlockInvokeOnce
内部是否使用了延时操作，问题可能出在延时上，你重点调整下延时时间。看看能否解决。

**Comment by liaoshaolim** [comment]
> setViewDidLayoutSubViewsBlockInvokeOnce
> 内部是否使用了延时操作，问题可能出在延时上，你重点调整下延时时间。看看能否解决。

内部没有使用延迟操作

**Comment by ChenYilong** [comment]
加一个延时试试

**Comment by liaoshaolim** [comment]
> 加一个延时试试

添加取消，我试了好几次了，不行的
就感觉 lottie 动画和 badge 之间有冲突

**Comment by liaoshaolim** [comment]
非常抱歉，之前添加的延时函数是在外部...

现在添加好了，也显示了，但是，出现了新的问题

badge 都被遮盖住了一半

**Comment by liaoshaolim** [comment]
![如图.png](https://upload-images.jianshu.io/upload_images/1387592-da5273b78c336a56.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by ChenYilong** [comment]
badge的设置方法贴一下，我确认下你的api。

**Comment by ChenYilong** [comment]
参考demo做法，demo里跟你的效果一致。

**Comment by liaoshaolim** [comment]
好的，谢谢回复，真的好及时！

**Comment by ChenYilong** [comment]
你确认下是不是最新版吧，我记得这个问题修复了。

**Comment by ChenYilong** [comment]
版本更新到 https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec

**Comment by ChenYilong** [comment]
建议 app启动后就给icon加红点的情况下，加一个延时，lottie图片加载可能比一般的静态图片略微延迟。
总体可忽略不及，但一旦json文件过大，加载时间也会延长。加一秒延迟，再显示红点，比较稳妥。

 ```Objective-C
   //添加提示动画，引导用户点击
    [tabBarController setViewDidLayoutSubViewsBlockInvokeOnce:YES block:^(CYLTabBarController *tabBarController) {
        NSUInteger delaySeconds = 1;
        dispatch_time_t when = dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delaySeconds * NSEC_PER_SEC));
        dispatch_after(when, dispatch_get_main_queue(), ^{
            @try {
                UIViewController *viewController0 = tabBarController.viewControllers[0];
                // UIControl *tab0 = viewController0.cyl_tabButton;
                // [tab0 cyl_showBadge];
                [viewController0 cyl_setBadgeBackgroundColor:RANDOM_COLOR];
                [viewController0 cyl_setBadgeCenterOffset:CGPointMake(-5, 3)];
                [viewController0 cyl_setBadgeRadius:5/2];
                [viewController0 cyl_setBadgeMargin:1];
                [viewController0 cyl_showBadge];
                
                [tabBarController.viewControllers[1] cyl_showBadgeValue:@"" animationType:CYLBadgeAnimationTypeScale];
                [tabBarController.viewControllers[1] cyl_setBadgeBackgroundColor:RANDOM_COLOR];
                [tabBarController.viewControllers[2] cyl_showBadgeValue:@"test" animationType:CYLBadgeAnimationTypeShake];
                [tabBarController.viewControllers[3] cyl_showBadgeValue:@"100" animationType:CYLBadgeAnimationTypeBounce];
                [tabBarController.viewControllers[4] cyl_showBadgeValue:@"new" animationType:CYLBadgeAnimationTypeBreathe];
            } @catch (NSException *exception) {}

            //添加仿淘宝tabbar，第一个tab选中后有图标覆盖
            if ([self cyl_tabBarController].selectedIndex != 0) {
                return;
            }
//            tabBarController.selectedIndex = 1;
        });
    }];
 ```

**Comment by liaoshaolim** [comment]
嗯嗯，谢谢回复

**Comment by ChenYilong** [comment]
客气，后期有问题，多多反馈。

**Comment by ChenYilong** [comment]
欢迎加我微信交流.我的id是chenyilong1010。另外使用 CYLTabBarController 做的 APP，来这里报道下吧！ https://github.com/ChenYilong/CYLTabBarController/issues/314
