### ISSUE TITLE
跳轉新頁面后tabbar消失不見

### ISSUE THREAD

**Issue by zijianzhong** [ChenYilong/CYLTabBarController#372]
在第一層級有tabbar的頁面點擊tabbar外的button進行跳轉到新的頁面之後，Tabbar無論怎麼設置都顯示不出來。

**Comment by ChenYilong** [comment]
消失不见是你自己代码控制的，你可以改下。

**Comment by ChenYilong** [comment]
你看下你navigationVC有没有重写push方法。在那里面控制的。
