### ISSUE TITLE
在1.17.0版本和最新的1.25.0都出现presentVC的时候tabbar整体上移问题

### ISSUE THREAD

**Issue by zcc2o** [ChenYilong/CYLTabBarController#375]
在1.17.0版本和最新的1.25.0都出现presentVC的时候tabbar整体上移问题，测试机型 iphoneX 模拟器 和iPhone7 真机
![QQ20190528-185307-HD](https://user-images.githubusercontent.com/24406932/58473257-b5f16480-817a-11e9-9027-d8e99f971f9b.gif)
![Uploading WeChat7fd38c1eb9d2341a8e8bad5ca99bedd6.png…]()
![Uploading WeChat7a5f2aa3ab3bf50f3456ca3f4a05954e.png…]()

**Comment by ChenYilong** [comment]
跟强制横屏有关，加微信细聊，chenyilong1010

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/376

**Comment by ChenYilong** [comment]
[present时tabbar上移.zip](https://github.com/ChenYilong/CYLTabBarController/files/3228133/present.tabbar.zip)

**Comment by ChenYilong** [comment]
1.26.0版本已经修复，添加新的API：

1.26.0 add new API cyl_forceUpdateInterfaceOrientation fix #376 fix #375

[present时tabbar上移bug-fixed.zip](https://github.com/ChenYilong/CYLTabBarController/files/3229641/present.tabbar.bug-fixed.zip)

**Comment by ChenYilong** [comment]
![](http://ww2.sinaimg.cn/large/006tNc79ly1g3i1krc1wwj30kj15ttcs.jpg)
