### ISSUE TITLE
Lottie 动画是否执行的问题

### ISSUE THREAD

**Issue by meilbn** [ChenYilong/CYLTabBarController#378]
![enter image description here](http://i68.tinypic.com/ifyhoo.jpg)

----------

<p align="center">
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec"><img src="https://img.shields.io/badge/Pod-GetLatestVersion-green.svg?style=flat"></a>
<a href=""><img src="https://img.shields.io/badge/Swift-compatible-orange.svg"></a>
<a href=""><img src="https://img.shields.io/badge/platform-iOS%208.0%2B-ff69b5152950834.svg"></a>
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/LICENSE"><img src="https://img.shields.io/badge/license-MIT-green.svg?style=flat"></a>
</p>

<p align="center">
<a href="https://github.com/ChenYilong/iOSBlog/issues/21"><img src="https://img.shields.io/static/v1.svg?label=QQ%E3%80%81Telegram%20Group&color=blue&message=%E7%82%B9%E5%87%BB%E8%8E%B7%E5%8F%96QQ%E3%80%81Telegram%E7%BE%A4%E4%BF%A1%E6%81%AF&color=green"></a>
</p>

<p align="center">
<a href="https://twitter.com/stevechen1010"><img src="https://img.shields.io/twitter/url/http/shields.io.svg?style=social&maxAge=2592000"></a>
<a href="http://weibo.com/luohanchenyilong"><img src="http://i67.tinypic.com/wbulbr.jpg"></a>
</a><a href="https://t.me/CYLTabBarController"><img src="http://i66.tinypic.com/of2hbn.jpg"></a></a> 
</p>

----------

## Base Info for this issue 

 1. Version：1.25.0
 2. Language of App ：Objective-C
 4. iOS System Version：iOS12
 5. Prototype（是否是真机）：YES，模拟器也一样
 6. Issue Type：Q-A

## 1. How to reproduce the problem.

在可以延迟登录的 App 里面，点击某些操作，或者，像点击底部 TabBar 中的“我的”的时候，要求用户登录，这样的话，``UITabBarControllerDelegate`` 的 ``- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController`` 方法会判断是否已登录，没有登录的话，就会弹出登录界面，这个方法返回 NO，但是如下图所以，Lottie 动画还是会执行，但是标签页并没有选中“我的”。

<img width="385" alt="Screenshot 2019-05-29 at 19 26 15" src="https://user-images.githubusercontent.com/3370355/58553490-a855e080-8247-11e9-9a61-44aff388522a.png">

## 2. Please help me in this way.

如果 ``- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController`` 方法返回 NO，Lottie 动画并不执行。

## 3. Here is a Demo. 

Demo 已发至邮箱。

## 4. Here is my Debug log

----------

<p align="center"><a href="http://weibo.com/u/1692391497?s=6uyXnP" target="_blank"><img border="0" src="http://service.t.sina.com.cn/widget/qmd/1692391497/b46c844b/1.png"/></a></a>

**Comment by ChenYilong** [comment]
收到，今天发布版本修复下。

**Comment by meilbn** [comment]
感谢，我现在也在尝试修改源码，但是出现别的问题。再试试自己项目里面修改下是否能避免。期待新版本。

微博@iOS程序犭袁 <notifications@github.com> 于2019年5月29日周三 下午8:34写道：

**Comment by ChenYilong** [comment]
我看了下你的demo，你的写法有问题，添加如下的代码既可，Lottie也考虑到的该场景，已经尝试可以满足你的需求。


 ```Objective-C
#pragma mark - UITabBarControllerDelegate

- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController {
    BOOL should = ![((CYLBaseNavigationController *)viewController).topViewController isKindOfClass:[MineViewController class]];
//缺少了下面这一行的代码，如下代码用来同步是否选中的状态。
    [[self cyl_tabBarController] updateSelectionStatusIfNeededForTabBarController:tabBarController shouldSelectViewController:viewController shouldSelect:should];
    return should;
}
 ```

**Comment by meilbn** [comment]
感谢，看来是我没仔细看头文件，这样写的确可以的。👍

微博@iOS程序犭袁 <notifications@github.com> 于2019年5月30日周四 上午3:53写道：

**Comment by meilbn** [comment]
现在发现一个新的问题，字典中都设置了 CYLTabBarLottieSize（如 24），但是第一个 tabBarItem 的 lottie 图片大小还是 22，第二个大小是指定的。

**Comment by ChenYilong** [comment]
```Objective-C
+ (NSArray<NSDictionary *> *)tabBarItemsAttributesForController {
    return @[@{
                CYLTabBarItemTitle : @"Discover",
                CYLTabBarLottieURL : [NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:@"discover" ofType:@"json"]],
                CYLTabBarLottieSize : [NSValue valueWithCGSize:CGSizeMake(40, 40)],
                },
             @{
                CYLTabBarItemTitle : @"Mine",
                CYLTabBarLottieURL : [NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:@"mine" ofType:@"json"]],
                CYLTabBarLottieSize : [NSValue valueWithCGSize:CGSizeMake(40, 40)],
                }];
}
 ```

![](http://ww1.sinaimg.cn/large/006tNc79gy1g3papxk2hbj30n01dsjrc.jpg)

**Comment by meilbn** [comment]
真奇怪，公司项目里面第一个就是没成功的，Demo 里面是可以的。
抱歉，我自己再看看，不是库的问题。。。

**Comment by ChenYilong** [comment]
![](http://ww3.sinaimg.cn/large/006tNc79ly1g4567nfujyj30u01yyqc9.jpg)
