### ISSUE TITLE
报错 最新版

### ISSUE THREAD

**Issue by wufengshou** [ChenYilong/CYLTabBarController#379]
![enter image description here](http://i68.tinypic.com/ifyhoo.jpg)

----------
![image](https://user-images.githubusercontent.com/13453816/58937589-6c6dce80-87a5-11e9-983e-d4778a6d210b.png)

<p align="center">
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec"><img src="https://img.shields.io/badge/Pod-GetLatestVersion-green.svg?style=flat"></a>
<a href=""><img src="https://img.shields.io/badge/Swift-compatible-orange.svg"></a>
<a href=""><img src="https://img.shields.io/badge/platform-iOS%208.0%2B-ff69b5152950834.svg"></a>
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/LICENSE"><img src="https://img.shields.io/badge/license-MIT-green.svg?style=flat"></a>
</p>

<p align="center">
<a href="https://github.com/ChenYilong/iOSBlog/issues/21"><img src="https://img.shields.io/static/v1.svg?label=QQ%E3%80%81Telegram%20Group&color=blue&message=%E7%82%B9%E5%87%BB%E8%8E%B7%E5%8F%96QQ%E3%80%81Telegram%E7%BE%A4%E4%BF%A1%E6%81%AF&color=green"></a>
</p>

<p align="center">
<a href="https://twitter.com/stevechen1010"><img src="https://img.shields.io/twitter/url/http/shields.io.svg?style=social&maxAge=2592000"></a>
<a href="http://weibo.com/luohanchenyilong"><img src="http://i67.tinypic.com/wbulbr.jpg"></a>
</a><a href="https://t.me/CYLTabBarController"><img src="http://i66.tinypic.com/of2hbn.jpg"></a></a> 
</p>

----------

## Base Info for this issue 

 1. Version：Latest Version as [here](https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec) 
 2. Language of App ：Objective-C/Swift
 4. iOS System Version：iOS12
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 4. Here is my Debug log

----------

<p align="center"><a href="http://weibo.com/u/1692391497?s=6uyXnP" target="_blank"><img border="0" src="http://service.t.sina.com.cn/widget/qmd/1692391497/b46c844b/1.png"/></a></a>

**Comment by ChenYilong** [comment]
对照下Lottie集成的步骤
https://github.com/ChenYilong/CYLTabBarController/issues/341

贴下podfile，我看你怎么pod集成方式。

**Comment by ChenYilong** [comment]
Xcode11 ？

**Comment by wufengshou** [comment]
嗯 xcode11  
    pod 'CYLTabBarController'
    pod 'lottie-ios'

**Comment by ChenYilong** [comment]
```Objective-C
//Podfile
#pod 'CYLTabBarController', '~> 1.24.1'        # [CN]默认不依赖Lottie [EN]Do not depend on lottie by default
pod 'CYLTabBarController/Lottie', '~> 1.24.1' # [CN]依赖Lottie库 [EN] Depend on lottie 
 ```

**Comment by wufengshou** [comment]
iOS 13 会打印一堆 错误

**Comment by wufengshou** [comment]
好的 谢谢

**Comment by ChenYilong** [comment]
打印错误近期会修复

**Comment by ChenYilong** [comment]
1.27.0版本已经发布，支持了iOS13的 Dark Mode ，修复了控制台输出大量警告。 详情：https://github.com/ChenYilong/CYLTabBarController/issues/386
