### ISSUE TITLE
两个tabBarButton + 一个发布按钮情况 苹果自适应偏移中间按钮点击相应区域 可以在Q - A里提一下

### ISSUE THREAD

**Issue by dymost** [ChenYilong/CYLTabBarController#38]
苹果提高左右手使用体验 故意设置点击区域偏移
将发布按钮曾经前置, 使其相应层前置
[self bringSubviewToFront:发布按钮];

这个坑可以单独提出来

之前有说明,现在没了.可以加一下

**Comment by ChenYilong** [comment]
将发布按钮曾经前置, 使其相应层前置
[self bringSubviewToFront:发布按钮];


这句话，没听懂

**Comment by dymost** [comment]
中间按钮,点击区域偏移,github无法加载示意图片,给你发邮件了
不好意思,回复迟了.

**Comment by dymost** [comment]
在 2016-04-14 16:35:10，"微博@iOS程序犭袁" <notifications@github.com> 写道：


将发布按钮曾经前置, 使其相应层前置
[self bringSubviewToFront:发布按钮];

这句话，没听懂

**Comment by ChenYilong** [comment]
@dymost  v1.5.1版本对该问题做了优化，可以保证不会有偏移了。
