### ISSUE TITLE
iOS13下 cyl_tabImageView 获取存在问题，可能无法获取

### ISSUE THREAD

**Issue by cwwise** [ChenYilong/CYLTabBarController#381]
![enter image description here](http://i68.tinypic.com/ifyhoo.jpg)

----------

<p align="center">
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec"><img src="https://img.shields.io/badge/Pod-GetLatestVersion-green.svg?style=flat"></a>
<a href=""><img src="https://img.shields.io/badge/Swift-compatible-orange.svg"></a>
<a href=""><img src="https://img.shields.io/badge/platform-iOS%208.0%2B-ff69b5152950834.svg"></a>
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/LICENSE"><img src="https://img.shields.io/badge/license-MIT-green.svg?style=flat"></a>
</p>

<p align="center">
<a href="https://github.com/ChenYilong/iOSBlog/issues/21"><img src="https://img.shields.io/static/v1.svg?label=QQ%E3%80%81Telegram%20Group&color=blue&message=%E7%82%B9%E5%87%BB%E8%8E%B7%E5%8F%96QQ%E3%80%81Telegram%E7%BE%A4%E4%BF%A1%E6%81%AF&color=green"></a>
</p>

<p align="center">
<a href="https://twitter.com/stevechen1010"><img src="https://img.shields.io/twitter/url/http/shields.io.svg?style=social&maxAge=2592000"></a>
<a href="http://weibo.com/luohanchenyilong"><img src="http://i67.tinypic.com/wbulbr.jpg"></a>
</a><a href="https://t.me/CYLTabBarController"><img src="http://i66.tinypic.com/of2hbn.jpg"></a></a> 
</p>

----------

## Base Info for this issue 

UIControl+CYLTabBarControllerExtention 中 cyl_tabImageView

 1. Version：Latest Version as [v1.21.x](https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec) 
 2. Language of App ：Objective-C
 4. iOS System Version：iOS13
 5. Prototype（是否是真机）：NO
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A
Bug
## 1. How to reproduce the problem.

在工程demo MainTabBarController.h中
```
- (void)tabBarController:(UITabBarController *)tabBarController didSelectControl:(UIControl *)control 
  这个地方代码
 animationView = [control cyl_tabImageView];
```
如果当前 TabbarItem 是选中状态 点击之后可以获取 animationView，如果当前TabbarItem是未选中状态 点击获取到animationView 值为nil，在iOS12上表现正常。

## 2. Please help me in this way.

应该都能获取到才是正常的。在iOS12下都可以正常获取到
## 3. Here is a Demo. 
最新版本上就可以复现

## 4. Here is my Debug log

```
iOS13下
- (UIImageView *)cyl_tabImageView {
    for (UIImageView *subview in self.subviews) {
        if ([subview cyl_isTabImageView]) {
            return (UIImageView *)subview;
        }
    }
    return nil;
}

当前未选中的情况
(lldb) po self.subviews
<__NSArrayM 0x6000026de130>(
<UIVisualEffectView: 0x7fe6054956c0; frame = (0 0; 93.75 48); userInteractionEnabled = NO; layer = <CALayer: 0x6000028962a0>> clientRequestedContentView effect=<UIVibrancyEffect: 0x600002a3ce30> style=UIBlurEffectStyleSystemChromeBackground vibrancyStyle=_UIVibrancyEffectStyleFill,
<LOTAnimationView: 0x7fe605547220; frame = (29.6667 7; 22 22); userInteractionEnabled = NO; layer = <CALayer: 0x600002875fc0>>
)

当前选中的情况
(lldb) po self.subviews
<__NSArrayM 0x6000026d9ce0>(
<UIVisualEffectView: 0x7fe6054956c0; frame = (0 0; 93.75 48); userInteractionEnabled = NO; layer = <CALayer: 0x6000028962a0>> clientRequestedContentView effect=<UIVibrancyEffect: 0x600002a3ce30> style=UIBlurEffectStyleSystemChromeBackground vibrancyStyle=_UIVibrancyEffectStyleFill,
<LOTAnimationView: 0x7fe605547220; frame = (29.6667 7; 22 22); userInteractionEnabled = NO; layer = <CALayer: 0x600002875fc0>>,
<UITabBarSwappableImageView: 0x7fe6054954d0; frame = (29.6667 7; 22 22); hidden = YES; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x600002896240>>,
<UITabBarButtonLabel: 0x7fe605495230; frame = (30.3333 30.6667; 20.6667 12); text = '首页'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x600000ba93b0>>
)

```

----------

<p align="center"><a href="http://weibo.com/u/1692391497?s=6uyXnP" target="_blank"><img border="0" src="http://service.t.sina.com.cn/widget/qmd/1692391497/b46c844b/1.png"/></a></a>

**Comment by ChenYilong** [comment]
这个问题在看了，有什么好的建议欢迎加微信聊chenyilong1010

**Comment by ChenYilong** [comment]
除了上述的办法，也可以直接升级到 v1.27.0，详情见：

https://github.com/ChenYilong/CYLTabBarController/issues/386
