### ISSUE TITLE
求助，iPad Pro三代显示有点小问题

### ISSUE THREAD

**Issue by ieliwb** [ChenYilong/CYLTabBarController#387]
用的最新版，见图，高度不对，怎么解决呢，大佬
<img width="1303" alt="屏幕快照 2019-06-15 14 27 27" src="https://user-images.githubusercontent.com/2177409/59547953-e1958c80-8f79-11e9-8d61-fca256d8f42b.png">

**Comment by ChenYilong** [comment]
可以自定义高度

**Comment by ieliwb** [comment]
谢谢，我急着发版看了源码，改好了，iPad去掉tabbar字效果更好，哈哈

        //全面屏 20 非 0
        float padding = 8;
        if (@available(iOS 11.0, *)) {
            if (self.window.safeAreaInsets.bottom>0) {
                padding = 12;
            }
        }
        
        self.tabBarViewController = [[CYLTabBarController alloc] initWithViewControllers:@[nav2,nav1,nav3,nav4] tabBarItemsAttributes:@[tabBarItem2,tabBarItem1,tabBarItem3,tabBarItem4] imageInsets:UIEdgeInsetsMake(padding, 0, -padding, 0) titlePositionAdjustment:UIOffsetMake(0, MAXFLOAT)];        

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2019-06-15 at 21 21 59](https://user-images.githubusercontent.com/2177409/59814326-7962f400-9347-11e9-9f25-f0c642cf4c47.png)

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/396
