### ISSUE TITLE
Tabbar的黑线，能否自定义颜色？

### ISSUE THREAD

**Issue by freesan44** [ChenYilong/CYLTabBarController#388]
![enter image description here](http://i68.tinypic.com/ifyhoo.jpg)

----------

<p align="center">
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec"><img src="https://img.shields.io/badge/Pod-GetLatestVersion-green.svg?style=flat"></a>
<a href=""><img src="https://img.shields.io/badge/Swift-compatible-orange.svg"></a>
<a href=""><img src="https://img.shields.io/badge/platform-iOS%208.0%2B-ff69b5152950834.svg"></a>
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/LICENSE"><img src="https://img.shields.io/badge/license-MIT-green.svg?style=flat"></a>
</p>

<p align="center">
<a href="https://github.com/ChenYilong/iOSBlog/issues/21"><img src="https://img.shields.io/static/v1.svg?label=QQ%E3%80%81Telegram%20Group&color=blue&message=%E7%82%B9%E5%87%BB%E8%8E%B7%E5%8F%96QQ%E3%80%81Telegram%E7%BE%A4%E4%BF%A1%E6%81%AF&color=green"></a>
</p>

<p align="center">
<a href="https://twitter.com/stevechen1010"><img src="https://img.shields.io/twitter/url/http/shields.io.svg?style=social&maxAge=2592000"></a>
<a href="http://weibo.com/luohanchenyilong"><img src="http://i67.tinypic.com/wbulbr.jpg"></a>
</a><a href="https://t.me/CYLTabBarController"><img src="http://i66.tinypic.com/of2hbn.jpg"></a></a> 
</p>

----------

## Base Info for this issue 

 1. Version：Latest Version as [here](https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec) 
 2. Language of App ：Objective-C
 4. iOS System Version：iOS12
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to reproduce the problem.

//以下方法能把顶部黑线隐藏掉，但目前的需求是改变黑线的颜色，请问能否实现
[mainCon hideTabBadgeBackgroundSeparator];
我通过以上方式看到获取的是一个UIImageView，所以我把ImageView的填充颜色改为红色，但还是没法生效，具体代码如下：
   [mainCon.tabBar layoutIfNeeded];
   UIImageView * tabBadgeBackgroundSeparatorImgView = mainCon.tabBar.cyl_tabBadgeBackgroundSeparator;
   [tabBadgeBackgroundSeparatorImgView setImage:[tabBadgeBackgroundSeparatorImgView.image imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate]];
   tabBadgeBackgroundSeparatorImgView.tintColor = kRedColor;

## 4. Here is my Debug log

----------

<p align="center"><a href="http://weibo.com/u/1692391497?s=6uyXnP" target="_blank"><img border="0" src="http://service.t.sina.com.cn/widget/qmd/1692391497/b46c844b/1.png"/></a></a>

**Comment by ChenYilong** [comment]
tabbar 的 background image 有值时，shadow image设置才会生效。

**Comment by ChenYilong** [comment]
demo演示代码里注释里说明了。

**Comment by freesan44** [comment]
> demo演示代码里注释里说明了。

您好，谢谢回复！
如果我修改[[UITabBar appearance] setBackgroundImage:[[UIImage alloc] init]];
这里只是修改背景图，我想实现的需求是，【tabbar顶部的黑线/灰线修改成红色】

**Comment by ChenYilong** [comment]
自定义shadowImageview不生效吗？

**Comment by freesan44** [comment]
> 自定义shadowImageview不生效吗？

可以了，谢谢!

**Comment by ChenYilong** [comment]
怎么生效的，上面的代码做了什么改动？
贴下用法吧。

**Comment by freesan44** [comment]
> 怎么生效的，上面的代码做了什么改动？
> 贴下用法吧。

UIGraphicsBeginImageContextWithOptions(CGSizeMake(kCutUIWidth(375), 1), 0, [UIScreen mainScreen].scale);
   [UIColorFromRGB(0xe6e6e6) set];
   UIRectFill(CGRectMake(0, 0,kCutUIWidth(375), 1));
   UIImage *ColorImg = UIGraphicsGetImageFromCurrentImageContext();
   UIGraphicsEndImageContext();
   [[UITabBar appearance] setShadowImage:ColorImg];

自定义一张1像素高度的纯颜色的image，然后放在setShadowImage里面

**Comment by ChenYilong** [comment]
你上面的代码有一个前提，必须调用了下面的代码：
因为背景是空的话，设置分割线也没用。

         [[UITabBar appearance] setBackgroundImage:someImage];

**Comment by freesan44** [comment]
是的

**Comment by ChenYilong** [comment]
//去除 TabBar 自带的顶部阴影
    需要使用 -[CYLTabBarController hideTabBarShadowImageView] 

见README

并参考：https://github.com/ChenYilong/CYLTabBarController/issues/386
