### ISSUE TITLE
badge不偏码

### ISSUE THREAD

**Issue by ShenYj** [ChenYilong/CYLTabBarController#393]
最左侧的`badge`垂直方向有点偏
![屏幕快照 2019-07-01 下午5 15 26](https://user-images.githubusercontent.com/15159923/60424911-f2096080-9c23-11e9-8e05-b777da8b85ed.png)

**Comment by ChenYilong** [comment]
这个是demo里自定义了offset的效果，用于演示的。你可以修改代码，去掉offset即可。

**Comment by ShenYj** [comment]
> 这个是demo里自定义了offset的效果，用于演示的。你可以修改代码，去掉offset即可。

响应的够快哦

**Comment by ChenYilong** [comment]
以响应快著称，哈哈哈，开了推动。
