### ISSUE TITLE
'UIUserInterfaceStyle' is unavailable: not available on iOS

### ISSUE THREAD

**Issue by DylanHoHo** [ChenYilong/CYLTabBarController#395]
你好，大神！
我在通过pod导入项目后，CYLTabBarController库里报错：'UIUserInterfaceStyle' is unavailable: not available on iOS，这是什么原因？请大牛指点 @

**Comment by ChenYilong** [comment]
我发布了1.28.2你更新下就好了

**Comment by ChenYilong** [comment]
iOS13上的新API用旧Xcode打开会有问题

**Comment by DylanHoHo** [comment]
xcode是最新的，iOS系统也是最新的，谢谢大神解决，明天我试试，在反馈结果




发自我的iPhone

------------------ Original ------------------
