### ISSUE TITLE
Lottie动画默认状态图片冲突

### ISSUE THREAD

**Issue by liuzhuoming** [ChenYilong/CYLTabBarController#397]
![enter image description here](http://i68.tinypic.com/ifyhoo.jpg)

----------

<p align="center">
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec"><img src="https://img.shields.io/badge/Pod-GetLatestVersion-green.svg?style=flat"></a>
<a href=""><img src="https://img.shields.io/badge/Swift-compatible-orange.svg"></a>
<a href=""><img src="https://img.shields.io/badge/platform-iOS%208.0%2B-ff69b5152950834.svg"></a>
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/LICENSE"><img src="https://img.shields.io/badge/license-MIT-green.svg?style=flat"></a>
</p>

<p align="center">
<a href="https://github.com/ChenYilong/iOSBlog/issues/21"><img src="https://img.shields.io/static/v1.svg?label=QQ%E3%80%81Telegram%20Group&color=blue&message=%E7%82%B9%E5%87%BB%E8%8E%B7%E5%8F%96QQ%E3%80%81Telegram%E7%BE%A4%E4%BF%A1%E6%81%AF&color=green"></a>
</p>

<p align="center">
<a href="https://twitter.com/stevechen1010"><img src="https://img.shields.io/twitter/url/http/shields.io.svg?style=social&maxAge=2592000"></a>
<a href="http://weibo.com/luohanchenyilong"><img src="http://i67.tinypic.com/wbulbr.jpg"></a>
</a><a href="https://t.me/CYLTabBarController"><img src="http://i66.tinypic.com/of2hbn.jpg"></a></a> 
</p>

----------

## Base Info for this issue 

加了Lottie动画之后，所有的Item图片都是动画的效果，未选中的默认状态图片不显示了
![效果图](http://note-1255605989.cosgz.myqcloud.com/tabbar.gif)

 1. Version：1.28.1
 2. Language of App ：Swift
 4. iOS System Version：iOS12
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 1. How to reproduce the problem.

代码基本照着demo翻译的，一切正常。只是在添加了Lottie动画之后，默认图片不显示了。

## 4. Here is my Debug log

----------

<p align="center"><a href="http://weibo.com/u/1692391497?s=6uyXnP" target="_blank"><img border="0" src="http://service.t.sina.com.cn/widget/qmd/1692391497/b46c844b/1.png"/></a></a>

**Comment by ChenYilong** [comment]
Lottie动画模式下，
默认选中状态的图片需要Lottie的json文件第一帧支持。
如果想用Lottie同时也想用静态图片做未选中状态的展示，
就需要自己实现了，方法比较复杂。在这里有介绍 https://github.com/ChenYilong/CYLTabBarController/issues/341

推荐让UI去支持，更新Lottie文件来支持。参考demo里的Lottie文件。

**Comment by liuzhuoming** [comment]
谢谢，刚用我的json文件放入demo中立马发现了问题，刚想关闭issue。o(￣▽￣)ｄ
还有个小问题，就是我中间的这个大按钮怎么往上面一些，我没有自定义plusbutton.

**Comment by liuzhuoming** [comment]
谢谢！(゜-゜)つロ 干杯~-
