### ISSUE TITLE
[bug]: PlusButton push 新界面, 返回 tabbar 透明色失效!

### ISSUE THREAD

**Issue by xiaohange** [ChenYilong/CYLTabBarController#405]
![enter image description here](http://i68.tinypic.com/ifyhoo.jpg)

----------

<p align="center">
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec"><img src="https://img.shields.io/badge/Pod-GetLatestVersion-green.svg?style=flat"></a>
<a href=""><img src="https://img.shields.io/badge/Swift-compatible-orange.svg"></a>
<a href=""><img src="https://img.shields.io/badge/platform-iOS%208.0%2B-ff69b5152950834.svg"></a>
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/LICENSE"><img src="https://img.shields.io/badge/license-MIT-green.svg?style=flat"></a>
</p>

<p align="center">
<a href="https://github.com/ChenYilong/iOSBlog/issues/21"><img src="https://img.shields.io/static/v1.svg?label=QQ%E3%80%81Telegram%20Group&color=blue&message=%E7%82%B9%E5%87%BB%E8%8E%B7%E5%8F%96QQ%E3%80%81Telegram%E7%BE%A4%E4%BF%A1%E6%81%AF&color=green"></a>
</p>

<p align="center">
<a href="https://twitter.com/stevechen1010"><img src="https://img.shields.io/twitter/url/http/shields.io.svg?style=social&maxAge=2592000"></a>
<a href="http://weibo.com/luohanchenyilong"><img src="http://i67.tinypic.com/wbulbr.jpg"></a>
</a><a href="https://t.me/CYLTabBarController"><img src="http://i66.tinypic.com/of2hbn.jpg"></a></a> 
</p>

----------

## Base Info for this issue 

 1. Version：Latest Version as [here](https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec) 
 2. Language of App ：Objective-C/Swift
 4. iOS System Version：iOS12
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 4. Here is my Debug log

----------

<p align="center"><a href="http://weibo.com/u/1692391497?s=6uyXnP" target="_blank"><img border="0" src="http://service.t.sina.com.cn/widget/qmd/1692391497/b46c844b/1.png"/></a></a>

**Comment by ChenYilong** [comment]
设置透明色的代码贴一下吧

**Comment by xiaohange** [comment]
@ChenYilong 
```
[[UITabBar appearance] setBackgroundImage:[[UIImage alloc] init]];
    [[UITabBar appearance] setBackgroundColor:[UIColor clearColor]];
```
这个是在 tabbar 初始设置的, 在 plus 按钮 push 出去, 再返回时, 背景色莫名奇妙的变成了 vc 的背景色

**Comment by ChenYilong** [comment]
demo能复现吗？贴一下demo能复现的代码吧

**Comment by xiaohange** [comment]
@ChenYilong 我找到原因了, 我的疏忽在新的界面继承了基类的tabbar 设置, 非常感谢~
