### ISSUE TITLE
关于为什么重写viewControllers

### ISSUE THREAD

**Issue by Mzxer** [ChenYilong/CYLTabBarController#41]
我发现viewControllers的重写方法里的功能，系统大都有实现。为什么不直接利用super调用系统原来的，再添加而外的功能呢？有非要重写的理由吗，水平有限，没看出门道？请指教，谢谢。

**Comment by ChenYilong** [comment]
这里给出了 方案：

https://github.com/ChenYilong/CYLTabBarController/issues/247
