### ISSUE TITLE
self.tabBarItem不正确

### ISSUE THREAD

**Issue by Andy1984** [ChenYilong/CYLTabBarController#43]
在demo中, CYLHomeViewController, `id a = self.tabBarItem;
    id b = self.tabBarController.tabBar.items.firstObject;
    if (a == b) {
        NSLog(@"same");
    } else {
        NSLog(@"not the same");
    }` self.tarBarItem是官方提供用于快速获取当前viewController的tabBarItem, 而在CYLHomeViewController中, b才是真的tabBarItem

**Comment by ChenYilong** [comment]
不好意思，没太懂，你说的“真的tabBarItem”具体指的是？什么才算是“真的”？望详细说下，或者你直接说下一个场景：你希望拿到tabBarItem做什么，然后发现拿的不对，设置也没有效果。

**Comment by Andy1984** [comment]
真的tabBarItem是指， CYLTabBarController的item， 你不是用KVC改变了self.tabBarController吗， 但是你没用KVC改变self.tabBarItem。</br> 具体场景是， 第一个tarBarItem， 双击， 第一个controller的scrollView回滚到最上面， 如同微信一样。我的做法是 `UITarBarItem *firstItem = self.tabBarController.tabBar.items.firstObject;
UIView *firstItemView = [firstItem valueForKey:@"view]";`然后再给这个firstItemView增加double tap手势

**Comment by ChenYilong** [comment]
这个需求可以实现，实现方式见：https://github.com/ChenYilong/CYLTabBarController/issues/359
