### ISSUE TITLE
关于使用过程遇到的问题

### ISSUE THREAD

**Issue by zuocai1993** [ChenYilong/CYLTabBarController#44]
1.我需要指定加号位置时  为什么必须是奇数才能指定？ + (NSUInteger)indexOfPlusButtonInTabBar

**Comment by ChenYilong** [comment]
你这里是有偶数指定plusButton位置的需求吗？之前因为感觉不会有这种需求，所以就限制了，你这里有效果图吗？方便贴下吗？

**Comment by zuocai1993** [comment]
airbnb这个app你可以看下，就是这样的效果。


发自 网易邮箱大师
在2016年05月02日 08:24，微博@iOS程序犭袁 写道:

你这里是有偶数指定plusButton位置的需求吗？之前因为感觉不会有这种需求，所以就限制了，你这里有效果图吗？方便贴下吗？

**Comment by ChenYilong** [comment]
看到了，我马上修改下这个限制，升级一个版本，更新下pod。

**Comment by ChenYilong** [comment]
v1.3.1已经允许Airbnb样式：允许在tabbarItem个数为偶数时指定PlusButton位置，请pod update。

**Comment by zuocai1993** [comment]
大赞


发自 网易邮箱大师
在2016年05月02日 11:15，微博@iOS程序犭袁 写道:

v1.3.1已经允许Airbnb样式：允许在tabbarItem个数为偶数时指定PlusButton位置，请pod update。
