### ISSUE TITLE
UI API called on a background thread: -[UIApplication applicationState]

### ISSUE THREAD

**Issue by MuRanJiangXia** [ChenYilong/CYLTabBarController#453]
![enter image description here](http://i68.tinypic.com/ifyhoo.jpg)

----------

<p align="center">
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec"><img src="https://img.shields.io/badge/Pod-GetLatestVersion-green.svg?style=flat"></a>
<a href=""><img src="https://img.shields.io/badge/Swift-compatible-orange.svg"></a>
<a href=""><img src="https://img.shields.io/badge/platform-iOS%208.0%2B-ff69b5152950834.svg"></a>
<a href="https://github.com/ChenYilong/CYLTabBarController/blob/master/LICENSE"><img src="https://img.shields.io/badge/license-MIT-green.svg?style=flat"></a>
</p>

<p align="center">
<a href="https://github.com/ChenYilong/iOSBlog/issues/21"><img src="https://img.shields.io/static/v1.svg?label=QQ%E3%80%81Telegram%20Group&color=blue&message=%E7%82%B9%E5%87%BB%E8%8E%B7%E5%8F%96QQ%E3%80%81Telegram%E7%BE%A4%E4%BF%A1%E6%81%AF&color=green"></a>
</p>

<p align="center">
<a href="https://twitter.com/stevechen1010"><img src="https://img.shields.io/twitter/url/http/shields.io.svg?style=social&maxAge=2592000"></a>
<a href="http://weibo.com/luohanchenyilong"><img src="http://i67.tinypic.com/wbulbr.jpg"></a>
</a><a href="https://t.me/CYLTabBarController"><img src="http://i66.tinypic.com/of2hbn.jpg"></a></a> 
</p>

----------

## Base Info for this issue 

 1. Version：Latest Version as [here](https://github.com/ChenYilong/CYLTabBarController/blob/master/CYLTabBarController.podspec) 
 2. Language of App ：Swift
 4. iOS System Version：iOS13
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash

## 1. How to reproduce the problem.
快速切换VC就会出现这个Crash

## 4. Here is my Debug log

Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 5810, TID: 1455627, Thread name: (none), Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   CFKYDriverSwift                     0x0000000105099860 -[RCCountly isInBackground] + 56
5   CFKYDriverSwift                     0x0000000105098a94 RCCountlyExceptionHandler + 1628
6   CFKYDriverSwift                     0x0000000104407e80 -[AMapCrashReporter handleUncaughtException:] + 480
7   CFKYDriverSwift                     0x00000001044076a4 AMapUncaughtExceptionHandler + 80
8   CoreFoundation                      0x000000019dd1cc94 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 1227924
9   libobjc.A.dylib                     0x000000019da4534c B39048C3-8395-3DE4-AF4D-ACA3097FDC53 + 25420
10  libc++abi.dylib                     0x000000019daea304 B148BC1F-83C8-34E2-868D-00DB2D9BBB55 + 58116
11  libc++abi.dylib                     0x000000019dae9c58 __cxa_get_exception_ptr + 0
12  libc++abi.dylib                     0x000000019dae9c18 B148BC1F-83C8-34E2-868D-00DB2D9BBB55 + 56344
13  libobjc.A.dylib                     0x000000019da451d0 B39048C3-8395-3DE4-AF4D-ACA3097FDC53 + 25040
14  CoreFoundation                      0x000000019dc24cc8 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 212168
15  CoreServices                        0x000000019e38750c 4631A29A-FFB2-3A9D-95FF-1037507BD066 + 840972
16  Foundation                          0x000000019dfd7908 0DF2911E-80CB-3289-8A1E-ED0913D55A12 + 43272
17  CFKYDriverSwift                     0x0000000105157044 fb1UCM8vZCiE + 356
18  CFKYDriverSwift                     0x000000010515edb4 fbkUVUzGnhkS + 1656
19  CFKYDriverSwift                     0x0000000105154658 fbIiaWxkoUb6 + 308
20  libsystem_pthread.dylib             0x000000019da391ec _pthread_start + 124
21  libsystem_pthread.dylib             0x000000019da3caec thread_start + 8

----------

<p align="center"><a href="http://weibo.com/u/1692391497?s=6uyXnP" target="_blank"><img border="0" src="http://service.t.sina.com.cn/widget/qmd/1692391497/b46c844b/1.png"/></a></a>

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
