### ISSUE TITLE
IOS13 如何设置tabbar的标题往上移动 

### ISSUE THREAD

**Issue by lilinxuan** [ChenYilong/CYLTabBarController#456]
titlePositionAdjustment 用这个设置的无效。图片位置属性可以移动，文字移动没效果，希望哪位大佬能告知一下，谢谢，好人一生平安~

**Comment by ChenYilong** [comment]
贴一下怎么设置的 titlePositionAdjustment,看下是不是设置的有问题.

**Comment by LJW008** [comment]
@ @ChenYilong 你好，用UITabBarAppearance 设置 ShadowImage,后 CYLTabBarItemTitlePositionAdjustment设置的偏移量就失效了，是时机问题不对吗

**Comment by lilinxuan** [comment]
@ChenYilong 找到原因了，但不知道怎么改，搞了半天无果。项目里有QMUI的问题。希望大佬可以帮忙搞一下咯。非常感谢

**Comment by lilinxuan** [comment]
@ChenYilong 找到问题所在了。QMUI的分类 UIView+QMUITheme.h 的 [self performSelector:setter withObject:value]这行代码注释掉就行了

**Comment by lilinxuan** [comment]
@ChenYilong 还有#import "UITabBar+QMUI.h" 里的load方法注释掉

**Comment by ChenYilong** [comment]
@Lee0820 Lee 你看看是否修复了你所说的问题: 
https://github.com/ChenYilong/CYLTabBarController/commit/94725e58eec7971ee03f7fbe1722728120980db8
