### ISSUE TITLE
button间的间距问题

### ISSUE THREAD

**Issue by ulongx** [ChenYilong/CYLTabBarController#48]
![tabbar](https://cloud.githubusercontent.com/assets/1161624/15139901/3a5e5d04-16cb-11e6-96cf-7af2e839060f.png)
这个上面的间距，是怎么处理的？

**Comment by ChenYilong** [comment]
创建背景图片时，让图片大一个像素，下载下最新的Demo，在config类里看下做法。

**Comment by ulongx** [comment]
嗯，非常完美，👍
