### ISSUE TITLE
[bug]:在lottie和selectedCover配合使用下，在隐藏selectedCover后item上会出现一个白色图片

### ISSUE THREAD

**Issue by zhong2020** [ChenYilong/CYLTabBarController#480]
iOS 系统13.3.1
1、正常情况
![image](https://user-images.githubusercontent.com/10590616/76716361-ec7c8800-676a-11ea-8fbe-f25364962df3.png)
2、selectedCover的显示
![image](https://user-images.githubusercontent.com/10590616/76716376-f9997700-676a-11ea-8ecf-494b49834ea6.png)
3、在隐藏selectedCover之后出现了问题
![image](https://user-images.githubusercontent.com/10590616/76716405-0ae28380-676b-11ea-91d0-12bb69aa22ad.png)
4、查看图层多了UITabBarSwappableImageView
![image](https://user-images.githubusercontent.com/10590616/76716426-19309f80-676b-11ea-9703-053d03d9c01e.png)
目前我的解决方法是，在显示selectedCover，隐藏UITabBarSwappableImageView
```
- (void)setSelectedCoverShow:(BOOL)show {
    UIControl *selectedTabButton = [self.viewControllers[0].tabBarItem cyl_tabButton];
    [selectedTabButton cyl_replaceTabButtonWithNewView:self.selectedCover
                                                  show:show];
    //解决隐藏selectedCover后，会有一个白色图片出现的问题
    selectedTabButton.cyl_tabImageView.hidden = YES;
    if (show) {
        [self addScaleAnimationOnView:self.selectedCover.imageView repeatCount:1];
    }
}
```

**Comment by ChenYilong** [comment]
查看最新demo,发现你说的情况无法复现.不加上面的隐藏代码,也能正常显示
