### ISSUE TITLE
是否可以加上iOS9的一些特性呢

### ISSUE THREAD

**Issue by devtofu** [ChenYilong/CYLTabBarController#49]
不知道这个框架最低有哪个系统的程序在用。

再使用 POP 特性的时候 ，返回的 ViewController 加上 __kindof ，强转的话就不会报警告了。

**Comment by ChenYilong** [comment]
最低版本是iOS7。你说的是`UIViewController (CYLTabBarControllerExtention)`这个分类里的  `-cyl_popSelectTabBarChildViewControllerForClassType` 这个系列的方法吗？

**Comment by devtofu** [comment]
恩，是的。

**Comment by ChenYilong** [comment]
关于警告，有代码，或者截图没？因为返回值就是UIViewController，不会是UINavigationController，应该不用强转啊！

**Comment by devtofu** [comment]
@ChenYilong  这样。
![image](https://cloud.githubusercontent.com/assets/12134966/15245097/32f9fcda-1937-11e6-8e8a-b4f17fc84893.png)

**Comment by ChenYilong** [comment]
v1.4.1已修复该问题，更新下。

**Comment by devtofu** [comment]
nice..
