### ISSUE TITLE
tabbarcontroller中设置self.selectedIndex = 2;没有效果

### ISSUE THREAD

**Issue by czl0325** [ChenYilong/CYLTabBarController#497]
最新版本

 2. Language of App ：Objective-C
 4. iOS System Version：iOS13.4.1
 5. Prototype（是否是真机）：YES

## 1. How to reproduce the problem.

tabbarcontroller中设置self.selectedIndex = 2;没有效果，出现🔴类名与方法名：-[CYLTabBar(CYLTabBarControllerExtention) cyl_tabBarButtonWithTabIndex:]（在第145行），描述：*** -[__NSArrayM objectAtIndexedSubscript:]: index 2 beyond bounds for empty array

`- (instancetype)init {
    if (self == [super initWithViewControllers:[self viewControllersForTabBar] tabBarItemsAttributes:[self tabBarItemsAttributesForTabBar]]) {
    }
    return self;
}`
初始化是5个viewcontrollers，使用是没问题，不知道为何？

**Comment by czl0325** [comment]
留个群号，我图片上传不上来

**Comment by ChenYilong** [comment]
demo有演示，要加延迟才能生效
