### ISSUE TITLE
setImageInsets 问题

### ISSUE THREAD

**Issue by everblacks** [ChenYilong/CYLTabBarController#50]
使用setImageInsets之后如果重复点击同一个item 图片就会越变越小

**Comment by ChenYilong** [comment]
暂无法复现你说的这种情况，可以贴一段代码，或者发一个Demo给我，我看下怎么回事。我的邮箱：luohanchenyilong@163.com

**Comment by ChenYilong** [comment]
该问题已经确认不是库的bug。

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/383
