### ISSUE TITLE
[Q-A]使用方法询问：设置tabbar背景颜色为透明时，tabbaritem的图标虚化

### ISSUE THREAD

**Issue by fuchenxi** [ChenYilong/CYLTabBarController#501]

**Comment by fuchenxi** [comment]
![image](https://user-images.githubusercontent.com/24308071/82799771-2a093a00-9ead-11ea-8de8-443a775a5887.png)

**Comment by ieliwb** [comment]
大佬解决了吗

**Comment by ChenYilong** [comment]
@ieliwb @fuchenxi 是用什么方式设置的透明?
贴一下设置透明的代码?
