### ISSUE TITLE
[Q-A]使用方法询问：

### ISSUE THREAD

**Issue by Bofearless** [ChenYilong/CYLTabBarController#508]
![image](https://user-images.githubusercontent.com/16445320/85268455-1e5b6400-b4a9-11ea-8ee3-17640fbb58ca.png)
这种效果现在支持吗？有文字，文字还需要更新，具体用法怎么使用呢？谢谢！

**Comment by ChenYilong** [comment]
中间的button是完全自定义的，所以可以实现。

**Comment by Bofearless** [comment]
> 中间的button是完全自定义的，所以可以实现。

已经实现，感谢回复，谢谢！
