### ISSUE TITLE
podspec不是最新代码？

### ISSUE THREAD

**Issue by sujiewen** [ChenYilong/CYLTabBarController#52]
podspec不是最新代码？

**Comment by ChenYilong** [comment]
是啊，为什么这么说，最新版是v1.5.1

**Comment by jeffreylyg** [comment]
@ChenYilong pod install 后是1.4.4, pod search看最新的也是1.4.4

**Comment by ChenYilong** [comment]
pod search 的是本机的pod仓库，你需要更新pod仓库再搜索，或者直接到官网搜索最新版 https://cocoapods.org ，使用 pod update命令升级下本地仓库。
