### ISSUE TITLE
请问下如何实现从 A - tabbar 的控制器界面  直接返回到B - tabbar 界面

### ISSUE THREAD

**Issue by zuocai1993** [ChenYilong/CYLTabBarController#53]
其中有一个方法setselectindex      我在返回的时候给tabbar 设置了这个属性没有起作用，  然后我尝试先popRoot  在设置selectIndex   这样他只能到A tabbar  无法跳转到B tabbar    请问有什么好的解决办法，请指教

**Comment by lipengda** [comment]
遍历viewcontrollers 返回

**Comment by ChenYilong** [comment]
@zuocai1993  看下这个接口能否满足你的需求
`UIViewController+CYLTabBarControllerExtention.h` 中的：

 ```Objective-C
/*!
 * Pop 到当前 `NavigationController` 的栈底，并改变 `TabBarController` 的 `selectedViewController` 属性，并将被选择的控制器作为返回值返回。
 @param index 需要选择的控制器在 `TabBar` 中的 index。
 @return 最终被选择的控制器。
 @attention 注意：方法中的参数和返回值都是 `UIViewController` 的子类，但并非 `UINavigationController` 的子类。
 */
- (UIViewController *)cyl_popSelectTabBarChildViewControllerAtIndex:(NSUInteger)index;
 ```

**Comment by zuocai1993** [comment]
找到方法了，谢谢




发自 网易邮箱大师
在2016年06月20日 17:00，lipengda 写道:

遍历viewcontrollers 返回

**Comment by ChenYilong** [comment]
能否解决你的问题？

**Comment by zuocai1993** [comment]
大赞，必须符合要求


发自 网易邮箱大师
在2016年06月20日 22:49，微博@iOS程序犭袁 写道:

能否解决你的问题？
