### ISSUE TITLE
badge无法自定义

### ISSUE THREAD

**Issue by TLcv** [ChenYilong/CYLTabBarController#54]
请问tabBarItem的badge能自定义吗

**Comment by ChenYilong** [comment]
自定义可以搭配另外一个库，进行 https://github.com/DeveloperLx/LxTabBadgePoint

**Comment by ChenYilong** [comment]
v1.13.0已经可自定义View来展示 TabBarItem 角标，默认支持未读小红点。详情参考文档。一打开APP就显示红点，已经在Demo中演示。
