### ISSUE TITLE
删除CYLPlusButton这个类

### ISSUE THREAD

**Issue by Sky891028** [ChenYilong/CYLTabBarController#57]
tabbar就无响应事件了。。 开始还以为是我代码的问题

**Comment by Sky891028** [comment]
如果不添加plus buttont tabBar是无法点击的 我使用1.4.5版本 OK 这个是否是1.5版本的缺陷

**Comment by ChenYilong** [comment]
更新下pod，v1.5.4已经修复。

**Comment by Sky891028** [comment]
It's work  
tks!

**Comment by ChenYilong** [comment]
这里有解决方案：https://github.com/ChenYilong/CYLTabBarController/issues/247
