### ISSUE TITLE
[bug]: 版本1.29.1 不支持 bitcode

### ISSUE THREAD

**Issue by dong4255** [ChenYilong/CYLTabBarController#570]
### CYLTabBarController.podspec
第14行
`s.pod_target_xcconfig = {
   'DEFINES_MODULE' => 'YES',
   'ENABLE_BITCODE' => 'NO'
 }`

这里的 ENABLE_BITCODE 被你设置成了 NO

**Comment by ChenYilong** [comment]
升级到 v1.29.2即可.
