### ISSUE TITLE
[bug]: iOS适配问题

### ISSUE THREAD

**Issue by DryCocoaDry** [ChenYilong/CYLTabBarController#573]
iOS15 设置 backgroundImage 无效

**Comment by weweco123** [comment]
遇到类似的问题，TabBar的背景变成透明。使用的版本是 1.29.2 。
1、在 iOS 15 系统，我的App TabBar上面有4个controller，在这4个controller 上面点击切换controller，TabBar的背景有的会自动变成透明，有的不会。
2、在iOS 14系统以下，不会出现任何问题。

如何解决？

**Comment by DryCocoaDry** [comment]
亲测可行：
if #available(iOS 15.0, *) {
            
            let appearance = UITabBarAppearance()
            appearance.backgroundImageContentMode = .scaleToFill
            appearance.backgroundImage = img
            tarBarVC.tabBar.scrollEdgeAppearance = appearance
            tarBarVC.tabBar.standardAppearance = appearance
            
}else {
            tarBarVC.tabBar.backgroundImage = img
}

**Comment by weweco123** [comment]
Nice，非常感谢，节日快乐。
