### ISSUE TITLE
自定义pickerView，放进项目中 无法交互？

### ISSUE THREAD

**Issue by Dreamle** [ChenYilong/CYLTabBarController#58]
最近我自定义了一个pickerView，放进项目中 无法交互？但是我单独拉出来，新建一个项目就可以正常交互？请问是什么情况？

**Comment by ChenYilong** [comment]
详细描述下，最好能给个demo，让我调试下，luohanchenyilong@163.com

**Comment by Dreamle** [comment]
我下载了新版本  确实可以交互了 非常感谢！不知道是哪里的原因？可以告诉一下吗？我也想多学习学习

**Comment by Dreamle** [comment]
你好，还有一个问题  就是我放在你的程序中就可以交互 但是现在将你最新版的拉进我的项目中还是无法交互（项目现在已经纯净的只剩几个控制器了），能否将你的邮箱告诉我，我发你邮箱里，你看一下

**Comment by Dreamle** [comment]
看到你邮箱了

**Comment by ChenYilong** [comment]
看了您的demo，这个不是我框架的问题，我试了下，把我的框架换成系统的tabbar，也是不能交互的，请看下，您的自定义pickerView的实现，应该是这个view的实现有问题。最好自己重新建一个demo，先确保自定义pickerView能交互。

**Comment by Dreamle** [comment]
找到原因了  非常感谢您，以后有问题 随时请教您。

**Comment by ChenYilong** [comment]
好的

**Comment by yoyoFan** [comment]
新手看不懂，怎么破
