### ISSUE TITLE
could you be nice enough to show me how to use it with swift? thanks

### ISSUE THREAD

**Issue by xiaoao** [ChenYilong/CYLTabBarController#6]
I'm a novice at ios dev, could you be nice enough to show me how to use it with swift? thanks

**Comment by ChenYilong** [comment]
reference： [《从头开始swift2.1 仿搜材通项目（三） 主流框架Tabbed的搭建》]( http://www.jianshu.com/p/c5bc2eae0f55?nomobile=yes )

**Comment by EaseLi** [comment]
《从头开始swift2.1 仿搜材通项目（三） 主流框架Tabbed的搭建》 里按钮事件 buttonClicked 没响应，请问是什么问题？

**Comment by ChenYilong** [comment]
还没看，稍候我跟进下。

**Comment by ChenYilong** [comment]
文档中已经添加了说明，并且仓库中也给出了一个演示Demo 


 [《文档地址》]( https://github.com/ChenYilong/CYLTabBarController#在-swift-项目中使用-cyltabbarcontroller
 ) 


仓库中给出了一个Swift Demo，文件夹叫做 Example-Swift。

具体的编写步骤参考热心网友提供的教程： [《从头开始swift2.1 仿搜材通项目（三） 主流框架Tabbed的搭建》]( http://www.jianshu.com/p/c5bc2eae0f55?nomobile=yes )

**Comment by ChenYilong** [comment]
@EaseLi 这个问题在文档中也有详细解释： [《文档地址》]( https://github.com/ChenYilong/CYLTabBarController#在-swift-项目中使用-cyltabbarcontroller)
