### ISSUE TITLE
如何实现点击PlusButton以模态视图的形式或者自定义转场动画弹出一个ViewController

### ISSUE THREAD

**Issue by ultimatevegance** [ChenYilong/CYLTabBarController#60]
你好，我是一个iOS开发 新手，最近使用您的CYLTabBarController加入到我自己的项目当中，实现了一个我自己的tabbar（如下图），但是我想实现点击中间的plusbutton以模态视图的形式弹出一个ViewController，或者加入自定义的转场动画效果。不知道如何实现。希望大侠指点指点。[](url)
<img width="372" alt="screen shot 2016-06-30 at 3 57 35 pm" src="https://cloud.githubusercontent.com/assets/9568495/16481658/f3e05ef4-3ede-11e6-96c5-184538fa368b.png">

**Comment by ChenYilong** [comment]
在Demo中的CYLPlusButtonSubclass中做如下处理：

 ```Objective-C
- (void)clickPublish {
    CYLTabBarController *tabBarController = [self cyl_tabBarController];
    UIViewController *viewController = tabBarController.selectedViewController;
    UIViewController *blueViewController = [[UIViewController alloc] init];
    blueViewController.view.backgroundColor = [UIColor blueColor];
    [viewController presentViewController:blueViewController animated:YES completion:nil];
}
 ```

**Comment by ultimatevegance** [comment]
你好我使用了这种方法，` [capPlusButton addTarget:capPlusButton action:@selector(clickStartCap) forControlEvents:UIControlEventTouchUpInside];`我之前addTarget 后面写的是self 结果一致没达到效果，改成capPlusButton就可以了。谢谢你，CYLTabBarController拓展性非常高而且简化了很多。

**Comment by kiven-man** [comment]
你好 我试了下 - (void)clickPublish {
    CYLTabBarController *tabBarController = [self cyl_tabBarController];
    UIViewController *viewController = tabBarController.selectedViewController;
    UIViewController *blueViewController = [[UIViewController alloc] init];
    blueViewController.view.backgroundColor = [UIColor blueColor];
    [viewController presentViewController:blueViewController animated:YES completion:nil];
} 并不起作用 ；tabBarController 运行时显示nill

**Comment by ChenYilong** [comment]
版本号多少？你是否把CYLTabBarController设为window的rootViewController？

**Comment by kiven-man** [comment]
是这样的 我把另外一个 ViewController=tabBarControllerConfig.tabBarController 然后设置ViewController为window的rootViewController 但是项目上的原因我不能 直接设置tabBarControllerConfig.tabBarController为window的rootViewController

**Comment by kiven-man** [comment]
如果如果 必须要把tabBarControllerConfig.tabBarController 设置为rootViewController 那CYLTabBarController 支持
![a6c833f3-a265-4452-ba9e-f21517889aa2](https://cloud.githubusercontent.com/assets/8351523/16646352/2fd7affc-445c-11e6-9898-d25aedc436bc.png)吗

**Comment by ChenYilong** [comment]
这个场景没考虑到，但按理说只要你设置了那两个数组，这个分类方法总是能返回CYLTabBarController给你，能发个Demo来吗。

**Comment by ChenYilong** [comment]
luohanchenyilong@163.com ，我帮你看下是不是我的Lib没覆盖你这种情况。
