### ISSUE TITLE
如何每次都刷新或重建中间的plusbutton?

### ISSUE THREAD

**Issue by kangyeting** [ChenYilong/CYLTabBarController#61]
中间的"+"btn, 需要转态来改变,怎么实时改变呢?

**Comment by ChenYilong** [comment]
在这个库中，如果你需要自定义plusButton，那么你需要子类化`CYLPlusButton`得到一个自定义的类，在Demo中是`CYLPlusButtonSubclass`，所以你可以通过操作你自定义的类来实时改变，或者通过操作 `    CYLExternPlusButton`这个extern常量来达到效果，这个常量定义在CYLPlusButton中，所以你需要`#import "CYLPlusButton.h"`。

**Comment by kangyeting** [comment]
多谢! 太感谢您了

**Comment by yixiaofeng** [comment]
我也遇到这个问题 不是太明白 可以详细说下怎么修改 CYLExternPlusButton 或者 在我自定义的类里怎么刷新呢

**Comment by ChenYilong** [comment]
单例的话，自己维护状态即可。
