### ISSUE TITLE
如何实现动画效果的 TabbarController

### ISSUE THREAD

**Issue by devtofu** [ChenYilong/CYLTabBarController#62]
可否能支持点击 tabBarItem 有动画效果。

例如下图这种：

![tab-bar-icons-iphone-ramotion-animation-interface-design](https://cloud.githubusercontent.com/assets/12134966/16510754/62021c96-3f7b-11e6-9afc-b4e78fb74cd0.gif)

**Comment by devtofu** [comment]
上图上一个 Swift 的开源库，[这个是地址](https://github.com/Ramotion/animated-tab-bar)

**Comment by ChenYilong** [comment]
这个需求得好好看看，动画的定制需求太高，如果接口预留不合适，无法满足绝大部分人的需求，就会很鸡肋，还不如不加，这个需要排期来调研下开发者对动画的需求。

**Comment by fuchenxi** [comment]
对的, 就是这个效果, 不过是让image放大, title不变化, 有考虑加入这个功能吗?

**Comment by hllGitHub** [comment]
http://www.jianshu.com/p/13fe42796153 看这个，在这个的基础上加了动画

**Comment by hllGitHub** [comment]
不过这样的订制效果太差了。主流的动画效果可以设置下，然后开放出参数，方便订制

**Comment by ChenYilong** [comment]
已经支持，https://github.com/ChenYilong/CYLTabBarController/issues/128
