### ISSUE TITLE
在没有plusButton的app中，无法实现该效果：在仅显示图标时，使图标自动居中

### ISSUE THREAD

**Issue by MerryGOOT** [ChenYilong/CYLTabBarController#63]
```Objective-C
- (NSArray *)tabBarItemsAttributesForController
{
    NSDictionary *firstTabBarItemsAttributes = @{CYLTabBarItemImage : @"home_normal",
                                                 CYLTabBarItemSelectedImage : @"home_highlight"};


NSDictionary *secondTabBarItemsAttributes = @{CYLTabBarItemImage : @"mycity_normal",
                                              CYLTabBarItemSelectedImage : @"mycity_highlight"};

return @[firstTabBarItemsAttributes,
         secondTabBarItemsAttributes];


}
 ```

不传标题，没有效果啊

**Comment by ChenYilong** [comment]
我这里可以啊，你有Demo吗，发一个我帮你看看，哪里出问题了 luohanchenyilong@163.com

**Comment by vincent-cihan** [comment]
我也是只显示图标不能居中，两种只显示图标居中的方式都试了都不可以，不知道上面的问题是什么情况

**Comment by ChenYilong** [comment]
你的意思是确实只显示了图标，但是图标没有自动居中？

**Comment by vincent-cihan** [comment]
恩，是的

**Comment by ChenYilong** [comment]
@MerryGOOT 检查下你的VC中title的设置方法。

 ```Objective-C
 self.navigationItem.title = @"首页(3)"; //✅sets navigation bar title.The right way to set the title of the navigation
    self.tabBarItem.title = @"首页23333";   //❌
    //self.title = @"首页1";                //❌
 ```

**Comment by ChenYilong** [comment]
@vincent-cihan 发个截图来，或者发个demo来 luohanchenyilong@163.com

**Comment by vincent-cihan** [comment]
不好意思刚才突然开会去了，这样可以么
![2016-07-05 2 57 59](https://cloud.githubusercontent.com/assets/16432385/16576326/feff59c6-42c0-11e6-90e7-c571fc14c9ab.png)
![2016-07-05 2 57 49](https://cloud.githubusercontent.com/assets/16432385/16576360/43d6680a-42c1-11e6-8c7d-d6829b578425.png)

**Comment by ChenYilong** [comment]
@MerryGOOT @vincent-cihan 忘了问了，你们都使用的什么版本的？请更新到最新版 1.5.4 ，这是新版本的特性，旧版本是没有这个特性的。

**Comment by vincent-cihan** [comment]
好的，我看了一下，pod确实是1.4.4版本而不是最新版，我去更新试试，谢谢

**Comment by vincent-cihan** [comment]
昨天pod更新了最新版(1.5.4)，图标还是无法居中，Demo可以，tabbar高度可以改变，但图标居中的两种方式都无效。
我完全使用了Demo中的CYLTabBarControllerConfig类进行设置的，不知道到底哪里有问题。
是否还有会有其他的第三方库或类会影响tabbar居中的方法？

**Comment by ChenYilong** [comment]
写个Demo发我，luohanchenyilong@163.com

**Comment by vincent-cihan** [comment]
Demo已发，多谢指导，麻烦了

**Comment by vincent-cihan** [comment]
忘了说了，关键设置在这个位置

**Comment by vincent-cihan** [comment]
忘了说了，关键位置在这
![2016-07-06 11 53 17](https://cloud.githubusercontent.com/assets/16432385/16607119/5288f7f0-4370-11e6-93d9-7060211adb77.png)

**Comment by ChenYilong** [comment]
@MerryGOOT @vincent-cihan  已修复，pod update到 1.5.5版本，修复了在没有plusButton的app中，无法实现该效果：在仅显示图标时，并使图标自动居中。

**Comment by vincent-cihan** [comment]
好的，多谢
