### ISSUE TITLE
作为StoryBoard的initial VC进行集成时如果同是重写`-application:didFinishLaunchingWithOptions`修改rootViewController会Crash

### ISSUE THREAD

**Issue by CoderPby** [ChenYilong/CYLTabBarController#64]
**前提**：程序的Initial View Controller是TabBarVc，继承自CYLTabBarVc
**复现路径**：程序一启动就判断用户有没有登录，没登录设置KeyWindow的RootVc为登录控制器
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions 
{
    //判断用户是否已经登录，没登录直接显示登录界面
    if (!userIsLogin) {
        LoginViewController *login = [LoginViewController new];
        self.window.rootViewController = login;
    }
    return YES;
}
```
**崩溃断点**:CYLTabBarController.m
```
- (void)dealloc {
    // KVO反注册
    [self.tabBar removeObserver:self forKeyPath:@"swappableImageViewDefaultOffset"];
}
```
**崩溃日志**：

> Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <CustomTabBarController 0x124851800> for the key path "swappableImageViewDefaultOffset" from <UITabBar 0x1247bb090> because it is not registered as an observer.

**Comment by ChenYilong** [comment]
怎么关了？

**Comment by CoderPby** [comment]
不好意思，刚才排版有点问题，修改了一下

**Comment by CoderPby** [comment]
我去，修改失败，我再写一下..

**Comment by CoderPby** [comment]
**前提**：程序的Initial View Controller是TabBarVc，继承自CYLTabBarVc
**复现路径**：程序一启动就判断用户有没有登录，没登录设置KeyWindow的RootVc为登录控制器
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions 
{
    //判断用户是否已经登录，没登录直接显示登录界面
    if (!userIsLogin) {
        LoginViewController *login = [LoginViewController new];
        self.window.rootViewController = login;
    }
    return YES;
}
```
**崩溃断点**:CYLTabBarController.m
```
- (void)dealloc {
    // KVO反注册
    [self.tabBar removeObserver:self forKeyPath:@"swappableImageViewDefaultOffset"];
}
```
**崩溃日志**：

> Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <CustomTabBarController 0x124851800> for the key path "swappableImageViewDefaultOffset" from <UITabBar 0x1247bb090> because it is not registered as an observer.

**Comment by ChenYilong** [comment]
能否发一个Demo给我，我帮你调试下，看时哪里出了问题luohanchenyilong@163.com

**Comment by CoderPby** [comment]
已发送，请查收

**Comment by ChenYilong** [comment]
看了你的Demo了，你是用的 StoryBoard 进行的 TabBarController 的集成，你 pod update 到1.5.6版本，我做了下兼容。

**Comment by CoderPby** [comment]
好的，感谢！

**Comment by CoderPby** [comment]
![bug](https://cloud.githubusercontent.com/assets/11246642/16679529/dbd54de6-451a-11e6-816f-992909236599.jpg)
还是不行...现在不是崩在dealloc那个方法了。报错如下：

> Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <CustomTabBarController 0x14001de00> for the key path "swappableImageViewDefaultOffset" from <UITabBar 0x13f7b4ae0> because it is not registered as an observer.

**Comment by ChenYilong** [comment]
你的报错信息不是跟之前的一样吗？你确定用的是1.5.6？我在你的Demo基础上集成后，已经不会崩溃了。

**Comment by ChenYilong** [comment]
我基本可以确认是你Xcode的编译缓存的问题，图中crash的64行，正停在1.5.5版本的dealloc方法里。

**Comment by CoderPby** [comment]
我是用**CocoaPods**集成，之前1.5.5Crash的时候，我是把`- (void)dealloc`方法里面的移除观察者那行代码注释（当然是unlock了文件..），后来升级到了1.5.6，我自己的电脑不会，同事的还是一样一直崩溃...重新Clone了项目也一样...后面没辙了换成手动导入才得以解决😂

**Comment by CoderPby** [comment]
自己又写了Demo，新版本确实解决问题了👍
