### ISSUE TITLE
用这个tabBar作为根视图收到通知之后,怎么返回上一个页面

### ISSUE THREAD

**Issue by RabbitBell** [ChenYilong/CYLTabBarController#66]
用这个Tabbar作为根视图, 在某个拥有Nav的界面,接收通知跳转到另一个页面,怎么返回上一个页面. (类似淘宝那种效果).

**Comment by ChenYilong** [comment]
请使用这个接口

`UIViewController+CYLTabBarControllerExtention.h` 中的：

 ```Objective-C
/*!
 * Pop 到当前 `NavigationController` 的栈底，并改变 `TabBarController` 的 `selectedViewController` 属性，并将被选择的控制器作为返回值返回。
 @param index 需要选择的控制器在 `TabBar` 中的 index。
 @return 最终被选择的控制器。
 @attention 注意：方法中的参数和返回值都是 `UIViewController` 的子类，但并非 `UINavigationController` 的子类。
 */
- (UIViewController *)cyl_popSelectTabBarChildViewControllerAtIndex:(NSUInteger)index;
 ```

**Comment by ChenYilong** [comment]
这个需要搭配推送通知的特性去做，推送通知的跳转逻辑，可以参考这里：

https://github.com/ChenYilong/CYLExternalURL


跳转到任意页面：

可以参考：


>         CYLTabBarController *tabBarController = [self cyl_tabBarController];
        UINavigationController *viewController = (UINavigationController *)tabBarController.selectedViewController;
        [viewController pushViewController:plusChildViewController animated:YES];


并搭配下面这个接口：

`UIViewController+CYLTabBarControllerExtention.h` 中的：

 ```Objective-C
/*!
 * Pop 到当前 `NavigationController` 的栈底，并改变 `TabBarController` 的 `selectedViewController` 属性，并将被选择的控制器作为返回值返回。
 @param index 需要选择的控制器在 `TabBar` 中的 index。
 @return 最终被选择的控制器。
 @attention 注意：方法中的参数和返回值都是 `UIViewController` 的子类，但并非 `UINavigationController` 的子类。
 */
- (UIViewController *)cyl_popSelectTabBarChildViewControllerAtIndex:(NSUInteger)index;
 ```
