### ISSUE TITLE
点击某一位置，用cyl_popSelectTabBarChildViewControllerAtIndex跳转到指定的根控制器，但是下面的图片出现两个选中的图片

### ISSUE THREAD

**Issue by a526592191** [ChenYilong/CYLTabBarController#68]
点击某一位置，用cyl_popSelectTabBarChildViewControllerAtIndex跳转到指定的根控制器，但是下面的图片出现两个选中的图片

**Comment by a526592191** [comment]
跳转的控制器的选中图片没有变成未选中状态,同时出现两个选中状态的图片

**Comment by a526592191** [comment]
<img width="409" alt="2016-07-20 10 54 39" src="https://cloud.githubusercontent.com/assets/15828261/16973694/6375ed72-4e68-11e6-979a-42c5e666280a.png">

**Comment by ChenYilong** [comment]
你时跳转到了“发现”还是“爆料”？能提供一个 demo 吗？我帮你看下问题所在。luohanchenyilong@163.com

**Comment by a526592191** [comment]
跳转了发现，[self cyl_popSelectTabBarChildViewControllerAtIndex:3];用这个跳转的

**Comment by ChenYilong** [comment]
提供下版本好，另外你有没有手动指定delegate的代理，爆料按钮点击后和其他item一样也是切换控制器，还是自定义事件？还有就是如果你点击“首页”，爆料能变成未选中状态吗？能提供一个 demo 吗？我帮你看下问题所在。luohanchenyilong@163.com

**Comment by a526592191** [comment]
你好，demo发你邮箱了，不知道这算不算一个bug？

**Comment by a526592191** [comment]
事情比较急，谢谢！

**Comment by ChenYilong** [comment]
ok，我先看下

**Comment by xxxIxxxx** [comment]
- (UIViewController *)cyl_popSelectTabBarChildViewControllerAtIndex:(NSUInteger)index
{
//这里面怎么写啊，，
    return ;
}

**Comment by ChenYilong** [comment]
返回值是index对应的控制器，你拿到了控制器就可以在该控制器的基础上进行push了。

**Comment by ChenYilong** [comment]
v1.6.7已修复。
