### ISSUE TITLE
tabbar背景图片只在6和6s才居中显示,其他的会偏移

### ISSUE THREAD

**Issue by owenWang123** [ChenYilong/CYLTabBarController#69]
只在6或者6s上是正常显示的, 变成别的就会出现这种类似问题,请问怎么解决
![44119b06-6680-eeca-ddc5-82eaebd764b8](https://cloud.githubusercontent.com/assets/16203373/16974359/70e82898-4e6e-11e6-88ba-8c760ba5521a.png)

**Comment by ChenYilong** [comment]
帮忙提供更多信息，比如版本号，这样描述我无法定位问题，能否提供以下demo，我帮你看下，luohanchenyilong@163.com

**Comment by ChenYilong** [comment]
暂时没有发现这个问题
