### ISSUE TITLE
添加选择背景色

### ISSUE THREAD

**Issue by bawn** [ChenYilong/CYLTabBarController#7]
希望能添加选中背景色的功能 
<img width="409" alt="screen shot 2015-10-28 at 9 21 56 am" src="https://cloud.githubusercontent.com/assets/7238866/10777333/5d7811c8-7d55-11e5-88be-8cb11bbeaf90.png">

**Comment by ChenYilong** [comment]
我已经在 Demo 中添加了如何实现该功能的代码：
详情见appdelegate 类中下面方法的实现：

 ```Objective-C
    [self setUpTabBarItemTextAttributes];
 ```

效果如下：
![simulator screen shot 2015 10 28 11 44 32](https://cloud.githubusercontent.com/assets/2911921/10779397/34956b0a-7d6b-11e5-82d9-fa75aa34e8d0.png)

**Comment by ChenYilong** [comment]
详情可参考
 [ ***iOS - Customize UITabBar Appearance*** ](http://jslim.net/blog/2014/05/05/ios-customize-uitabbar-appearance/)

**Comment by bawn** [comment]
谢谢
