### ISSUE TITLE
TabBarItemImage 如果是非正方形（带Title的切图）的，不能自动居中

### ISSUE THREAD

**Issue by xiafb** [ChenYilong/CYLTabBarController#71]
TabBarItemImage 如果是非正方形（带Title的切图）的，不能自动居中

**Comment by ChenYilong** [comment]
自动居中调整的是PlusButton的中心点坐标，把你的PlusButton背景调成显眼的颜色，比如红色，看下是否是居中的。

**Comment by xiafb** [comment]
我直接在CYLTabBarControllerDemoForWeib这个demo中把第一个TabBarItemImage设成非正方形的，结果其它几个正方形的TabBarItemImage的也都不居中显示了
![2016-07-28 11 28 07](https://cloud.githubusercontent.com/assets/5442499/17200395/68ab2654-54b7-11e6-90eb-d876ecab1345.png)

**Comment by ChenYilong** [comment]
由于我在实现时，只考虑到了四个图标尺寸是一致的，所以我会先调整第一个图标的位置，然后后面的图标会默认按照第一个图标的偏移量来调整。请描述下你想达到的效果。我可以调整下实现方案。

**Comment by xiafb** [comment]
上图中，如果把后面三个图标同第一个图标大小的非正方形图标后，所有图标都向上偏移了（未居中）。效果就是：如果设计师给的是带title的非正方形图标，也能居中就好了（虽然也能通过setImageInsets来实现）
![2016-07-28 11 50 13](https://cloud.githubusercontent.com/assets/5442499/17200741/78ca9e2c-54ba-11e6-9200-1487280dce2f.png)

**Comment by ChenYilong** [comment]
不好意思没听太明白你的需求，需要我做点什么？
