### ISSUE TITLE
建议，CYLPlusButtonSubclass 中的plusButton 方法写成单例会好些

### ISSUE THREAD

**Issue by riverlj** [ChenYilong/CYLTabBarController#73]
这样就可以从外部获取到自定义的元素。

**Comment by ChenYilong** [comment]
PlusButton是 CYLTabBarController 的子视图，生命周期一致，CYLTabBarController 在 App 生命周期内是不会被销毁的，所以 PlusButton 也是不会被销毁的，你就可以把他当做单例来用，CYLTabBarController 的访问可以通过 `CYLTabBarController *tabBarController = [self cyl_tabBarController];` ，plusButton 你可以使用 `CYLPlusButtonSubclass *plusButton = CYLExternPlusButton;`,这两个方式都等同于单例的初始化方法。

**Comment by riverlj** [comment]
@ChenYilong 知晓了，感谢回复～
