### ISSUE TITLE
如何使用storyboard直接生成CYLTabBarController？而不是在appdelegate内的代码创建？

### ISSUE THREAD

**Issue by leo524891010** [ChenYilong/CYLTabBarController#74]

**Comment by ChenYilong** [comment]
支持的，你这里有一个Demo ，见CYLTabBarControllerTestDemo文件夹： https://github.com/ChenYilong/CYLDeallocBlockExecutor

**Comment by leo524891010** [comment]
那请问 在原始的tabviewcontroller里面 可以在storyboard里面做vc的关系链接 比如这样：
![screen shot 2016-08-06 at 11 01 11 am](https://cloud.githubusercontent.com/assets/4951023/17458445/49e4e556-5bc5-11e6-910d-ea7fc8f67912.png)

那现在的话 是必须要用setViewControllers api 来建立连接吗？

**Comment by ChenYilong** [comment]
对，要用`-setViewControllers:` API，我重写了setViewControllers方法。

**Comment by leo524891010** [comment]
@ChenYilong 太感谢了 这个库比美国的任何的tabbar库都要好

**Comment by ChenYilong** [comment]
多谢使用，多多提bug给我，有好的建议也欢迎直接提。
