### ISSUE TITLE
TabBar消失了！

### ISSUE THREAD

**Issue by xiafb** [ChenYilong/CYLTabBarController#75]
在某个tab的二级页面，执行以下代码代码pop到一级页面后，tabbar为什么会被隐藏掉了？
VC2 _vc = [[VC2 alloc] init];
__weak __typeof(&_self)weakSelf = self;
 vc.ablock = ^{
       [weakSelf.navigationController popViewControllerAnimated:YES];
 };
 UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:vc];
 [self presentViewController:nav animated:YES completion:nil];

**Comment by ChenYilong** [comment]
请贴下更详细的代码，以及截图。如果有可能，推荐发个Demo给我，我帮你看下： luohanchenyilong@163.com

**Comment by xiafb** [comment]
Demo已发到这个邮箱，谢谢

**Comment by ChenYilong** [comment]
ik

**Comment by hongdong** [comment]
@ChenYilong 这个问题解决了吗？同样出现这个问题

**Comment by ChenYilong** [comment]
https://github.com/ChenYilong/CYLTabBarController/issues/241
