### ISSUE TITLE
如果我用KVO写的夜间模式,怎么可以通知中间按钮修改图片就是那个加号

### ISSUE THREAD

**Issue by Gx952743985** [ChenYilong/CYLTabBarController#76]
或者你有什么建议没,我只想写一个夜间模式

**Comment by ChenYilong** [comment]
你可以像访问单例那样访问中间按钮，详见： https://github.com/ChenYilong/CYLTabBarController/issues/73

**Comment by Gx952743985** [comment]
6的飞起,不过我用一句话搞定了:  [CYLExternPlusButton setBackgroundImage:[UIImage imageNamed:@"Unknown"] forState:UIControlStateNormal];
还有就是tabBarItem的字体颜色如何改变

**Comment by ChenYilong** [comment]
改变颜色的话，我这里有个简单粗暴的方法：遍历viewControllers属性，一个一个改。 `[self cyl_tabBarController].viewControllers`。暂时还没想到什么优雅的方式改。
