### ISSUE TITLE
如何更改默认选中的视图控制器？

### ISSUE THREAD

**Issue by xxxIxxxx** [ChenYilong/CYLTabBarController#77]
项目中要默认显示第三个，不知道怎么更改。求助！

**Comment by xxxIxxxx** [comment]
tabBarController.selectedIndex = 2;
    这个不管用

**Comment by ChenYilong** [comment]
你点击PlusButton是不是会像其他TabBarItem一样跳转到控制器？

**Comment by xxxIxxxx** [comment]
不是，我不要中间的那个按钮。
就是简单五个视图，然后进入应用默认就是显示第三个。

**Comment by xxxIxxxx** [comment]
比如说 微信    我进入微信就要显示   通讯录 而不是微信

**Comment by ChenYilong** [comment]
你代码怎么写的，贴代码，有可能的话发Demo给我，luohanchenyilong@163.com

**Comment by xxxIxxxx** [comment]
已发送

**Comment by xxxIxxxx** [comment]
tabBar.selectedIndex = 2;   系统tabbar不是可以设置选中视图控制器。
比如说 我的tabbar里有五个视图控制器 ，我进入应用默认要显示第一个，但是我想让他显示第三个。

帮忙看下吧，谢谢了。
有点急。。。

**Comment by xxxIxxxx** [comment]
已解决
在AppDelegate.m 中加入
    tabBarControllerConfig.tabBarController.selectedIndex = 2;

**Comment by Xlff** [comment]
为何要在appdelegate中设置才有效果，在configure中设置不起作用呢
