### ISSUE TITLE
self.title 会改变tabbaritem.title 为什么

### ISSUE THREAD

**Issue by lyc59621** [ChenYilong/CYLTabBarController#78]

**Comment by ChenYilong** [comment]
iOS系统内部实现就是这么实现的。

**Comment by lyc59621** [comment]
那我要怎么写 才不会影响item的title     self.navigationItem.title    这样？？ 不太好吧

**Comment by ChenYilong** [comment]
这样写为什么不太好？

**Comment by lyc59621** [comment]
有没有方法可以让self.title 方法不影响  tabBarItem.title 这个方法

**Comment by ChenYilong** [comment]
这是系统实现，暂时没有好的方法。

**Comment by lizhaojie001** [comment]
为什么我改变成self.title和不该之前 self.navigationItem.title 都不显示呢

**Comment by ChenYilong** [comment]
请检查 是否是将该设置放在了 `viewDidLoad` 方法中，建议放在 `viewWillAppear` 中, 详情参考 http://stackoverflow.com/a/10982774

**Comment by ChenYilong** [comment]
这时候ViewController还没有push出来，对应navigation相关属性都是nil，你在这里设置是没用的，请等 ViewController push 出来后设置。

**Comment by lizhaojie001** [comment]
![vc](https://cloud.githubusercontent.com/assets/14847521/18154811/81bdd3e6-703a-11e6-878b-2a9a1004740f.png)

**Comment by ChenYilong** [comment]
为什么不在ViewController push出来后再设置？出于什么考虑？

**Comment by ChenYilong** [comment]
你po下navigationController属性

**Comment by lizhaojie001** [comment]
tabbar的item和这个不一样么,我想和tabbar一起设置,self.title

**Comment by lizhaojie001** [comment]
![vcc](https://cloud.githubusercontent.com/assets/14847521/18154898/2fa78b50-703b-11e6-8f1a-e102732543c8.png)

**Comment by lizhaojie001** [comment]
我在navigation下的根控制器设置了title就显示了

**Comment by ChenYilong** [comment]
具体怎么做的，贴个代码出来吧。

**Comment by lizhaojie001** [comment]
![1](https://cloud.githubusercontent.com/assets/14847521/18155134/1b35b320-703d-11e6-9706-5af9b0aaf056.png)
![2](https://cloud.githubusercontent.com/assets/14847521/18155135/1b621f78-703d-11e6-8002-6ae240982e73.png)
![3](https://cloud.githubusercontent.com/assets/14847521/18155139/1bf422b0-703d-11e6-9461-eda9aca6f9a4.png)
![4](https://cloud.githubusercontent.com/assets/14847521/18155138/1bef028a-703d-11e6-82aa-76aebd71960c.png)
![5](https://cloud.githubusercontent.com/assets/14847521/18155136/1bd9db62-703d-11e6-929b-758ef3b1221b.png)
![6](https://cloud.githubusercontent.com/assets/14847521/18155137/1bda2cac-703d-11e6-86da-b021cebd12df.png)

**Comment by lizhaojie001** [comment]
应该就是在加载过程中,没有加载navi的时候已经加载了根控制器的viewdidload;了
