### ISSUE TITLE
[BXTRepairButton registerPlusButton]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by Jason318** [ChenYilong/CYLTabBarController#81]
你好，BXTRepairButton集成自CYLPlusButton，但是一旦运行，就会报这个错误，什么问题？

**Comment by Jason318** [comment]
版本号是1.6.0

**Comment by ChenYilong** [comment]
请问 BXTRepairButton 是否继承自 CYLPlusButton

**Comment by Jason318** [comment]
是的，很纳闷，为什么会出现这种状况

**Comment by Jason318** [comment]
可能昨天我更新CocoaPods的问题，发现不仅这个库调用方法有问题，调用其他库里面的方法也会提示unrecognized selector sent to instance错误，求教

**Comment by ChenYilong** [comment]
贴代码，或者给Demo：luohanchenyilong@163.com

**Comment by Jason318** [comment]
好了，发过去了，您查看一下

**Comment by ChenYilong** [comment]
没看到

**Comment by goink** [comment]
这个问题可以清空工程derived data，卸载app，重新编译安装解决。应该是从老版本cocoapods更新到新版本造成的。
