### ISSUE TITLE
tabbar错乱了。我也不知道我是怎么弄的

### ISSUE THREAD

**Issue by ruichou** [ChenYilong/CYLTabBarController#82]
![simulator screen shot 2016 8 30 6 10 44](https://cloud.githubusercontent.com/assets/15194925/18085302/2b28f820-6edd-11e6-986e-9b4858a57d4d.png)

**Comment by ChenYilong** [comment]
复现步骤，以及Demo发我, luohanchenyilong@163.com

**Comment by ChenYilong** [comment]
估计是图片没加载上
