### ISSUE TITLE
iOS10从加号按钮进入的VC点击导航栏崩溃

### ISSUE THREAD

**Issue by lmssll** [ChenYilong/CYLTabBarController#83]
在CYLTabBarController的自带Demo中将plusChildViewController 和 indexOfPlusButtonInTabBar 方法的注释去掉，点击加号按钮切换到PlusChildViewController之后点击导航栏崩溃. 错误日志如下:
**\* Assertion failure in -[UIGestureGraphEdge initWithLabel:sourceNode:targetNode:directed:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3599.5/Source/GestureGraph/UIGestureGraphEdge.m:25

请您帮忙看一下，谢谢啦~

**Comment by ChenYilong** [comment]
iOS10下面，还没测试，稍后我测试确认下

**Comment by SHIMLY-GitHub** [comment]
我这边也出现这个问题了 不知道怎么搞了

**Comment by a526592191** [comment]
这个怎么解决？？？？我也是这个问题

**Comment by a526592191** [comment]
有没有谁已经解决了的

**Comment by zingwin** [comment]
没有找到问题所在

**Comment by cconecode** [comment]
@ChenYilong 测试好了吗 ，现在都有这个 bug

**Comment by hi-guy** [comment]
同问

**Comment by hugolubingshen** [comment]
@hi-guy 没用的，这样不是凸起的按钮

**Comment by nididege** [comment]
我解决了。

按照 https://huang.sh/2016/09/wkwebview%E5%9C%A8ios-10%E4%B8%8Acrash-invalid-parameter-not-satisfying-targetnode/ 的思路来解决的。是一样的root cause, 按照这个修复就好。

具体是CYLPlusButtonSubclassing的这里：
+ (void)load {
    [super registerSubclass];
}

改成链接里的dispatch_after延迟2秒的做法就好了。

**Comment by devtofu** [comment]
@nididege 我加了延迟，+ 号按钮就绘制不上去了，能否贡献下代码

**Comment by hugolubingshen** [comment]
@nididege 我这样改的，跟楼上一样，+号没有出来，下面是我的代码
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSUInteger createDelay = 0;
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(createDelay * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
             [super registerPlusButton];
        });
        
    });
}

**Comment by nididege** [comment]
@devtofu 是的，加了延迟同时需要控制显示TabBarController的时机。我是在我的项目里直接改的，在显示TabBarController之前有启动图等，所以直接延迟没有问题。

如果用github的这个示例代码，需要在AppDelegate.m里，setRootViewController时也延迟。
如`+ (void)load`的地方延迟了1秒，setRootViewController时就需要延迟1.5秒。

这个issue最好的修复是等主人来修改load CYLPlusChildViewController的时机

**Comment by ChenYilong** [comment]
@nididege  你如果有解决方案，可以提下PR。如果测试没问题的话，就可以Merge，然后我更新下 CocoaPods 版本。

**Comment by hugolubingshen** [comment]
@nididege 不行，setRootViewController延迟的话，启动页load完就会奔溃

**Comment by nididege** [comment]
@ChenYilong 好的。 @hugolubingshen 看我上面贴的zip，要临时设置一个RootViewController的。

**Comment by devtofu** [comment]
@nididege 用你这方法果然管用 - -！！！

**Comment by hugolubingshen** [comment]
@nididege 没看到你有设置历史的rootVc啊，AppDelegate只有这点代码
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // 设置主窗口,并设置根控制器
//    self.window = [[UIWindow alloc]init];
//    self.window.frame = [UIScreen mainScreen].bounds;
    
    [self performSelector:@selector(showTabBarController) withObject:self afterDelay:1.5f];
    [self.window makeKeyAndVisible];
    [self customizeInterface];
    return YES;
}

- (void)showTabBarController
{
    CYLTabBarControllerConfig *tabBarControllerConfig = [[CYLTabBarControllerConfig alloc] init];
    [self.window setRootViewController:tabBarControllerConfig.tabBarController];
}

- (void)customizeInterface {
    [self setUpNavigationBarAppearance];
}

**Comment by hugolubingshen** [comment]
自己设置了一下临时的 VC,解决了 @nididege  谢谢分享

**Comment by nididege** [comment]
@hugolubingshen 我是偷懒直接在项目设置的General里选了Main storyboard做Main Interface.

**Comment by hugolubingshen** [comment]
@nididege 难怪没看出来，我都不用storyboard的😂

**Comment by ChenYilong** [comment]
这里有一个更简单的方法来解决这个问题： 

见文档：

<https://github.com/ChenYilong/CYLTabBarController#第四步可选创建自定义的形状不规则加号按钮>

@hugolubingshen  @nididege @devtofu 你们试一下。
