### ISSUE TITLE
CYLTabBarController与RESideMenu兼容性的问题

### ISSUE THREAD

**Issue by Zss1990** [ChenYilong/CYLTabBarController#84]
大神您好，请教一个问题：
背景故事如下：
  我使用CYLTabBarController的时候引用了RESideMenu，
  1.RESideMenu 作为AppDelegate的rootViewController，
  2.把RESideMenu 作为RESideMenu 的ContentViewController进行设置
产生了问题：
   在设置让TabBarItem只显示图标不显示文字的时候（设置方法是：通过不设置tabBarItemsAttributes中      的“CYLTabBarItemTitle”的键），结果：图片不是居中显示的，而是往上进行偏移；（通过设置imageInsets属性也是无效的）
测试：我把RESideMenu去掉后，进步会产生以上问题；
请大神帮忙看下，这两个框架是否存在兼容性问题

**Comment by ChenYilong** [comment]
嗯，兼容性我还没测试，稍后测试下。

**Comment by Zss1990** [comment]
- (CYLTabBarController *)cyl_tabBarController {}
这个方法里返回为空，造成调整图片位置没有成功

**Comment by Zss1990** [comment]
请问下，这个问题有更好的解决方案吗？

**Comment by ChenYilong** [comment]
在恰当的时间设置下，将第三个参数 `tabBarController` 替换为你初始化好的 CYLTabBarController。

 ```Objective-C
    objc_setAssociatedObject(self, @selector(cyl_tabBarController), tabBarController, OBJC_ASSOCIATION_ASSIGN);
 ```

**Comment by ChenYilong** [comment]
另外能否提供一个Demo，我帮你调试下。luohanchenyilong@163.com

**Comment by ChenYilong** [comment]
参考：https://github.com/ChenYilong/CYLTabBarController/issues?q=is%3Aissue+RESideMenu+is%3Aclosed
