### ISSUE TITLE
【重要】iOS 10 GM 系统下必现崩溃

### ISSUE THREAD

**Issue by devtofu** [ChenYilong/CYLTabBarController#87]
不知道是不是 iOS 10 GM 的问题，使用 **+plusChildViewController** 这个方式加载 vc ，导航栏上的 item 点击必崩

附上 demo 和 截图 .  
[CYLTabBarController-master Test.zip](https://github.com/ChenYilong/CYLTabBarController/files/469508/CYLTabBarController-master.Test.zip)

![image](https://cloud.githubusercontent.com/assets/12134966/18470721/9a7999ce-79e0-11e6-9f7e-20e03380af0f.png)

**Comment by a526592191** [comment]
我也是这个问题，这个怎么解？？？

**Comment by devtofu** [comment]
@a526592191 还没解决，暂时没用这个方式，重新弄了个 tabbar

**Comment by ChenYilong** [comment]
@a526592191  @devtofu 已经解决，详情见：https://github.com/ChenYilong/CYLTabBarController/issues/101
