### ISSUE TITLE
iOS 10 正式版下问题，Xcode 8 编译后。

### ISSUE THREAD

**Issue by EchoZuo** [ChenYilong/CYLTabBarController#88]
iOS 10正式版系统，项目在Xcode 8 编译后，tabbar出现了问题。进入程序tabbar上面出现黑线条，无法去除；并且首次运行进入后中间两个itme位置发生偏移，两个按钮均向中间靠拢，此时下方4个item均无法点击，但是中间按钮可以点击；随便进入一个二级界面后在回到一级界面，此时tabbar中间两个item位置归位，恢复正常，并且此时可以正常点击了。

附上图片，
图一：
首次进入出现问题的时候：
![1](https://cloud.githubusercontent.com/assets/14211725/18504533/60c99980-7a95-11e6-9734-04d9b48ef5e4.png)

图二：从二级界面回到一级界面后显示正常的界面：
![2](https://cloud.githubusercontent.com/assets/14211725/18504569/8ba0ad10-7a95-11e6-95cc-9346662a8c01.jpg)

**Comment by ChenYilong** [comment]
了解了，我看下

**Comment by EchoZuo** [comment]
您好，我给tabBarController的tabBarHeight设置为50之后，首次运行进入后中间两个itme位置发生偏移 这个问题解决了。设置为49也不行，为50就可以了。
但是目前出现的黑线的问题还没有解决，依旧存在。

**Comment by EchoZuo** [comment]
@ChenYilong 您好，我给tabBarController的tabBarHeight设置为50之后，首次运行进入后中间两个itme位置发生偏移 这个问题解决了。设置为49也不行，为50就可以了。
但是目前出现的黑线的问题还没有解决，依旧存在。

**Comment by EchoZuo** [comment]
您好，在1.6版本中，item发生偏移的问题是这样。当tabBarHeight 为49的时候，itme就会发生偏移，如之前提交的图片中的第一张，按钮会挤到中间。不为49的时候就没有问题。包括我这边再您这边提供的demo中也测试了下，也是如此。

**Comment by ChenYilong** [comment]
暂时没发现这个问题，同时为iOS10适配，更新到了v1.6.1，请更新重试，详见这里的讨论：https://github.com/ChenYilong/CYLTabBarController/issues/101

**Comment by lizzie8023** [comment]
@EchoZuo  
UITabBar.appearance().layer.borderWidth = 0.0
UITabBar.appearance().clipsToBounds = true
