### ISSUE TITLE
iOS  10 后tabbar 无法完成跳转；但是plusbutton 正常弹出；

### ISSUE THREAD

**Issue by ultimatevegance** [ChenYilong/CYLTabBarController#93]
我的是升级xcode8了；模拟器是ios10 ；运行后发现 tabbar不能点击跳转了；但plusbutton 还是可以使用；

**Comment by devSC** [comment]
我也是这情况.

**Comment by devSC** [comment]
已提Fix PR.

**Comment by devtofu** [comment]
@devSC 添加了这行代码，并不管用...

**Comment by ChenYilong** [comment]
@devSC 无法跳转是什么意思？

**Comment by ultimatevegance** [comment]
点击没有反应 ；不能调到相应的VC；之前是可以的；

**Comment by ChenYilong** [comment]
v1.6.1 已经修复该问题，请更新，相关的commit：https://github.com/ChenYilong/CYLTabBarController/commit/e86302b80e76bc3102f813f0d3adfe0464f92ac0

**Comment by ultimatevegance** [comment]
好的 ；O(∩_∩)O谢谢

**Comment by ChenYilong** [comment]
经测试iOS10.2版本已经修复了该问题，v1.6.1之前的版本也工作正常。
