### ISSUE TITLE
使用viewController.hidesBottomBarWhenPushed = YES来隐藏tabbar，点击pop的时候会出现window上移的现象

### ISSUE THREAD

**Issue by ArronMe** [ChenYilong/CYLTabBarController#94]
<img width="375" alt="1" src="https://cloud.githubusercontent.com/assets/16532586/19225853/cfd2c1fe-8ed5-11e6-87ed-53b725f9d820.png">

**Comment by ChenYilong** [comment]
请提供更多信息，或者直接给我发Demo，方便我定位问题：luohanchenyilong@163.com
