### ISSUE TITLE
tabBarHeight不设置时的异常

### ISSUE THREAD

**Issue by skyz319** [ChenYilong/CYLTabBarController#96]
tabBarHeight属性不设置的情况惠，tabBar可见但不可点。需在源文件中默认一个tabBarHeight值。

**Comment by ChenYilong** [comment]
v1.6.1 已经修复该问题，请更新，相关的commit：https://github.com/ChenYilong/CYLTabBarController/commit/e86302b80e76bc3102f813f0d3adfe0464f92ac0
