### ISSUE TITLE
咨询一个问题

### ISSUE THREAD

**Issue by EchoZuo** [ChenYilong/CYLTabBarController#97]
目前项目底部tabbar类似于咸鱼。在一级某个界面中，点击了tabbar中间的大按钮，如何获取到这个的点击响应？

**Comment by hugolubingshen** [comment]
这种问题就别问了，仔细看过代码都知道

**Comment by ChenYilong** [comment]
创建PlusButton时，自行处理，详见：https://github.com/ChenYilong/CYLTabBarController/blob/e86302b80e76bc3102f813f0d3adfe0464f92ac0/Example/Classes/View/CYLPlusButtonSubclass.m#L86
