### ISSUE TITLE
遇到一个诡异的问题

### ISSUE THREAD

**Issue by lilin87788** [ChenYilong/CYLTabBarController#99]
在我项目里面tabbar 运行后看不到 不知道去哪里了

**Comment by ChenYilong** [comment]
解决没有，我暂时没发现这个问题

**Comment by lilin87788** [comment]
解决了 目前只知道是另外一个开源代码 会干扰到你的类 ，我去掉以后Tabbar 就正常了

**Comment by lilin87788** [comment]
具体 如何干扰的 那个类代码量很大 大概是一个 objc methed replace  的  底层 方法造成的

**Comment by lilin87788** [comment]
Aspects
